# Sahulat Home generative search, Part 1: catalogue, utility definitions and embeddings

Sahulat Home is a fictional Pakistani household-goods store; all products, brands, prices and stock levels are synthetic. Its listings describe **features** (material, size, pieces) similar to what is standard practice in e-commerce.

However, Sahulat Home also offers generative, context-aware search. Shoppers can find products by what they need them for, not only by name. Results also take into account the page they searched from and what they have browsed and searched for during the current visit (categories, products and price range). Nothing is kept after the visit ends. This is especially useful because shoppers often know **what they need a product for but not what it’s called**

This notebook builds the layer that connects the two. In this part I:
1. audit the synthetic catalogue and fix the category set;
2. generate a utility-focused **semantic definition** for every product with an LLM, comparing two prompt versions;
3. hand-check a sample of definitions for accuracy;
4. embed the products for meaning-based search and save everything for the live site;
5. record tokens and cost.

In RAG (retrieval-augmented generation) terms, this is the retrieval side: the definitions and embeddings are what the search looks things up in. The generation side, a chat assistant that answers only from retrieved products, comes in Part 3.

**AI use.** The code was written with Claude (Anthropic) as a coding assistant. I made the design decisions, choosing between options Claude proposed. The runs, hand-check verdicts and observations are my own. `docs/DECISIONS.md` in the repository records what was tried, what changed and why.

## 1. Setup
Installs the two providers' libraries, reads the API keys from Colab Secrets (they are never printed), pulls the project from GitHub and loads the shared `search` package. The live website runs the same package, so the results below describe the deployed system, not a copy.

In [1]:
!pip install -q groq google-genai

import os, sys, json, random, subprocess, time
import pandas as pd
from google.colab import userdata

os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")
os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")
token = userdata.get("GITHUB_TOKEN")

REPO = "/content/data722-generative-search"
url = f"https://x-access-token:{token}@github.com/mahamnalavi/data722-generative-search.git"
if not os.path.exists(REPO):
    r = subprocess.run(["git", "clone", "-q", url, REPO], capture_output=True, text=True)
else:
    r = subprocess.run(["git", "-C", REPO, "pull", "-q"], capture_output=True, text=True)
print("GitHub:", "OK" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])
subprocess.run(["git", "-C", REPO, "config", "user.name", "Maham (Colab run)"])
subprocess.run(["git", "-C", REPO, "config", "user.email", "mahamnalavi@users.noreply.github.com"])

sys.path.insert(0, REPO)
os.chdir(REPO)
import search
from search import load_catalogue, keyword_index
from search.llm import GroqChat, GeminiEmbedder, USAGE
from search.definitions import PROMPT_V1, PROMPT_V2, build_prompt, definition_text, unsupported_claims
from search.semantic import save_index, rank
pd.options.display.max_colwidth = 140
os.makedirs("results", exist_ok=True)
print("Search code loaded:", search.VERSION)

GitHub: OK
Search code loaded: v2-context-chat

## 2. Catalogue audit
A per-category summary (size, product types, price range, stock) and basic data-quality checks, used to fix the category set on evidence.

In [2]:
products = load_catalogue()
df = pd.DataFrame(products)
audit = df.groupby("category").agg(
    products=("product_id", "count"),
    product_types=("product_type", "nunique"),
    price_min=("price_pkr", "min"), price_median=("price_pkr", "median"), price_max=("price_pkr", "max"),
    out_of_stock=("in_stock", lambda s: f"{(~s).mean():.0%}"),
)
display(audit)
variants = df.groupby("product_type").size()
print(f"Total: {len(df)} products, {df.product_type.nunique()} product types, "
      f"{(variants > 1).sum()} types sold in 2-3 price variants, {(~df.in_stock).sum()} out of stock")
print("Missing values:", int(df.isna().sum().sum()), "| Duplicate titles:", int(df.title.duplicated().sum()))
print("\nExample of one product type in several price variants (used to test budgets and price-based personalisation):")
display(df[df.product_type == "pressure_cooker"][["product_id", "title", "price_pkr", "stock_qty"]])

,products,product_types,price_min,price_median,price_max,out_of_stock
category,,,,,,
Furniture,44,37,1450,9475.0,64500,11%
Kitchenware,59,35,290,1250.0,11900,10%
Organizers,48,35,450,1620.0,4450,17%
Tools,44,37,250,1250.0,19900,7%

Total: 195 products, 144 product types, 49 types sold in 2-3 price variants, 22 out of stock
Missing values: 0 | Duplicate titles: 0

Example of one product type in several price variants (used to test budgets and price-based personalisation):

,product_id,title,price_pkr,stock_qty
19,KIT-020,"Aluminium Pressure Cooker, 5 Litre",5950,20
20,KIT-021,"Stainless Steel Pressure Cooker, 7 Litre, Induction Base",11900,3
21,KIT-022,"Mini Pressure Cooker, 3 Litre",4350,42

**Decision:** I kept the four categories (Kitchenware, Tools, Organizers, Furniture). They are reasonably balanced (44-59 products each), no data is missing, and the 195-product total is inside the planned 150-200 range.

**Observations:** The catalogue has 195 products across four categories: Kitchenware 59, Organizers 48, Tools 44, Furniture 44. That’s balanced enough that no category dominates the evaluation, and the total sits within the range of 150–200 that I planned.

Prices span very different ranges by category: Organizers stay between Rs 450 and Rs 4,450, while Furniture runs from Rs 1,450 to Rs 64,500 (median Rs 9,475). That matters for budget questions, because a phrase like “under 5,000” rules out most furniture but almost no organizers. 49 of the 144 product types come in two or three price variants, which is what lets me test price-based personalisation.

22 products (11%) are out of stock, with Organizers having the most (8), so stock limits are tested too. No values are missing and no titles are duplicated. I kept the four categories as they are.

## 3. Semantic definitions: first attempt (prompt v1)
A simple prompt asks `gpt-oss-120b` (on Groq) to describe 10 hard-to-name products. Each definition is then checked automatically for claims the catalogue does not support, for example "dishwasher safe" when the specs never say so.

This matters beyond accuracy. Under the Competition Commission of Pakistan's April 2023 deceptive-marketing guidelines (Section 10, Competition Act 2010), product claims must be substantiated, so a definition shown to shoppers cannot invent features.

In [3]:
llm = GroqChat()
by_id = {p["product_id"]: p for p in products}
SAMPLE = ["KIT-003", "KIT-025", "KIT-007", "TOL-001", "ORG-005", "FUR-001", "FUR-036", "KIT-053", "TOL-018", "KIT-015"]

def generate(version, ids, batch_size=5, task="definitions"):
    """Ask the model for definitions in batches of 5. Any product missing from a batch reply
    is retried on its own (twice); if it still fails, it gets a title-only fallback and is reported."""
    out = {}
    ok = lambda item: bool(item) and bool(definition_text(item))
    for i in range(0, len(ids), batch_size):
        batch = [by_id[x] for x in ids[i:i + batch_size]]
        try:
            data, _ = llm.chat_json([{"role": "user", "content": build_prompt(version, batch)}],
                                    task=f"{task}_{version}", max_tokens=2500, n_items=len(batch))
            for item in data.get("items", []):
                if item.get("product_id") in by_id and ok(item):
                    out[item["product_id"]] = item
        except Exception as e:
            print("  batch problem, retrying one by one:", type(e).__name__)
        for p in batch:
            for attempt in range(2):
                if p["product_id"] in out:
                    break
                try:
                    data, _ = llm.chat_json([{"role": "user", "content": build_prompt(version, [p])}],
                                            task=f"{task}_{version}", max_tokens=1200)
                    item = (data.get("items") or [{}])[0]
                    if ok(item):
                        out[p["product_id"]] = {**item, "product_id": p["product_id"]}
                except Exception as e:
                    print(f"  {p['product_id']} attempt {attempt + 1} failed:", type(e).__name__)
            if p["product_id"] not in out:
                print(f"  FALLBACK used for {p['product_id']} (title only); reported in the results")
                out[p["product_id"]] = {"product_id": p["product_id"], "what_it_is": p["title"], "fallback": True}
        print(f"  {version}: {len(out)}/{len(ids)} done")
    return out

print("Prompt v1:\n" + PROMPT_V1.split("Products:")[0])
v1 = generate("v1", SAMPLE)

def check_table(defs):
    rows = []
    for pid, d in defs.items():
        text = definition_text(d)
        rows.append({"product_id": pid, "title": by_id[pid]["title"], "definition": text,
                     "unsupported_claims": ", ".join(unsupported_claims(text, by_id[pid])) or "-"})
    return pd.DataFrame(rows)

t1 = check_table(v1)
display(t1)
print(f"v1: {(t1.unsupported_claims != '-').sum()} of {len(t1)} definitions contain a claim the catalogue does not support")
json.dump(v1, open("results/definitions_v1_sample.json", "w"), indent=1, ensure_ascii=False)

Prompt v1:
You write short descriptions for an online household-goods store in Pakistan.
For each product below, describe what it is and what people use it for.

Return JSON: {"items": [{"product_id": "...", "definition": "..."}]}


  v1: 5/10 done
  v1: 10/10 done

,product_id,title,definition,unsupported_claims
0,KIT-003,Adjustable Mandoline with 5 Thickness Settings,"A kitchen mandoline made of ABS with stainless‑steel blades, offering five adjustable thickness settings and a julienne insert, plus a h...",-
1,KIT-025,"Wooden Hand Churner (Madhani), 45 cm","A traditional wooden hand churner (Madhani) crafted from sheesham wood, 45 cm long with a star‑shaped churn head, used for manually chur...",-
2,KIT-007,Stainless Steel Bench Scraper with Measuring Edge,"A stainless‑steel bench scraper featuring a 15 × 11 cm blade, wooden handle, and built‑in inch and centimetre measuring marks, ideal for...",-
3,TOL-001,"Electronic Wall Scanner, 4-in-1","A 4‑in‑1 electronic wall scanner that detects wood studs, metal objects, live AC wires and deep‑scan targets, with an LCD display and po...",-
4,ORG-005,"Lazy Susan Turntable, 30 cm","A 30 cm clear acrylic Lazy Susan turntable that rotates 360°, providing easy access to spices, condiments or small kitchen items stored ...",-
5,FUR-001,"Cane Mooda Stool, Natural","A round stool made from woven cane and reed, standing 45 cm tall with a 40 cm seat diameter, ideal for casual seating in living rooms or...",-
6,FUR-036,"Wooden Folding Rehal, Carved","A hand‑carved Sheesham‑wood rehal that folds flat (30 cm when open), used as a decorative floor cushion or low seating piece in living r...",-
7,KIT-053,Glass Boil-Over Preventer Disc,"A 7 cm diameter disc of heat‑resistant glass that sits on top of a pot to prevent water or milk from boiling over, protecting stovetops ...",-
8,TOL-018,"Drain Auger, 5 m Steel Cable","A 5‑metre long, 6 mm spring‑steel cable with a crank‑drum handle, designed to clear clogs in drains and pipes.",-
9,KIT-015,"Cast Iron Tawa, 12 inch","A 12‑inch pre‑seasoned cast‑iron tawa, weighing about 2.1 kg, perfect for making flatbreads, pancakes, and stir‑frying on the stove.",perfect

v1: 1 of 10 definitions contain a claim the catalogue does not support

**Observations on v1:** The automatic check flagged only 1 of the 10 v1 definitions: “perfect” in the cast iron tawa’s definition, a marketing word. Reading them myself showed bigger problems the check could not see. Most definitions mainly repeat the specs (“made of ABS with stainless-steel blades… five thickness settings”) and only mention the use at the end, so they add little that a shopper would actually type.

Additionally, none include Urdu or Roman Urdu names, even for products shoppers know by those names. The rehal is described as “a decorative floor cushion or low seating piece”, when it is a folding stand for holding the Quran or a book while reading. That is a confidently wrong definition that passed the automatic check, because the check only looks for claim words, not for the wrong use. This is why v2 asks for structured uses, shopper phrases and local names, and why the hand-check and the judge are needed alongside the automatic check.

## 4. Semantic definitions: revised prompt (v2)
v2 targets the main risk in generated product text, unsupported claims. It restricts the model to the given facts, rules out safety, health, durability and marketing claims, and asks for structured fields (what it is, uses, shopper phrases, Urdu or Roman Urdu names). Structured fields can be checked one by one, and the local names give Urdu and Roman Urdu searches something to match.

The comparison below shows how v1 and v2 actually differ on the same 10 products. v2 then runs on all 195 products, in about 40 calls paced to stay under Groq's free limit of 8,000 tokens per minute.

In [4]:
print("Prompt v2:\n" + PROMPT_V2.split("Products:")[0])
v2_sample = generate("v2", SAMPLE)
t2 = check_table(v2_sample)
display(t2)
print(f"Flagged unsupported claims on the same 10 products: v1 = {(t1.unsupported_claims != '-').sum()}, "
      f"v2 = {(t2.unsupported_claims != '-').sum()}")

Prompt v2:
You write search definitions for an online household-goods store in Pakistan.
A shopper may not know a product's name, so they describe the job they need done.
For each product, write what it is FOR, in plain everyday words.

Rules:
1. Use only the facts given (title, category, specs). Do not add features, materials,
   certifications, safety, health or durability claims that are not in the facts.
2. Uses must follow directly from what the product is. No marketing words
   ("best", "premium", "perfect", "must-have").
3. Include phrases a shopper might type, in English, and common Urdu or Roman Urdu
   names only if you are confident they are used in Pakistan (otherwise leave the list empty).
4. Keep each field short.

Return JSON exactly in this shape:
{"items": [{"product_id": "...",
            "what_it_is": "one sentence",
            "used_for": ["2-4 short uses"],
            "shopper_phrases": ["3-5 things a shopper might type"],
            "local_names": ["0-3 Urdu or Roman Urdu names"]}]}


  v2: 5/10 done
  v2: 10/10 done

,product_id,title,definition,unsupported_claims
0,KIT-003,Adjustable Mandoline with 5 Thickness Settings,A hand‑held slicer with adjustable thickness settings and a julienne insert. Used for: thinly slice vegetables; make uniform potato chip...,-
1,KIT-025,"Wooden Hand Churner (Madhani), 45 cm",A wooden hand‑crank churner for making butter or curd. Used for: hand‑churn butter at home; make fresh curd or lassi; stir thick mixture...,-
2,KIT-007,Stainless Steel Bench Scraper with Measuring Edge,A stainless‑steel bench scraper with built‑in inch and centimetre measurement markings. Used for: scrape dough from work surface; measur...,-
3,TOL-001,"Electronic Wall Scanner, 4-in-1","A handheld electronic scanner that detects wood, metal, live AC wires and deep objects behind walls. Used for: locate studs in walls; fi...",-
4,ORG-005,"Lazy Susan Turntable, 30 cm",A clear acrylic rotating turntable for easy access to items on a kitchen shelf or countertop. Used for: store spices for quick reach; di...,-
5,FUR-001,"Cane Mooda Stool, Natural",A round stool made of cane and reed for sitting. Used for: extra seating in living room; footrest while watching TV; small table for hol...,-
6,FUR-036,"Wooden Folding Rehal, Carved",A hand‑carved sheesham wood folding rehal for holding the Qur'an. Used for: prayer stand; displaying books; decorative accent. Shoppers ...,-
7,KIT-053,Glass Boil-Over Preventer Disc,A glass disc placed on a pot to stop water from boiling over. Used for: prevent boil‑over while cooking rice; keep stovetop clean; reduc...,-
8,TOL-018,"Drain Auger, 5 m Steel Cable",A 5 m steel cable auger with a crank handle for clearing clogged drains. Used for: unclog bathroom sink; remove hair blockage in shower ...,-
9,KIT-015,"Cast Iron Tawa, 12 inch",A 12‑inch pre‑seasoned cast‑iron tawa for cooking flatbreads and pancakes. Used for: making roti or chapati; cooking pancakes; searing v...,-

Flagged unsupported claims on the same 10 products: v1 = 1, v2 = 0

In [5]:
t0 = time.time()
remaining = [p["product_id"] for p in products if p["product_id"] not in v2_sample]
v2 = {**v2_sample, **generate("v2", remaining)}
print(f"Generated {len(v2)} definitions in {(time.time() - t0) / 60:.1f} minutes")

payload = {"prompt_version": "v2", "model": llm.model, "generated": time.strftime("%Y-%m-%d %H:%M"),
           "items": {pid: {**v2[pid], "text": definition_text(v2[pid])} for pid in sorted(v2)}}
json.dump(payload, open("data/definitions_v2.json", "w"), indent=1, ensure_ascii=False)

all_checks = check_table(v2)
flagged = all_checks[all_checks.unsupported_claims != "-"]
has_local = sum(1 for d in v2.values() if d.get("local_names"))
fallbacks = [pid for pid, d in v2.items() if d.get("fallback")]
print(f"Fallback (title only) used for {len(fallbacks)} products: {fallbacks or 'none'}")
print(f"Automatic check, all {len(v2)} products: {len(flagged)} flagged ({len(flagged) / len(v2):.0%}); "
      f"{has_local} include Urdu/Roman Urdu names")
display(flagged)

  v2: 5/185 done
  v2: 10/185 done
  v2: 15/185 done
  v2: 20/185 done
  v2: 25/185 done
  v2: 30/185 done
  v2: 35/185 done
  v2: 40/185 done
  v2: 45/185 done
  v2: 50/185 done
  v2: 55/185 done
  v2: 60/185 done
  v2: 65/185 done
  v2: 70/185 done
  v2: 75/185 done
  v2: 80/185 done
  v2: 85/185 done
  v2: 90/185 done
  v2: 95/185 done
  v2: 100/185 done
  v2: 105/185 done
  v2: 110/185 done
  v2: 115/185 done
  v2: 120/185 done
  v2: 125/185 done
  v2: 130/185 done
  v2: 135/185 done
  v2: 140/185 done
  v2: 145/185 done
  v2: 150/185 done
  v2: 155/185 done
  v2: 160/185 done
  v2: 165/185 done
  v2: 170/185 done
  v2: 175/185 done
  v2: 180/185 done
  v2: 185/185 done
Generated 195 definitions in 7.3 minutes
Fallback (title only) used for 0 products: none
Automatic check, all 195 products: 6 flagged (3%); 162 include Urdu/Roman Urdu names

,product_id,title,definition,unsupported_claims
11,KIT-002,"Silicone Egg Yolk Separator, Food-Grade",A food‑grade silicone tool for separating egg yolks from whites. Used for: splitting yolk for sauces; collecting whites for baking; easy...,food grade
13,KIT-005,Heavy-Duty Zinc Alloy Garlic Press,A heavy‑duty garlic press made of zinc alloy with a chrome finish. Used for: pressing garlic cloves into paste; quickly mincing garlic f...,heavy duty
76,TOL-014,Heavy-Duty Caulking Gun,A steel-frame gun that pushes caulk out of standard cartridges. Used for: sealing gaps around windows; filling cracks in walls; applying...,heavy duty
79,TOL-017,"Flange Plunger, Heavy-Duty",A heavy‑duty plunger with a flange rubber cup and plastic handle. Used for: unclogging toilets with a flange cup; clearing bathroom drai...,heavy duty
101,TOL-040,Heavy-Duty Staple Gun with 600 Staples,A steel heavy‑duty staple gun that holds 600 staples (6‑10 mm). Used for: securing upholstery fabric; attaching carpet padding; fastenin...,heavy duty
131,ORG-027,"Bamboo Shoe Rack, 2 Tiers",A two‑tier bamboo shoe rack. Used for: hold up to 6 pairs of shoes; organize shoes in a natural wood look; save space in a hallway. Shop...,eco

**Correction:** Reading the 6 flagged rows, 5 were false alarms: the check treated “Heavy-Duty” in a title and “heavy duty” in a definition as different words. I fixed the check to treat hyphens as spaces and re-ran it below on the same definitions.

In [6]:
# Re-check with the corrected claim checker (hyphens treated as spaces). The original output above is kept.
import importlib, search.definitions as defs_mod
subprocess.run(["git", "-C", REPO, "pull", "-q"], check=True)
importlib.reload(defs_mod)
unsupported_claims = defs_mod.unsupported_claims
re_v1 = check_table(v1)
re_all = check_table(v2)
re_flagged = re_all[re_all.unsupported_claims != "-"]
print(f"Corrected check: v1 sample {(re_v1.unsupported_claims != '-').sum()} of 10 flagged; "
      f"all 195 v2 definitions: {len(re_flagged)} flagged ({len(re_flagged) / len(v2):.0%}), was 6")
display(re_flagged)
json.dump({"v1_sample_flagged": int((re_v1.unsupported_claims != '-').sum()), "v2_all_flagged": len(re_flagged),
           "v2_flagged_ids": re_flagged.product_id.tolist()}, open("results/claim_check_corrected.json", "w"), indent=1)

Corrected check: v1 sample 1 of 10 flagged; all 195 v2 definitions: 1 flagged (1%), was 6

,product_id,title,definition,unsupported_claims
131,ORG-027,"Bamboo Shoe Rack, 2 Tiers",A two‑tier bamboo shoe rack. Used for: hold up to 6 pairs of shoes; organize shoes in a natural wood look; save space in a hallway. Shop...,eco

**Observation:** On the same 10 products, v2 had no unsupported claim words (v1 had 1, “perfect”), and it fixed v1’s most serious error: the rehal went from “a decorative floor cushion” to “a folding stand for holding the Qur’an”. Structured fields made the uses explicit (“Used for: making roti or chapati”) instead of burying them after the specs. However, v2 is not perfect: it calls the madhani “hand-crank” when it is turned by hand. Across all 195 products, v2 generated every definition in 7.3 minutes with no fallbacks, and 162 include an Urdu or Roman Urdu name. The automatic check first flagged 6, but reading them showed 5 false alarms caused by my checker treating “Heavy-Duty” and “heavy duty” as different words. After fixing the checker, 1 genuine flag remains (“eco” for the bamboo shoe rack).

## 5. Hand check: definition accuracy
20 products, 5 per category, drawn at random with a fixed seed per category so the sample can be reproduced. I judged each definition against the product's facts:
- **Y**: accurate and useful
- **P**: partly right (a small error, or an obvious use missing)
- **N**: wrong or misleading

In [7]:
payload = json.load(open("data/definitions_v2.json"))   # reload, in case Colab restarted since section 4
HANDCHECK = []
for c in ["Kitchenware", "Tools", "Organizers", "Furniture"]:
    ids = sorted(p["product_id"] for p in products if p["category"] == c)
    HANDCHECK += sorted(random.Random("handcheck-" + c).sample(ids, 5))

for pid in HANDCHECK:
    p = by_id[pid]
    print(f"{pid} | {p['title']}  (Rs {p['price_pkr']:,})")
    print("   FACTS:", "; ".join(f"{k}: {v}" for k, v in p["attributes"].items()))
    print("   DEFINITION:", payload["items"][pid]["text"], "\n")

KIT-013 | Fine Mesh Conical Strainer (Chinois), 20 cm  (Rs 1,690)
   FACTS: material: Stainless steel 18/8; mesh: Extra fine; diameter: 20 cm
   DEFINITION: A 20 cm stainless steel conical strainer with an extra‑fine mesh. Used for: sieving fine sauces; removing seeds from purees; straining tea leaves; filtering powdered spices. Shoppers say: fine mesh strainer; conical chinois 20 cm; stainless steel tea strainer; sieve for sauces; small kitchen strainer. Also called: چینی سٹرینر, چینی سٹرینر 20 سینٹی میٹر.

KIT-030 | Fine Rasp Grater with Soft Grip  (Rs 1,250)
   FACTS: material: Stainless steel photo-etched blade; length: 30 cm; includes: Blade cover
   DEFINITION: A handheld stainless‑steel grater with a soft grip handle. Used for: grating cheese; shredding carrots; rubbing nutmeg; making zest. Shoppers say: cheese grater; fine grater for zest; stainless steel rasp; small kitchen grater. Also called: rasp grater, grater.

KIT-031 | 4-Sided Box Grater  (Rs 890)
   FACTS: material: Stainless steel; sides: 4 (fine, medium, coarse, slicer); height: 24 cm
   DEFINITION: A four‑sided stainless‑steel box grater with fine, medium, coarse and slicer sides. Used for: grating cheese; shredding vegetables; coarse grating potatoes; slicing cucumbers. Shoppers say: box grater 4 side; multi side grater; stainless steel grater; kitchen grater for veg. Also called: box grater, grater.

KIT-040 | Handheld Vegetable Spiralizer, 4 Blades  (Rs 1,190)
   FACTS: material: PP plastic, steel blades; blades: 4 interchangeable
   DEFINITION: A handheld tool with four interchangeable blades for turning vegetables into spirals or ribbons. Used for: making zucchini noodles; creating curly carrot strips; preparing decorative salad toppings. Shoppers say: vegetable spiralizer; zucchini noodles tool; spiral cut veggies; handheld veggie slicer. Also called: سبزی سپائرلائزر, سبزی کا سپائرل میکر.

KIT-041 | Cast Aluminium Lemon Squeezer  (Rs 790)
   FACTS: material: Enamel-coated aluminium; type: Hand press
   DEFINITION: A hand‑press lemon squeezer made of enamel‑coated cast aluminium. Used for: extracting juice from lemons; pressing small citrus fruits; making fresh lemonade. Shoppers say: lemon squeezer hand press; cast aluminium citrus press; manual lemon juicer. Also called: لیموں کا رس نکالنے والا, لیموں کا سqueezer.

TOL-003 | Magnetic Torpedo Level, 9 inch  (Rs 650)
   FACTS: length: 9 in; vials: 3; base: Magnetic
   DEFINITION: A 9‑inch magnetic level with three vials for checking straightness. Used for: checking walls for plumb; aligning shelves; installing picture frames. Shoppers say: level for wall mounting; magnetic level 9 inch; how to check if a surface is level. Also called: مقناطیسی لیول, magnetic level.

TOL-015 | Pipe Wrench, 14 inch  (Rs 1,650)
   FACTS: length: 14 in; material: Drop-forged steel; jaw: Up to 2 in
   DEFINITION: A 14‑inch pipe wrench made of drop‑forged steel for turning pipes. Used for: tightening pipe fittings; removing stuck pipe nuts; plumbing repairs. Shoppers say: 14 inch pipe wrench; pipe wrench steel; plumbing wrench. Also called: پائپ رنچ, pipe wrench.

TOL-030 | Retractable Utility Knife with 5 Blades  (Rs 450)
   FACTS: blade: 18 mm snap-off; spares: 5; lock: Auto-lock slider
   DEFINITION: A retractable utility knife that comes with five snap‑off blades. Used for: cutting cardboard or packaging; trimming carpet or vinyl; opening boxes. Shoppers say: retractable utility knife 5 blades; snap off knife for home; handheld cutting knife; utility knife with auto lock; box cutting knife. Also called: یوزٹیلیٹی نائف, کٹر چاقو.

TOL-036 | Wall Plug and Screw Kit, 200 Pieces  (Rs 690)
   FACTS: pieces: 200; sizes: 6 mm and 8 mm plugs, matching screws
   DEFINITION: A kit of 200 wall plugs and matching screws in 6 mm and 8 mm sizes. Used for: fixing shelves to walls; installing picture frames; mounting light fixtures. Shoppers say: wall plug and screw kit; 200 pieces plugs screws; 6mm and 8mm wall anchors; fixings for drywall. Also called: وال پلگ, سکرو کٹ.

TOL-039 | 3.6 V Cordless Screwdriver, USB  (Rs 3,650)
   FACTS: voltage: 3.6 V; battery: Li-ion 1500 mAh; bits: 10
   DEFINITION: A small cordless screwdriver that runs on a 3.6 V Li‑ion battery and includes 10 bits. Used for: tightening screws in furniture; assembling flat‑pack items; installing light fixtures; quick repairs without a cord. Shoppers say: cordless screwdriver; battery powered screwdriver; screwdriver with USB charger; small electric screwdriver; DIY screwdriver. Also called: بغیر تار کے سکرو ڈرائیور, cordless screwdriver.

ORG-003 | Adjustable Bamboo Drawer Dividers, Set of 4  (Rs 2,950)
   FACTS: material: Bamboo; length: Spring-loaded 44-55 cm; pieces: 4
   DEFINITION: A set of four bamboo drawer dividers that adjust to fit drawer width. Used for: separating utensils in kitchen drawer; organising office supplies; keeping cutlery sorted. Shoppers say: bamboo drawer dividers; adjustable drawer organizer; drawer separator set; kitchen drawer organizer bamboo; spring loaded drawer dividers.

ORG-005 | Lazy Susan Turntable, 30 cm  (Rs 1,290)
   FACTS: diameter: 30 cm; material: Clear acrylic; rotation: 360 degrees
   DEFINITION: A clear acrylic rotating turntable for easy access to items on a kitchen shelf or countertop. Used for: store spices for quick reach; display condiments on a countertop; organise small jars in cabinets. Shoppers say: lazy susan turntable 30 cm; clear acrylic rotating tray; kitchen turntable. Also called: لیزی سوزن.

ORG-014 | Clear Fridge Organizer Bins, Set of 4  (Rs 1,950)
   FACTS: pieces: 4; material: BPA-free PET; handles: Built-in
   DEFINITION: Clear PET bins with built-in handles for arranging items inside a refrigerator. Used for: store fruits and vegetables; separate dairy products; keep leftovers organized; stack items without sliding. Shoppers say: clear fridge bins; refrigerator organizer bins; transparent fridge storage; fridge bins set of 4.

ORG-020 | Velvet Hangers, Pack of 20  (Rs 1,890)
   FACTS: pieces: 20; material: Velvet-flocked ABS; hook: 360-degree
   DEFINITION: Velvet‑flocked plastic hangers with a 360‑degree hook. Used for: hang shirts; keep dresses from slipping; organize coats; store trousers. Shoppers say: velvet hangers pack; soft plastic hangers; 360 degree hook hangers; wardrobe velvet hangers.

ORG-034 | Over-the-Sink Roll-Up Drying Rack  (Rs 1,450)
   FACTS: size: 52 x 32 cm; material: Silicone-coated steel; folds: Rolls up
   DEFINITION: A roll‑up drying rack that fits over the sink, made of silicone‑coated steel. Used for: dry dishes in sink area; store small utensils while drying; save countertop space; easy to roll away. Shoppers say: over sink drying rack; roll up dish rack; silicone coated drying rack; sink countertop dryer; foldable dish rack. Also called: sink ke upar rack, roll up drying rack.

FUR-003 | Woven Rope Charpai, Sheesham Frame  (Rs 18,500)
   FACTS: material: Sheesham legs, nylon rope weave; size: 190 x 90 cm
   DEFINITION: A woven rope charpai with a sheesham wood frame. Used for: relaxing in the living room; outdoor seating on a balcony; guest sleeping area. Shoppers say: rope charpai; sheesham frame charpai; woven rope bed. Also called: چَرپائی, روپ چارپائی.

FUR-004 | Storage Ottoman, Fabric, 76 cm  (Rs 8,950)
   FACTS: size: 76 x 38 x 38 cm; material: Linen-look fabric, MDF; lid: Hinged
   DEFINITION: A fabric-covered ottoman with a hinged lid for hidden storage. Used for: extra seating; storing blankets or magazines; footrest in living room. Shoppers say: ottoman with storage; fabric storage ottoman; living room footrest; hidden storage ottoman. Also called: اُٹمان, Ottoman.

FUR-016 | Drop-Leaf Dining Table, Seats 2-4  (Rs 19,900)
   FACTS: size_open: 120 x 75 cm; size_folded: 75 x 40 cm; material: Rubberwood
   DEFINITION: A drop‑leaf dining table that seats 2‑4 people. Used for: small family meals; compact dining space; temporary work surface; folded storage when not in use. Shoppers say: drop leaf dining table; foldable dining table; 2 to 4 seat table; compact dining table. Also called: ڈائننگ ٹیبل, فولڈنگ ٹیبل.

FUR-023 | Sheesham Wood Bedside Table, Open Shelf  (Rs 12,500)
   FACTS: size: 45 x 40 x 55 cm; material: Solid sheesham; shelves: 1 open
   DEFINITION: A sheesham wood bedside table with an open shelf. Used for: holding a lamp or alarm clock; displaying books or decor; quick access to bedside items. Shoppers say: sheesham bedside table; wooden nightstand with shelf; open shelf bedside table; solid wood bedside table; bedroom table sheesham. Also called: شیشم ٹیبل, نائٹ اسٹینڈ.

FUR-039 | Single-Seat Recliner, Fabric  (Rs 54,500)
   FACTS: mechanism: Manual lever; material: Fabric, solid wood frame
   DEFINITION: A single‑seat fabric recliner with a manual lever and solid wood frame Used for: Relax and recline after work; Watch TV comfortably; Read a book in a cozy seat. Shoppers say: fabric recliner chair; single seat recliner; manual lever recliner; living room recliner; reclining chair. Also called: ریکلائنر.

In [9]:
# My verdicts: (Y / P / N, note)
VERDICTS = {
    "KIT-013": ("P", "Urdu name 'Chini strainer' is invented."), "KIT-030": ("P", "Zest and nutmeg are right, but a fine rasp isn’t really for “shredding carrots”; that’s a box grater."), "KIT-031": ("Y", "No issue observed"), "KIT-040": ("Y", "No issue observed"), "KIT-041": ("P", "Uses fine, but one local name is garbled mixed script:لیموں کا سqueezer"),
    "TOL-003": ("P", "Uses correct but Urdu name is not commonly used and doesn't imply the same product."), "TOL-015": ("Y", "No issue observed."), "TOL-030": ("P", "Uses fine; small spelling slip in the other second Urdu name (not cutter کٹر)"), "TOL-036": ("P", "Fixings for drywall: 6/8 mm wall plugs are for brick or concrete walls, which most Pakistani homes have, not drywall. This is a minor issue in use that needs correction."), "TOL-039": ("Y", "No issue observed."),
    "ORG-003": ("Y", "No issue observed."), "ORG-005": ("P", "Uses fine; Urdu should also have tranlation for 'kitchen table' and 'table' as they are more commonly used words."), "ORG-014": ("P", "Uses mainly correct but they also state 'Stack items without sliding' even though facts never say they stack. This is a small unsupported claim."), "ORG-020": ("Y", "No issue observed."), "ORG-034": ("Y", "No issue observed."),
    "FUR-003": ("P", "Uses are OK, but 'living room' isn’t where a charpai usually goes; the Urdu spelling چَرپائی is off and چارپائی is correct"), "FUR-004": ("P", "Uses are correct but Urdu spelling for Ottoman is incorrect; the correct is اوٹومن"), "FUR-016": ("Y", "No issue observed."), "FUR-023": ("Y", "No issue observed."), "FUR-039": ("Y", "No issue observed."),
}
assert sorted(VERDICTS) == sorted(HANDCHECK), "The IDs above must match the sample shown"
marks = [v for v, _ in VERDICTS.values()]
if "?" in marks:
    print(f"{marks.count('?')} products still marked '?'. Fill them in and run again.")
else:
    y, p_, n = marks.count("Y"), marks.count("P"), marks.count("N")
    print(f"Definition accuracy (hand check, n=20): strict {y / 20:.0%} (Y only), lenient {(y + p_) / 20:.0%} (Y + P); wrong: {n}")
    json.dump({pid: {"verdict": v, "note": n_} for pid, (v, n_) in VERDICTS.items()},
              open("results/definition_handcheck.json", "w"), indent=1)

Definition accuracy (hand check, n=20): strict 50% (Y only), lenient 100% (Y + P); wrong: 0

**Observation:** I judged 20 definitions (5 per category): 10 accurate (Y), 10 partly right (P), none wrong. That is 50% strict and 100% lenient accuracy. Observation highlights are:
1. Most P verdicts were about the local names, not the uses: an invented Urdu name (“Chini strainer” for a chinois), misspellings, and names that aren’t commonly used.
2. Four involved the uses or claims: a fine rasp described as “shredding carrots”, wall plugs “for drywall” (Pakistani walls are mostly brick), fridge bins said to “stack” when the facts don’t say so, and a charpai suggested for the living room. These are minor, so the uses are reliable enough to show shoppers in the “What it’s for” box, which shows uses only. The local names are not, so I keep them only as hidden search text.

A better fix would be a short hand-made glossary of common Urdu product names instead of letting the model invent them.

## 6. Embeddings
Gemini (`gemini-embedding-001`, 768 dimensions) turns each product's text into a vector that represents its meaning, so products can be matched to a query by meaning rather than shared words. Two indexes are saved, so that the effect of the definitions can be isolated in Part 2:
- **catalogue text**: title, subcategory and description, as written by the store
- **definitions**: title plus the AI definition

A quick side-by-side on 6 queries follows. The scored comparison on 114 labelled queries is in Part 2.

In [10]:
payload = json.load(open("data/definitions_v2.json"))
emb = GeminiEmbedder()
ids = [p["product_id"] for p in products]
cat_texts = [f'{p["title"]}. {p["subcategory"]}. {p["description"]}' for p in products]
def_texts = [f'{p["title"]}. {payload["items"][p["product_id"]]["text"]}' for p in products]

meta = {"model": emb.model, "dims": emb.dims, "task_type": "RETRIEVAL_DOCUMENT"}
cat_vecs = emb.embed(cat_texts, kind="document", task="embed_products")
save_index("emb_catalogue", ids, cat_vecs, {**meta, "text": "title + subcategory + description"})
def_vecs = emb.embed(def_texts, kind="document", task="embed_products")
save_index("emb_definitions_v2", ids, def_vecs, {**meta, "text": "title + definition v2"})
print(f"Saved 2 indexes: {len(cat_vecs)} products x {len(cat_vecs[0])} numbers each")

  Gemini rate limit; waiting 30s (attempt 1)
  Gemini rate limit; waiting 30s (attempt 2)
  Gemini rate limit; waiting 30s (attempt 3)
  Gemini rate limit; waiting 30s (attempt 1)
  Gemini rate limit; waiting 30s (attempt 1)
  Gemini rate limit; waiting 30s (attempt 2)
Saved 2 indexes: 195 products x 768 numbers each

In [11]:
from search.semantic import load_index
load_index.cache_clear()
idx_cat, idx_def = load_index("emb_catalogue"), load_index("emb_definitions_v2")
TRY = ["something to separate egg whites from yolks", "slice potatoes thin for chips",
       "pyaz barik katne wali cheez", "find the wooden beam behind my wall before drilling",
       "stop milk from boiling over", "seat for my elderly mother to pray"]
qvecs = emb.embed(TRY, kind="query", task="embed_queries")
title = lambda pid: by_id[pid]["title"][:45]
rows = []
for q, qv in zip(TRY, qvecs):
    kw = [title(pid) for pid, _ in keyword_index().search(q, 3)] or ["(no match)"]
    rows.append({"query": q,
                 "keyword top 3": " | ".join(kw),
                 "embeddings, catalogue text": " | ".join(title(pid) for pid, _ in rank(qv, idx_cat, 3)),
                 "embeddings, definitions": " | ".join(title(pid) for pid, _ in rank(qv, idx_def, 3))})
display(pd.DataFrame(rows))

,query,keyword top 3,"embeddings, catalogue text","embeddings, definitions"
0,something to separate egg whites from yolks,"Silicone Egg Yolk Separator, Food-Grade | Egg Holder Drawer for Fridge, 21 Eggs | 3-Piece Stainless Steel Egg Separator Set","Silicone Egg Yolk Separator, Food-Grade | 3-Piece Stainless Steel Egg Separator Set | Egg Holder Drawer for Fridge, 21 Eggs","3-Piece Stainless Steel Egg Separator Set | Silicone Egg Yolk Separator, Food-Grade | Egg Holder Drawer for Fridge, 21 Eggs"
1,slice potatoes thin for chips,(no match),"Adjustable Mandoline with 5 Thickness Setting | 8-Blade Apple Slicer and Corer | Compact V-Blade Mandoline, 3 Inserts","Adjustable Mandoline with 5 Thickness Setting | Compact V-Blade Mandoline, 3 Inserts | 4-Sided Box Grater"
2,pyaz barik katne wali cheez,(no match),"Pull-String Chopper, 900 ml, 5 Blades | Pull-String Manual Chopper, 500 ml | Adjustable Mandoline with 5 Thickness Setting","Adjustable Mandoline with 5 Thickness Setting | Pull-String Manual Chopper, 500 ml | Pizza Cutter Wheel with Finger Guard"
3,find the wooden beam behind my wall before drilling,Rubber Cup Plunger with Wooden Handle | Wall-Mounted Plastic Bag Holder | Wall Pegboard Kit with 10 Accessories,"Electronic Wall Scanner, 4-in-1 | Drill Bit Set, 13 Pieces, Masonry and Wood | Wall-Mounted Fold-Down Desk","Electronic Wall Scanner, 4-in-1 | Drill Bit Set, 13 Pieces, Masonry and Wood | Magnetic Torpedo Level, 9 inch"
4,stop milk from boiling over,"Glass Boil-Over Preventer Disc | Metal Bunk Bed, Single over Single | Over-the-Door Shoe Organizer, 24 Pockets","Glass Boil-Over Preventer Disc | Splatter Guard Screen, 33 cm | 3-Piece Stainless Steel Egg Separator Set","Glass Boil-Over Preventer Disc | Splatter Guard Screen, 33 cm | 3-Piece Stainless Steel Egg Separator Set"
5,seat for my elderly mother to pray,"Folding Steel Chair, Padded Seat | Single-Seat Recliner, Fabric | Foldable Prayer Chair with Backrest","Foldable Prayer Chair with Backrest | Wooden Rocking Chair | Folding Steel Chair, Padded Seat",Foldable Prayer Chair with Backrest | Wooden Rocking Chair | Floor Cushion Gaddi Set with Bolster

**Observations:** On these 6 examples, keyword search fails on 2 queries outright (“slice potatoes thin for chips” and the Roman Urdu “pyaz barik katne wali cheez” both return nothing). For “wooden beam behind my wall” it returns wrong products (a plunger, a bag holder), because it only matches shared words. Both meaning-based methods put a correct product first in all 6 cases, including the Roman Urdu query, where they found the chopper and the mandoline. To my surprise, meaning search on the store’s own text did about as well as on the AI definitions here, because the embedding model already links needs to product names quite well. So these 6 examples show that meaning search beats keyword search, but not yet whether the definitions add value on top. That is tested on 114 labelled questions in Part 2. The “rate limit, waiting” messages show the free Gemini tier slowing the run; the code waited and finished without errors.

## 7. Tokens and cost
Every AI call in this notebook is logged. The project runs on free tiers, so the actual cost is \$0. The estimate below uses published paid prices:
- Groq `gpt-oss-120b`: \$0.15 per million input tokens and \$0.60 per million output tokens (third-party price index, October 2026)
- Gemini `gemini-embedding-001`: \$0.15 per million tokens (Google Developers Blog)

Gemini does not report token counts for embeddings, so those are estimated at about 4 characters per token.

In [12]:
usage = pd.DataFrame(USAGE.summary()).T
display(usage)
print(f"Total tokens: {int(usage.tokens_in.sum() + usage.tokens_out.sum()):,} | "
      f"estimated cost at paid prices: ${usage.est_cost_usd.sum():.4f}")
usage.to_json("results/part1_usage.json", indent=1)

,model,calls,items,tokens_in,tokens_out,seconds,est_cost_usd
definitions_v1,openai/gpt-oss-120b,2,10,787,555,1.7,0.00045
definitions_v2,openai/gpt-oss-120b,39,195,22548,25568,69.9,0.01872
embed_products,gemini-embedding-001,20,390,25218,0,8.1,0.00378
embed_queries,gemini-embedding-001,1,6,52,0,0.5,0.00001

Total tokens: 74,728 | estimated cost at paid prices: $0.0230

## 8. Saving results
The definitions, both indexes and the result files are committed to the project repository. The live site redeploys from the repository, so it picks them up automatically.

In [13]:
files = ["data/definitions_v2.json", "data/emb_catalogue.json", "data/emb_definitions_v2.json", "results"]
subprocess.run(["git", "add", *files], check=True)
subprocess.run(["git", "commit", "-q", "-m", "Part 1 run: definitions v2, embeddings, hand-check, usage"])
subprocess.run(["git", "pull", "-q", "--rebase"])
r = subprocess.run(["git", "push", "-q"], capture_output=True, text=True)
print("Pushed to GitHub" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])
print(subprocess.run(["git", "log", "--oneline", "-1"], capture_output=True, text=True).stdout)

Pushed to GitHub
0f3527f Part 1 run: definitions v2, embeddings, hand-check, usage