# Sahulat Home generative search, Part 3: the "Ask Sahulat" chat, judged


Part 2 measured retrieval: does the right product come back? This part measures the **generation** side of the RAG system, the "Ask Sahulat" chat assistant on the live site. For each message, the assistant:
1. reads budget and stock limits by rules;
2. retrieves candidates with the same search as the search bar (meaning search on the AI definitions, chosen in Part 2), page and visit context included;
3. asks `gpt-oss-120b` (on Groq) to pick up to three candidates and explain each, in the shopper's language, or to say honestly that nothing fits;
4. checks the answer in code: products the search did not return are dropped, limits are re-checked, and reasons are scanned for unsupported claims.

**Questions:**
- Does the chat pick the right product more often than the search bar's first result?
- Does it stay grounded and within limits, and say "no close match" when it should?
- What does an independent judge (Gemini, a different company) think of its answers and of the Part 1 definitions, and how far can that judge be trusted, measured against my own checks?
- What does a chat turn cost?

**This is the second run.** The first run (`notebook/03a_chat_first_run.ipynb`, kept unchanged as evidence) found failures that a rule in the prompt alone did not prevent: English questions answered in Roman Urdu, a conversation that lost its topic, marketing words, and a product code shown to the shopper. I fixed them in code and ran the whole evaluation again. Section 6 compares the two runs.

**Method.** All 79 test questions, single turn and without context, so the numbers are comparable with Part 2. Then scripted multi-turn conversations with page context. Then the judge, and my hand-check of 16 judge verdicts (20%).

**AI use.** Code written with Claude (Anthropic) as a coding assistant. Design decisions, runs, hand-checks and observations are mine.

## 1. Setup
Loads the keys, pulls the project (including the outputs of Parts 1 and 2) and the settings tuned on dev, which are the same ones the live site uses.

In [1]:
!pip install -q groq google-genai

import os, sys, json, random, subprocess, time
import pandas as pd
from google.colab import userdata

os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")
os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")
token = userdata.get("GITHUB_TOKEN")
REPO = "/content/data722-generative-search"
url = f"https://x-access-token:{token}@github.com/mahamnalavi/data722-generative-search.git"
if not os.path.exists(REPO):
    r = subprocess.run(["git", "clone", "-q", url, REPO], capture_output=True, text=True)
else:
    r = subprocess.run(["git", "-C", REPO, "pull", "-q"], capture_output=True, text=True)
print("GitHub:", "OK" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])
subprocess.run(["git", "-C", REPO, "config", "user.name", "Maham (Colab run)"])
subprocess.run(["git", "-C", REPO, "config", "user.email", "mahamnalavi@users.noreply.github.com"])
sys.path.insert(0, REPO); os.chdir(REPO)

for f in ["data/definitions_v2.json", "data/emb_definitions_v2.json", "results/query_vectors.json", "results/tuned_params.json"]:
    assert os.path.exists(f), f"{f} is missing: run Notebooks 01 and 02 first"
from search import chat, pipeline, products_by_id, load_catalogue
from search import evaluate as ev
from search.llm import GroqChat, GeminiEmbedder, USAGE, PRICES
from search.judge import GeminiJudge, run_batches, CHAT_RUBRIC, DEF_RUBRIC
pd.options.display.max_colwidth = 90

rows = json.load(open("data/eval_queries.json", encoding="utf-8"))
test = [r for r in rows if r["split"] == "test"]
by_q = {r["qid"]: r for r in rows}
by_id = products_by_id()
catalogue = load_catalogue()
live = json.load(open("results/tuned_params.json"))["live"]
qvecs = json.load(open("results/query_vectors.json"))
vec_by_text = {ev.query_text_for_embedding(r["query"]): qvecs[r["qid"]] for r in rows}
emb = GeminiEmbedder()
def embed_fn(texts):
    """Re-use the Part 2 query embeddings; embed only texts not seen before (multi-turn demos)."""
    missing = [t for t in texts if t not in vec_by_text]
    if missing:
        vec_by_text.update(zip(missing, emb.embed(missing, kind="query", task="embed_chat_queries")))
    return [vec_by_text[t] for t in texts]
llm = GroqChat()
print(f"Ready: {len(test)} test questions; live settings loaded")

GitHub: OK
Ready: 79 test questions; live settings loaded

**What changed since the first run.** Each fix moves a rule from the prompt into code, because the first run showed the prompt alone was not enough:

| First-run failure | Evidence | Fix |
|---|---|---|
| Replies in the wrong language | 4 of the 16 sample replies printed in the first run were English questions answered in Roman Urdu; a Roman Urdu message answered in Urdu script | The shopper's language is detected by rules and stated in the message ("REPLY LANGUAGE"); if the reply comes back in another language, the model is asked once more |
| Conversation lost its topic | "only ones in stock please" searched without "rotis" (two messages back), so the chat said nothing fits | A follow-up with no product words of its own is searched together with the last message that named a need; filler words ("only", "ones", "please", "sasta", "wala") no longer count as product words |
| Marketing words | 7 answers used "perfect" in a reason | The prompt names the banned words, and the code replaces any that slip through ("perfect" → "right", "ideal" → "suitable") before the shopper sees them; the model's original wording is still recorded |
| Product codes shown | "Sab se sasta TOL-027 hai" | Any product code in the reply is replaced by the product's name |
| Forced picks | A butter churner offered "for making rotis" | The prompt now says to pick a product only if its facts or uses show it does the job, and that fewer picks are better than a weak one |

Everything else (the search, the settings from Part 2, the test questions, the judge) is unchanged, so the two runs can be compared directly.

## 2. The context design
This is what the chat model sees for every message. The system prompt sets the rules: candidates only, at most three, reasons from the facts, honest "no close match", the shopper's language, and context as a soft hint. The message then gives the conversation, the limits, a short summary of the page and visit, and the candidate products with their facts and AI-written uses from Part 1.

Below are the rules, and the complete message for one test question.

In [2]:
print(chat.SYSTEM_PROMPT)
ex = next(r for r in test if r["style"] == "constraint")
msgs = [{"role": "user", "content": ex["query"]}]
cons = chat.merged_constraints([ex["query"]])
cands = []
for t, v in zip(chat.retrieval_texts([ex["query"]]), embed_fn([ev.query_text_for_embedding(ex["query"])])):
    cands += [p["product_id"] for p in pipeline.run(t, mode=pipeline.LIVE_MODE, query_vec=v, k=6, params=live, constraints=cons)["results"]]
print("\n----- message for:", ex["query"], "-----\n")
print(chat.build_user_prompt(msgs, cons, {"page_category": "Kitchenware", "categories_browsed": {"Kitchenware": 2},
                                          "product_types_viewed": ["tawa"], "price_band": {"min": 1850, "max": 3290, "median": 2350}}, cands))

You are "Ask Sahulat", the shopping assistant of Sahulat Home, an online household-goods store in Pakistan.

Rules:
1. Recommend ONLY products listed under CANDIDATES, by their id. Never invent products, prices, stock or features.
2. Pick at most 3, best first. Pick a candidate only if its facts or uses show it does what the shopper asked; fewer picks are better than a weak one. For each, give one short reason that follows from its listed facts or uses.
3. Candidates already meet the stated budget and stock limits. If the shopper asks for cheaper, prefer lower prices.
4. If no candidate does what the shopper needs, set "no_match" to true, say so plainly, and suggest different words to search. Never force a product.
5. Write the reply and every reason in the REPLY LANGUAGE given in the message.
6. PAGE and VISIT are soft hints for unclear requests only. The shopper's own words always win.
7. Keep "reply" under 60 words. No marketing words such as "perfect", "ideal", "best", "premium". Refer to products by name, never by id.

Return JSON only: {"reply": "...", "picks": [{"id": "...", "why": "..."}], "no_match": false}

----- message for: pressure cooker under 5000 -----

CONVERSATION (latest last):
Shopper: pressure cooker under 5000

REPLY LANGUAGE: English
LIMITS: max price Rs 5,000
PAGE: opened from the Kitchenware page | VISIT: browsed Kitchenware (2 pages); viewed tawa; prices viewed Rs 1,850 to Rs 3,290

CANDIDATES:
- KIT-022 | Mini Pressure Cooker, 3 Litre | Rs 4,350 | in stock | uses: quickly cooking small portions of dal; making single‑serve soups; softening vegetables; preparing small batches of rice | specs: capacity: 3 L; material: Hard aluminium; safety: Gasket release window
- KIT-053 | Glass Boil-Over Preventer Disc | Rs 450 | in stock | uses: prevent boil‑over while cooking rice; keep stovetop clean; reduce mess from sauces | specs: material: Heat-resistant glass; diameter: 7 cm
- KIT-043 | Insulated Hot Pot Casserole, 2.5 Litre | Rs 1,890 | in stock | uses: keeping soups hot for serving; transporting stews to a gathering; serving hot dishes at a buffet | specs: capacity: 2.5 L; material: Stainless steel inner, PU insulation; lid: Locking
- KIT-005 | Heavy-Duty Zinc Alloy Garlic Press | Rs 1,150 | in stock | uses: pressing garlic cloves into paste; quickly mincing garlic for curries; adding fresh garlic flavor without chopping | specs: material: Zinc alloy; finish: Chrome; length: 18 cm
- KIT-006 | Rocker Garlic Crusher, Stainless Steel | Rs 890 | in stock | uses: crushing garlic cloves into fine pieces; making garlic paste without a board; quickly preparing garlic for sauces | specs: material: Stainless steel; shape: Curved rocker; length: 13 cm
- KIT-019 | Non-Stick Karahi with Glass Lid, 26 cm | Rs 4,250 | in stock | uses: frying vegetables; making curries; stir‑frying meat; cooking eggs | specs: material: Aluminium, non-stick; diameter: 26 cm; lid: Tempered glass

**Observations:** This is the context design at the centre of the chat. The model never searches the catalogue itself: it receives one message built by code, with five parts:

1. The conversation (the last 6 messages).
2. The limits, read by rules, not by the model (“max price Rs 5,000”).
3. The page and visit summary, marked as a soft hint (rule 6). The visit in this example is made up for illustration; section 3 sends no context.
4. The candidates: up to 6 products from the same search the site uses, each with its id, price, stock, specs and the uses from my Part 1 definitions.
5. The reply language (“REPLY LANGUAGE: English”), detected from the shopper’s words by rules. The first run showed that asking the model to match the shopper’s language was not reliable on its own.

The example shows why this order matters. The budget filter runs before the model sees anything, so the Rs 5,950 and Rs 11,900 pressure cookers are not candidates at all. Only the Rs 4,350 mini cooker is, and the model cannot break the budget without inventing a product, which the code would drop (rule 1 and the grounding check). The other five candidates are weaker matches (a boil-over disc, a hot pot, garlic presses, a karahi), because search always fills the list. That tests rule 4: the model should pick only the mini cooker and not force the rest. Giving each product’s uses, not just its specs, lets the model explain a pick in the shopper’s terms (“for small portions of dal”) while staying within the facts. Asking for JSON with product ids, not free text, is what lets the code check every pick.

## 3. The chat on all 79 test questions
Each question is sent as a single message, with no context, using the same code as the live site. Answers are saved as they arrive. The calls are paced to Groq's free limit of 8,000 tokens per minute, so expect 12-15 minutes. If Groq's daily limit runs out part-way, the affected questions are marked as fallbacks; wait, then re-run this cell and it retries only those.

In [3]:
RUNS_FILE = "results/chat_test_runs.json"
runs = json.load(open(RUNS_FILE)) if os.path.exists(RUNS_FILE) else {}
t0 = time.time()
for i, r in enumerate(test, start=1):
    if r["qid"] in runs and not runs[r["qid"]].get("fallback"):
        continue   # already answered by the chat model (fallbacks are retried)
    res = chat.respond([{"role": "user", "content": r["query"]}], context=None, embed_fn=embed_fn, llm=llm, params=live)
    runs[r["qid"]] = {"reply": res["reply"], "picks": [p["product_id"] for p in res["products"]],
                      "whys": [p["why"] for p in res["products"]], "no_match": res["no_match"],
                      "search_no_close_match": res["search_no_close_match"], **res["diagnostics"]}
    if i % 5 == 0 or i == len(test):
        json.dump(runs, open(RUNS_FILE, "w"), indent=1, ensure_ascii=False)
        print(f"  {len(runs)}/{len(test)} answered ({(time.time() - t0) / 60:.1f} min)")
json.dump(runs, open(RUNS_FILE, "w"), indent=1, ensure_ascii=False)
fallbacks = [q for q, x in runs.items() if x.get("fallback")]
print(f"Done: {len(runs)} answers; chat model unavailable (search results shown instead) for {len(fallbacks)}")

  5/79 answered (0.0 min)
  10/79 answered (1.0 min)
  15/79 answered (2.0 min)
  20/79 answered (2.1 min)
  25/79 answered (3.1 min)
  30/79 answered (4.1 min)
  35/79 answered (4.1 min)
  40/79 answered (5.1 min)
  45/79 answered (6.1 min)
  50/79 answered (7.1 min)
  55/79 answered (7.2 min)
  60/79 answered (8.2 min)
  65/79 answered (9.2 min)
  70/79 answered (10.2 min)
  75/79 answered (10.3 min)
  79/79 answered (11.2 min)
Done: 79 answers; chat model unavailable (search results shown instead) for 0

**Observation:** As in the first run, all 79 test questions were answered by the chat model in 11.2 minutes, with no fallbacks. The time is mostly the pacing that keeps the run within Groq’s free limit. The language retries added with the fixes did not noticeably slow the run; section 4 shows how many were needed.

## 4. Automatic scores
The chat's first suggestion compared with the search bar's first result on the same questions, plus the checks done in code: grounding, limits, unsupported claim words and no-match handling.

In [4]:
search_runs = {x["qid"]: x for x in ev.run_queries(test, pipeline.LIVE_MODE, qvecs, params=live)}
def rel(q): return set(by_q[q]["relevant_ids"])
ans = [r["qid"] for r in test if not r["expects_no_match"]]
nom = [r["qid"] for r in test if r["expects_no_match"]]
rate = lambda xs: round(sum(xs) / len(xs), 3) if xs else None

chat_first = {q: bool(runs[q]["picks"]) and runs[q]["picks"][0] in rel(q) for q in ans}
chat_any = {q: any(p in rel(q) for p in runs[q]["picks"]) for q in ans}
search_first = {q: bool(search_runs[q]["ids"]) and search_runs[q]["ids"][0] in rel(q) for q in ans}
search_top3 = {q: any(i in rel(q) for i in search_runs[q]["ids"][:3]) for q in ans}
viol = sum(1 for q in runs for pid in runs[q]["picks"]
           if (by_q[q]["expected_max_price"] is not None and by_id[pid]["price_pkr"] > by_q[q]["expected_max_price"])
           or (by_q[q]["expected_in_stock"] and not by_id[pid]["in_stock"]))
chat_cw = [(not runs[q]["no_match"]) and (q in nom or not runs[q]["picks"] or runs[q]["picks"][0] not in rel(q)) for q in runs]
search_cw = [(not search_runs[q]["no_close_match"]) and (q in nom or not search_runs[q]["ids"] or search_runs[q]["ids"][0] not in rel(q)) for q in runs]

summary = pd.DataFrame({
    "search bar": {"first result correct": rate(list(search_first.values())),
                            "a correct product among the first 3": rate(list(search_top3.values())),
                            "correct 'no close match'": rate([search_runs[q]["no_close_match"] for q in nom]),
                            "wrongly says 'no close match'": rate([search_runs[q]["no_close_match"] for q in ans]),
                            "confidently wrong": rate(search_cw)},
    "Ask Sahulat chat": {"first result correct": rate(list(chat_first.values())),
                         "a correct product among the first 3": rate(list(chat_any.values())),
                         "correct 'no close match'": rate([runs[q]["no_match"] for q in nom]),
                         "wrongly says 'no close match'": rate([runs[q]["no_match"] for q in ans]),
                         "confidently wrong": rate(chat_cw)}})
display(summary)
dropped = sum(len(x["dropped_ids"]) for x in runs.values())
flagged = {q: x["claim_flags"] for q, x in runs.items() if x["claim_flags"]}
n_picks = sum(len(x["picks"]) for x in runs.values())
print(f"Grounding: {dropped} suggested product ids were not among the search candidates and were dropped by code")
print(f"Limits: {viol} of {n_picks} shown picks break the question's budget or stock limit")
print(f"Unsupported claim words in reasons: {len(flagged)} answers flagged {flagged if flagged else ''}")

style_rows = {}
for r in test:
    if r["expects_no_match"]:
        continue
    s = style_rows.setdefault(r["style"], {"search first": [], "chat first": []})
    s["search first"].append(search_first[r["qid"]]); s["chat first"].append(chat_first[r["qid"]])
display(pd.DataFrame({k: {c: rate(v) for c, v in d.items()} for k, d in style_rows.items()}).T)

# Checks added after the first run: reply language, words replaced before the shopper sees them, product codes
lang = {q: (chat.detect_language(by_q[q]["query"]), x.get("language_retry", False), chat.detect_language(x["reply"])) for q, x in runs.items()}
mismatch = [q for q, (want, _, got) in lang.items() if got != want and not (want == "roman_urdu" and got == "english")]
print(f"Reply language: {len(mismatch)} of {len(runs)} replies not in the shopper's language {mismatch if mismatch else ''}; "
      f"retried once for {sum(r for _, r, _ in lang.values())}")
cleaned = {q: x["cleaned"] for q, x in runs.items() if x.get("cleaned")}
print(f"Replaced before the shopper saw them (marketing words, product codes): {len(cleaned)} answers {cleaned if cleaned else ''}")

                                     search bar  Ask Sahulat chat
first result correct                      1.000             0.957
a correct product among the first 3       1.000             0.957
correct 'no close match'                  0.333             0.889
wrongly says 'no close match'             0.014             0.043
confidently wrong                         0.076             0.013

Grounding: 1 suggested product ids were not among the search candidates and were dropped by code
Limits: 0 of 97 shown picks break the question's budget or stock limit
Unsupported claim words in reasons: 0 answers flagged

            search first  chat first
name                 1.0       0.941
precise              1.0       1.000
vague                1.0       0.909
constraint           1.0       1.000
urdu                 1.0       0.889
trap                 1.0       1.000

Reply language: 0 of 79 replies not in the shopper's language ; retried once for 0
Replaced before the shopper saw them (marketing words, product codes): 1 answers {'Q006': ['ideal']}

**Observations:** On ranking, the second run matches the first: the chat put a correct product first for 67 of 70 answerable questions (0.96), against 1.00 for the search bar, and said “no close match” for 8 of the 9 things the store doesn’t sell, against 3 for the search bar. All three misses are now over-caution, answerable questions it called “no close match” (4.3%, up from 2.9%), rather than wrong picks. Its confidently-wrong rate fell to 1.3% (1 of 79), a sixth of the search bar’s 7.6%. It also showed fewer products: 97 picks against 121 in the first run, so the new rule to skip weak picks took effect.

The fixes show clearly in the checks. Every reply was in the shopper’s language (0 of 79 wrong, and no retry was needed), so stating the language in the message was enough. No reason contained a claim word (0, against 7 answers with “perfect” in the first run), and the code replaced the one remaining marketing word (“ideal”) before the shopper saw it. The grounding check dropped one suggested product that search had not returned, which shows why that check stays in code. No pick broke a budget or stock limit. This is one run each, and the model’s answers vary from run to run, so a difference of one question (2 vs 3 cautious answers) is within normal variation. The language and claim-word changes are too large for that.

## 5. Multi-turn conversations and context
Three scripted conversations, run exactly as the live site runs them:
- **A.** A follow-up that tightens the budget, then adds stock, opened from the Kitchenware page.
- **B.** Roman Urdu, with a "cheaper" follow-up.
- **C.** Opened from the Furniture page while the shopper describes a plumbing problem. Their own words should win over the page.

In [5]:
def converse(turns, context):
    msgs = []
    for text in turns:
        msgs.append({"role": "user", "content": text})
        res = chat.respond(msgs, context=context, embed_fn=embed_fn, llm=llm, params=live)
        msgs.append({"role": "assistant", "content": res["reply"]})
        shown = "; ".join(f'{p["title"]} (Rs {p["price_pkr"]:,}, {"in stock" if p["in_stock"] else "out of stock"})' for p in res["products"]) or "(none)"
        print(f"SHOPPER: {text}\nASSISTANT: {res['reply']}\n   shown: {shown}\n   limits: {res['constraints']}\n")

kitchen = {"page_category": "Kitchenware", "categories_browsed": {"Kitchenware": 3}, "product_types_viewed": ["karahi", "tawa"],
           "price_band": {"min": 1850, "max": 4250, "median": 2350}}
furniture = {"page_category": "Furniture", "categories_browsed": {"Furniture": 4}, "product_types_viewed": ["sofa_cum_bed"],
             "price_band": {"min": 20000, "max": 64500, "median": 46500}}
print("=== A ==="); converse(["I need something for making rotis at home", "something cheaper, under 2000", "only ones in stock please"], kitchen)
print("=== B ==="); converse(["bijli chali jaye to roshni ke liye kuch chahiye", "is se sasta wala?"], None)
print("=== C ==="); converse(["my kitchen sink is blocked, water won't drain"], furniture)

=== A ===
SHOPPER: I need something for making rotis at home
ASSISTANT: You can roll the dough with the Wooden Chakla Belan Set, and cook the rotis on the Granite‑Coated Flat Tawa.
   shown: Wooden Chakla Belan Set, 10 inch (Rs 1,290, in stock); Granite-Coated Flat Tawa, 12 inch, Induction Base (Rs 3,290, in stock)
   limits: {'max_price': None, 'in_stock': False}

SHOPPER: something cheaper, under 2000
ASSISTANT: You could use the Wooden Chakla Belan Set for rolling the dough and the Steel Chimta to flip the rotis while cooking.
   shown: Wooden Chakla Belan Set, 10 inch (Rs 1,290, in stock); Steel Chimta, Flat 14 inch (Rs 390, in stock)
   limits: {'max_price': 2000, 'in_stock': False}

SHOPPER: only ones in stock please
ASSISTANT: The Wooden Chakla Belan Set lets you roll the dough easily, and the Steel Chimta is handy for flipping the rotis while cooking.
   shown: Wooden Chakla Belan Set, 10 inch (Rs 1,290, in stock); Steel Chimta, Flat 14 inch (Rs 390, in stock)
   limits: {'max_price': 2000, 'in_stock': True}

=== B ===
SHOPPER: bijli chali jaye to roshni ke liye kuch chahiye
ASSISTANT: Aap ke liye Rechargeable LED Emergency Light aur Rechargeable LED Bulb dono achhe hain, dono power outage mein roshni dete hain.
   shown: Rechargeable LED Emergency Light, 60 LEDs (Rs 2,450, in stock); Rechargeable LED Bulb, 12 W, B22 (Rs 990, in stock)
   limits: {'max_price': None, 'in_stock': False}

SHOPPER: is se sasta wala?
ASSISTANT: Aap ke liye Rechargeable LED Bulb Rs 990 mein sasta hai aur power outage mein roshni deta hai.
   shown: Rechargeable LED Bulb, 12 W, B22 (Rs 990, in stock)
   limits: {'max_price': None, 'in_stock': False}

=== C ===
SHOPPER: my kitchen sink is blocked, water won't drain
ASSISTANT: Try a Drain Auger to reach deep clogs, or a plunger for simpler blockages.
   shown: Drain Auger, 5 m Steel Cable (Rs 1,890, in stock); Rubber Cup Plunger with Wooden Handle (Rs 590, in stock)
   limits: {'max_price': None, 'in_stock': False}

**Observations:** All four failures from the first run’s conversations are fixed. In conversation A, “only ones in stock please” now keeps the topic: the chat again suggests the chakla belan (Rs 1,290) and chimta (Rs 390), both in stock and under the Rs 2,000 limit from the turn before, instead of saying nothing fits. It also answers in English, and no longer offers a butter churner “for making rotis”. In conversation B, the Roman Urdu question gets a Roman Urdu reply (the first run switched to Urdu script), and “is se sasta wala?” names the Rs 990 bulb instead of showing its product code. Conversation C still shows the shopper’s words winning over the page: opened from the Furniture page, “my kitchen sink is blocked” got a drain auger and a plunger. Budget and stock limits were carried correctly across every turn, as before. These are three scripted conversations run once, so they show that the specific failures are fixed, not that the chat never loses a topic.

## 6. Before and after the fixes
The first run's numbers come from `results/part3_first_run.json`, read from the printed outputs of `03a_chat_first_run.ipynb` (its raw answer files were lost when that Colab session ended before they were saved). The language check on the first run is limited to the 16 answers printed there, so the same 16 questions are compared here.

In [6]:
first = json.load(open("results/part3_first_run.json"))
f4 = first["section4_summary"]
sample = [d["qid"] for d in first["section7_sample"]]
lang_first = len(first["section7_language_mismatches"])
lang_now = len([q for q in sample if q in mismatch])
claims_now_written = sum(1 for x in runs.values() if x["claim_flags"])
compare = pd.DataFrame({
    "first run": {"first result correct (70 answerable)": f4["first result correct"]["Ask Sahulat chat"],
                  "correct 'no close match' (9)": f4["correct 'no close match'"]["Ask Sahulat chat"],
                  "wrongly says 'no close match'": f4["wrongly says 'no close match'"]["Ask Sahulat chat"],
                  "confidently wrong (79)": f4["confidently wrong"]["Ask Sahulat chat"],
                  "answers with a claim word written by the model": first["claim_word_answers"],
                  "answers with a claim word shown to the shopper": first["claim_word_answers"],
                  "wrong reply language, same 16 questions": f"{lang_first}/16"},
    "second run (fixed)": {"first result correct (70 answerable)": summary.loc["first result correct", "Ask Sahulat chat"],
                  "correct 'no close match' (9)": summary.loc["correct 'no close match'", "Ask Sahulat chat"],
                  "wrongly says 'no close match'": summary.loc["wrongly says 'no close match'", "Ask Sahulat chat"],
                  "confidently wrong (79)": summary.loc["confidently wrong", "Ask Sahulat chat"],
                  "answers with a claim word written by the model": claims_now_written,
                  "answers with a claim word shown to the shopper": 0,
                  "wrong reply language, same 16 questions": f"{lang_now}/16"}})
display(compare)
print(f"Wrong reply language across all 79 (second run only): {len(mismatch)}")
print("\nFirst run, conversation A (for comparison with section 5 above):")
print(first["section5_conversations"].split("=== B ===")[0])
json.dump(compare.astype(str).to_dict(), open("results/part3_before_after.json", "w"), indent=1)

                                               first run second run (fixed)
first result correct (70 answerable)               0.957              0.957
correct 'no close match' (9)                       0.889              0.889
wrongly says 'no close match'                      0.029              0.043
confidently wrong (79)                             0.025              0.013
answers with a claim word written by the model         7                  0
answers with a claim word shown to the shopper         7                  0
wrong reply language, same 16 questions             4/16               0/16

Wrong reply language across all 79 (second run only): 0

First run, conversation A (for comparison with section 5 above):
=== A ===
SHOPPER: I need something for making rotis at home
ASSISTANT: Here are suitable items:
   shown: Granite-Coated Flat Tawa, 12 inch, Induction Base (Rs 3,290, in stock); Wooden Chakla Belan Set, 10 inch (Rs 1,290, in stock)
   limits: {'max_price': None, 'in_stock': False}

SHOPPER: something cheaper, under 2000
ASSISTANT: Here are some affordable options for making rotis:
   shown: Wooden Chakla Belan Set, 10 inch (Rs 1,290, in stock); Steel Chimta, Flat 14 inch (Rs 390, in stock); Wooden Hand Churner (Madhani), 45 cm (Rs 650, in stock)
   limits: {'max_price': 2000, 'in_stock': False}

SHOPPER: only ones in stock please
ASSISTANT: Maaf, in items mein roti banane ke liye koi cheez nahi hai. Aap "tawa", "roti maker" ya "chapati press" jaise lafz try karen.
   shown: (none)
   limits: {'max_price': 2000, 'in_stock': True}

**Observations:** The fixes removed the failures they targeted without costing accuracy. First-place accuracy (0.957) and correct “no close match” (8 of 9) are identical across the two runs. The chat was confidently wrong less often (1 answer, against 2), and said “no close match” for one more answerable question (3, against 2). With one run each, that one-question shift is within the normal variation of a language model.

The targeted problems are gone. Replies in the wrong language fell from 4 of the same 16 questions to 0, and none of the 79 were wrong in the second run. Answers with an unsupported claim word in a reason fell from 7 to 0. That happened at the source: once the prompt named the banned words, the model stopped writing “perfect”. The code’s replacement step is a safety net, and it caught one remaining “ideal”. So the “shown to the shopper” figure of 0 is guaranteed by the code; the “written by the model” figure is the real improvement. Conversation A, printed above from the first run, can be compared turn by turn with section 5: the topic is now kept, and the wrong reply and the forced pick are gone.

The lesson is that rules stated only in the prompt were followed most of the time but not reliably. The ones that matter to a shopper (language, unsupported claims, product codes, the conversation topic) are now set or checked in code, as budget and stock limits already were.

## 7. The judge
Gemini grades the 79 chat answers and all 195 definitions from Part 1. It uses the same Y / P / N scale I used in my hand-check, so the two can be compared. Verdicts are saved as they arrive; if Gemini's free daily limit runs out, I re-run the cell later and it carries on.

In [7]:
judge = GeminiJudge()
print("Judge model:", judge.model)
chat_items = []
for r in test:
    x = runs[r["qid"]]
    chat_items.append({"id": r["qid"], "request": r["query"], "assistant_reply": x["reply"],
                       "suggested": [{"title": by_id[p]["title"], "price_pkr": by_id[p]["price_pkr"], "in_stock": by_id[p]["in_stock"],
                                      "facts": by_id[p]["attributes"], "reason_given": w} for p, w in zip(x["picks"], x["whys"])]})
chat_grades = run_batches(judge, CHAT_RUBRIC, chat_items, "judge_chat", "results/judge_chat.json", batch_size=8)

defs = json.load(open("data/definitions_v2.json"))["items"]
def_items = [{"id": pid, "title": by_id[pid]["title"], "facts": by_id[pid]["attributes"], "definition": defs[pid]["text"]}
             for pid in sorted(defs)]
def_grades = run_batches(judge, DEF_RUBRIC, def_items, "judge_definitions", "results/judge_definitions.json", batch_size=15)

Judge model: models/gemini-flash-lite-latest
  graded 8/79
  graded 16/79
  graded 24/79
  graded 32/79
  graded 40/79
  graded 48/79
  graded 56/79
  graded 64/79
  graded 72/79
  graded 79/79
  graded 15/195
  graded 30/195
  graded 45/195
  graded 60/195
  graded 75/195
  graded 90/195
  graded 105/195
  graded 120/195
  graded 135/195
  graded 150/195
  graded 165/195
  graded 180/195
  graded 195/195

In [8]:
cg = pd.DataFrame(chat_grades.values())
print(f"Chat answers graded: {len(cg)} of {len(test)}")
for col in ["first_pick", "reasons_supported", "language_match"]:
    if col in cg:
        print(f"  {col}: " + ", ".join(f"{k} {v}" for k, v in cg[col].value_counts().items()))
dg = pd.DataFrame(def_grades.values())
print(f"\nDefinitions graded: {len(dg)} of {len(defs)}")
if len(dg):
    vc = dg["verdict"].value_counts()
    print("  " + ", ".join(f"{k} {v} ({v / len(dg):.0%})" for k, v in vc.items()))
    display(dg[dg["verdict"] != "Y"][["id", "verdict", "note"]].head(15))

# How far does the judge agree with me? Compare with my 20 hand-checked definitions from Part 1.
if os.path.exists("results/definition_handcheck.json"):
    mine = json.load(open("results/definition_handcheck.json"))
    pairs = [(mine[p]["verdict"], def_grades[p]["verdict"]) for p in mine if p in def_grades]
    agree = sum(a == b for a, b in pairs)
    print(f"\nJudge vs my hand-check on the same {len(pairs)} definitions: same verdict on {agree} ({agree / max(len(pairs), 1):.0%})")
    display(pd.crosstab(pd.Series([a for a, _ in pairs], name="my verdict"), pd.Series([b for _, b in pairs], name="judge verdict")))

Chat answers graded: 79 of 79
  first_pick: good 67, none 11, partial 1
  reasons_supported: yes 68, n/a 11
  language_match: yes 79

Definitions graded: 195 of 195
  Y 183 (94%), P 12 (6%)

,id,verdict,note
17,FUR-018,P,Facts do not state that the chair is stackable.
28,FUR-029,P,"Called wall shelf in shoppers say, but facts specify corner unit."
82,KIT-039,P,Snipping garlic cloves is not appropriate for herb scissors.
100,KIT-057,P,Grating soft fruits is not supported by facts.
111,ORG-009,P,"Mentions organizing boots, which rarely fit shoe pockets."
116,ORG-014,P,"Mentions stacking, but facts do not state these bins stack."
126,ORG-024,P,Facts do not mention holding towels.
131,ORG-029,P,"Facts state 5 compartments and a drawer, not just 5."
133,ORG-031,P,Preventing spills in bags is incorrect for pantry containers.
137,ORG-035,P,Mentions zip-lock and freezer bags; facts only state plastic bags.
148,ORG-046,P,"Shoppers say mentions wall mug rack, but facts do not state wall mounting."
191,TOL-041,P,Mentioning gas fittings may be dangerous without specific product certification.

Judge vs my hand-check on the same 20 definitions: same verdict on 11 (55%)

judge verdict  P   Y
my verdict
P              1   9
Y              0  10

**Observations:** The judge’s chat grades match the automatic scores in section 4: 67 good first picks, 11 answers with no product (the 8 correct “no close match” answers and the 3 over-cautious ones), and 1 partial, the single confidently-wrong answer. As in the first run, it never used “wrong”. This time its finding that every reply was in the shopper’s language agrees with the code’s own check (0 of 79 wrong). In the first run it gave the same verdict while 4 of the 16 replies printed in that run were in the wrong language, so its language grade cannot be trusted on its own.

On the Part 1 definitions, which have not changed, the judge gave 183 accurate and 12 partly right this time, against 185 and 10 in the first run. The same judge, grading the same text, gave different verdicts on a few items, so even an AI judge’s scores carry run-to-run noise. Several of its notes are sensible (“gas fittings” for PTFE tape, the fridge bins “stack” claim). Its agreement with my 20 hand-checked definitions is unchanged at 11 of 20 (55%), with the same pattern: it never called a definition I rated accurate wrong, but it called 9 of my 10 “partly right” definitions accurate, missing invented Urdu names and context errors such as wall plugs “for drywall”. The judge is a useful first filter, but it is consistently more lenient than my own checking, and its 94% should be read as an upper bound.

## 8. My check of the judge (16 chat verdicts, 20%)
16 of the judge's chat verdicts, sampled at random with a fixed seed. For each, I read the request, the reply and the suggestions, and record whether I agree with the judge's grade.

In [9]:
CHECK = sorted(random.Random("judge-check").sample(sorted(r["qid"] for r in test), 16))
for q in CHECK:
    x, g = runs[q], chat_grades.get(q, {})
    print(f"{q} | {by_q[q]['query']}")
    print("   reply:", x["reply"])
    print("   suggested:", "; ".join(f'{by_id[p]["title"]} (Rs {by_id[p]["price_pkr"]:,})' for p in x["picks"]) or "(none)")
    print("   reasons:", " | ".join(w for w in x["whys"] if w) or "(none)")
    print(f"   JUDGE: first_pick={g.get('first_pick')}, reasons_supported={g.get('reasons_supported')}, "
          f"language_match={g.get('language_match')}  {g.get('note', '')}\n")

Q022 | bookcase
   reply: We don’t have any in‑stock bookcases right now. Try searching for “shelf unit” or “wall shelves”.
   suggested: (none)
   reasons: (none)
   JUDGE: first_pick=none, reasons_supported=n/a, language_match=yes  No bookcases in stock.

Q032 | flip rotis without burning my fingers
   reply: Try the Steel Chimta, Flat 14 inch—it lets you flip chapatis safely without touching the hot surface.
   suggested: Steel Chimta, Flat 14 inch (Rs 390)
   reasons: designed for flipping chapati and turning fried items, keeping your fingers away from heat
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q039 | stop oil splashing everywhere while frying
   reply: The Splatter Guard Screen stops oil from splashing while frying.
   suggested: Splatter Guard Screen, 33 cm (Rs 990)
   reasons: prevents oil splatter while frying
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q047 | hold two pieces of wood together while the glue dries
   reply: The Quick‑Grip Bar Clamps hold wood pieces securely while the glue sets.
   suggested: Quick-Grip Bar Clamps, Set of 2 (Rs 1,350)
   reasons: designed for holding wood pieces while gluing
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q049 | stop water leaking from a pipe thread
   reply: Use PTFE Thread Seal Tape to stop the leak; it seals pipe threads effectively. A pipe wrench can help tighten the joint if needed.
   suggested: PTFE Thread Seal Tape, Pack of 5 (Rs 250); Pipe Wrench, 14 inch (Rs 1,650)
   reasons: seals pipe threads to prevent leaks | tightens pipe fittings for a secure connection
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q056 | use my laptop comfortably in bed
   reply: A Laptop Bed Table with Foldable Legs lets you work comfortably in bed, and its size fits well for a laptop. The Adjustable Laptop Table with Tilting Top also offers height flexibility and a tilting surface for better viewing. Both are in stock and affordable.
   suggested: Laptop Bed Table with Foldable Legs (Rs 2,950); Adjustable Laptop Table with Tilting Top (Rs 4,950)
   reasons: Foldable legs make it easy to use on a bed | Adjustable height and tilting top improve comfort while in bed
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q066 | the kitchen sink drains really slowly
   reply: Try a Drain Auger to reach deep clogs, or a Rubber Cup Plunger for quick surface blockages.
   suggested: Drain Auger, 5 m Steel Cable (Rs 1,890); Rubber Cup Plunger with Wooden Handle (Rs 590)
   reasons: clears kitchen sink clogs with a 5 m steel cable | removes minor pipe blockages in sink drains
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q067 | guests are staying over and we have no spare bed
   reply: You could use the Sofa Cum Bed, which turns into a guest bed; the Metal Bunk Bed gives two sleeping spots while saving floor space; or the Woven Rope Charpai, which works as a simple guest sleeping area.
   suggested: Sofa Cum Bed, 3-Seater, Fabric (Rs 64,500); Metal Bunk Bed, Single over Single (Rs 46,500); Woven Rope Charpai, Sheesham Frame (Rs 18,500)
   reasons: turns into a guest bed | provides two sleeping spots and saves floor space | can be used as a guest sleeping area
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q069 | plastic shopping bags are piling up in the kitchen
   reply: A wall‑mounted plastic bag holder can keep your zip‑lock and freezer bags organized and free up drawer space.
   suggested: Wall-Mounted Plastic Bag Holder (Rs 590)
   reasons: stores zip‑lock bags and keeps them easily reachable
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q077 | knife sharpener under 1500
   reply: The 3‑Stage Manual Knife Sharpener fits your budget and sharpens kitchen knives.
   suggested: 3-Stage Manual Knife Sharpener (Rs 990)
   reasons: Sharpens kitchen knives with diamond, ceramic, and tungsten stages
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q083 | storage for winter blankets under 2000, in stock
   reply: Here are some options for storing winter blankets within your budget:
   suggested: Jumbo Vacuum Bags, Set of 3 (Rs 1,390); Under-Bed Storage Bag with Zip, Set of 2 (Rs 1,590); Hanging Closet Shelves, 6 Sections (Rs 1,350)
   reasons: Jumbo vacuum bags compress quilts and blankets to save space | Under‑bed storage bags keep extra bedding hidden and organized | Hanging closet shelves provide easy access for folded blankets
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q094 | jootay rakhne ki rack
   reply: Aap ke liye ye shoe rack munasib hain:
   suggested: Stackable Shoe Rack, 4 Tiers (Rs 2,450); Bamboo Shoe Rack, 2 Tiers (Rs 2,950); Over-the-Door Shoe Organizer, 24 Pockets (Rs 1,450)
   reasons: 4 tiers se 12 joote rakh sakte hain aur floor space bachata hai | Bamboo ka natural look aur 2 tiers se 6 joote organize karte hain | 24 pockets ke saath over-the-door lagta hai, floor space bilkul bachata
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q103 | mosquito net for a bed
   reply: Sorry, we don’t have a mosquito net in our current list. Try searching for "mosquito net" or "bed net".
   suggested: (none)
   reasons: (none)
   JUDGE: first_pick=none, reasons_supported=n/a, language_match=yes  No products available for this request.

Q108 | hair curling tongs
   reply: We don’t have hair curling tongs in our catalog. Try searching for “curling iron” or “hair styling tools”.
   suggested: (none)
   reasons: (none)
   JUDGE: first_pick=none, reasons_supported=n/a, language_match=yes  No products were suggested in the catalog.

Q109 | office chair under Rs 10000
   reply: Sorry, none of the listed items match an office chair under Rs 10,000. Try searching with terms like “office chair” or “desk chair”.
   suggested: (none)
   reasons: (none)
   JUDGE: first_pick=none, reasons_supported=n/a, language_match=yes  No products were suggested in the catalog.

Q114 | cover for a bean bag
   reply: The Bean Bag Cover Only, Large will replace your worn cover or let you add a new breathable cover.
   suggested: Bean Bag Cover Only, Large (Rs 3,950)
   reasons: fits a bean bag and is a replaceable cotton canvas cover
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

In [10]:
# My verdict on each judge grade: "agree" or "disagree", with a note where I disagree
MY_CHECK = {
    "Q022": ("agree", "Correct to suggest nothing: the store's only bookcase is out of stock, and the reply says so and suggests other words. The automatic score counts this as 'wrongly says no close match', which is unfair here"),
    "Q032": ("agree", ""),
    "Q039": ("agree", ""),
    "Q047": ("agree", ""),
    "Q049": ("agree", ""),
    "Q056": ("agree", ""),
    "Q066": ("agree", ""),
    "Q067": ("agree", ""),
    "Q069": ("agree", "Right product, but the reason talks about zip-lock and freezer bags, not shopping bags. It comes from an error in this product's AI definition (the judge flagged that definition in section 7), so definition errors carry through into chat answers"),
    "Q077": ("agree", ""),
    "Q083": ("agree", ""),
    "Q094": ("agree", "Roman Urdu question, Roman Urdu reply; all three capacities match the specs"),
    "Q103": ("agree", "Correctly said the store has no mosquito net"),
    "Q108": ("agree", "Correctly said the store has no hair curling tongs"),
    "Q109": ("agree", "Correctly said no office chair within budget"),
    "Q114": ("agree", ""),
}
assert sorted(MY_CHECK) == CHECK, "The IDs must match the sample shown above"
marks = [v for v, _ in MY_CHECK.values()]
if "?" in marks:
    print(f"{marks.count('?')} still marked '?'.")
else:
    print(f"I agree with the judge on {marks.count('agree')} of 16 chat verdicts ({marks.count('agree') / 16:.0%})")
    json.dump({q: {"my_view": v, "note": n} for q, (v, n) in MY_CHECK.items()}, open("results/judge_handcheck.json", "w"), indent=1)

I agree with the judge on 16 of 16 chat verdicts (100%)

**Observations:** I agreed with the judge on all 16 sampled chat verdicts. Two need a note. In Q022 (“bookcase”), the chat suggested nothing because the store’s only bookcase is out of stock, and said so. That is the honest answer, but the automatic score in section 4 counts it as “wrongly says no close match”, so that measure slightly overstates the chat’s over-caution. In Q069, the right product came first, but its reason talks about zip-lock and freezer bags instead of shopping bags. That wording comes from an error in the product’s AI definition, which the judge flagged in section 7, so mistakes in the Part 1 definitions can carry through into chat answers.

Full agreement here does not show that the judge is reliable. It shows that the second run left it little to miss. The first run’s records show what it misses: it marked all 79 replies as in the shopper’s language and every reason as supported, yet 4 of these same 16 questions were answered in Roman Urdu (section 6), and 7 reasons used “perfect”. So the judge confirms good answers but does not catch language or wording problems. Those are now checked in code, not left to the judge.

## 9. Cost and latency
Token use for this whole run, and per chat turn. We run on free tiers, so the actual cost is \$0. The estimate uses published paid prices: Groq `gpt-oss-120b` at \$0.15 / \$0.60 per million input / output tokens, and Gemini embeddings at \$0.15 per million tokens. The judge model's price is not included in the per-turn figure, because it is an evaluation cost, not a running cost.

In [11]:
usage = pd.DataFrame(USAGE.summary()).T
display(usage)
turns = [x for x in runs.values() if not x.get("fallback")]
tin = sum(x["tokens_in"] for x in turns) / len(turns)
tout = sum(x["tokens_out"] for x in turns) / len(turns)
lat = sorted(x["latency_ms"] for x in turns)
p = PRICES["openai/gpt-oss-120b"]
per_turn = tin / 1e6 * p["in"] + tout / 1e6 * p["out"]
embed_per_query = 12 / 1e6 * PRICES["gemini-embedding-001"]["in"]   # about 12 tokens per search
print(f"Average chat turn: {tin:,.0f} input + {tout:,.0f} output tokens; median latency {lat[len(lat) // 2] / 1000:.1f} s "
      f"(slowest {lat[-1] / 1000:.1f} s)")
print(f"Estimated cost at paid prices: ${per_turn * 1000:.2f} per 1,000 chat turns; "
      f"${embed_per_query * 1000:.4f} per 1,000 searches (embedding only); hosting on Vercel Hobby: $0")
json.dump({"avg_tokens_in": tin, "avg_tokens_out": tout, "median_latency_s": lat[len(lat) // 2] / 1000,
           "usd_per_1000_chat_turns": per_turn * 1000, "usd_per_1000_searches": embed_per_query * 1000},
          open("results/part3_cost.json", "w"), indent=1)

,model,calls,items,tokens_in,tokens_out,seconds,est_cost_usd
chat_turn,openai/gpt-oss-120b,85,85,68894,10022,45.9,0.01635
embed_chat_queries,gemini-embedding-001,6,6,76,0,1.4,0.00001
judge_chat,models/gemini-flash-lite-latest,10,79,18469,4493,14.1,0.0
judge_definitions,models/gemini-flash-lite-latest,13,195,31402,6779,20.1,0.0

Average chat turn: 806 input + 115 output tokens; median latency 0.6 s (slowest 58.7 s)
Estimated cost at paid prices: $0.19 per 1,000 chat turns; $0.0018 per 1,000 searches (embedding only); hosting on Vercel Hobby: $0

**Observations:** This run made 85 chat calls (79 test questions and 6 conversation turns), using about 79,000 tokens in total, and 6 Gemini embedding calls for conversation messages not seen before. An average chat turn uses 806 input and 115 output tokens. Most of the input is the candidate list with each product’s facts and uses. At paid prices that is about \$0.19 per 1,000 chat turns, and \$0.0018 per 1,000 searches for the embedding. Hosting on Vercel’s free plan costs \$0, and on free tiers the whole project costs \$0. The judge’s calls (about 61,000 tokens) are an evaluation cost, not a running cost, so they are not in the per-turn figure.

The median chat turn took 0.6 seconds. The slowest (58.7 s) was the notebook pausing to stay within Groq’s free limit of 8,000 tokens per minute, not the model itself. On the live site there is no such pause: if the limit is reached, the chat shows the search results instead. The site also adds one embedding call per new message, so a shopper waits a little longer than the median here. The binding constraint is the free tier, not cost. At about 920 tokens per turn, 8,000 tokens a minute allows roughly 8 chat turns a minute, and Groq’s free daily limit of 1,000 requests caps the chat at about 1,000 turns a day. That is fine for a demo, but a real store would need a paid tier, which at these prices is still very cheap.

## 10. Saving results

In [12]:
summary.to_json("results/part3_chat_vs_search.json", indent=1)
subprocess.run(["git", "add", "results"], check=True)
subprocess.run(["git", "commit", "-q", "-m", "Part 3 run: chat evaluation, judge, judge hand-check, cost"])
subprocess.run(["git", "pull", "-q", "--rebase"])
r = subprocess.run(["git", "push", "-q"], capture_output=True, text=True)
print("Pushed to GitHub" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])

Pushed to GitHub