# Sahulat Home generative search, Part 3: the "Ask Sahulat" chat, judged


Part 2 measured retrieval: does the right product come back? This part measures the **generation** side of the RAG system, the "Ask Sahulat" chat assistant on the live site. For each message, the assistant:
1. reads budget and stock limits by rules;
2. retrieves candidates with the same search as the search bar (meaning search on the AI definitions, chosen in Part 2), page and visit context included;
3. asks `gpt-oss-120b` (on Groq) to pick up to three candidates and explain each, in the shopper's language, or to say honestly that nothing fits;
4. checks the answer in code: products the search did not return are dropped, limits are re-checked, and reasons are scanned for unsupported claims.

**Questions:**
- Does the chat pick the right product more often than the search bar's first result?
- Does it stay grounded and within limits, and say "no close match" when it should?
- What does an independent judge (Gemini, a different company) think of its answers and of the Part 1 definitions, and how far can that judge be trusted, measured against my own checks?
- What does a chat turn cost?

**Method.** All 79 test questions, single turn and without context, so the numbers are comparable with Part 2. Then scripted multi-turn conversations with page context. Then the judge, and my hand-check of 16 judge verdicts (20%).

**AI use.** Code written with Claude (Anthropic) as a coding assistant. Design decisions, runs, hand-checks and observations are mine.

## 1. Setup
Loads the keys, pulls the project (including the outputs of Parts 1 and 2) and the settings tuned on dev, which are the same ones the live site uses.

In [1]:
!pip install -q groq google-genai

import os, sys, json, random, subprocess, time
import pandas as pd
from google.colab import userdata

os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")
os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")
token = userdata.get("GITHUB_TOKEN")
REPO = "/content/data722-generative-search"
url = f"https://x-access-token:{token}@github.com/mahamnalavi/data722-generative-search.git"
if not os.path.exists(REPO):
    r = subprocess.run(["git", "clone", "-q", url, REPO], capture_output=True, text=True)
else:
    r = subprocess.run(["git", "-C", REPO, "pull", "-q"], capture_output=True, text=True)
print("GitHub:", "OK" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])
subprocess.run(["git", "-C", REPO, "config", "user.name", "Maham (Colab run)"])
subprocess.run(["git", "-C", REPO, "config", "user.email", "mahamnalavi@users.noreply.github.com"])
sys.path.insert(0, REPO); os.chdir(REPO)

for f in ["data/definitions_v2.json", "data/emb_definitions_v2.json", "results/query_vectors.json", "results/tuned_params.json"]:
    assert os.path.exists(f), f"{f} is missing: run Notebooks 01 and 02 first"
from search import chat, pipeline, products_by_id, load_catalogue
from search import evaluate as ev
from search.llm import GroqChat, GeminiEmbedder, USAGE, PRICES
from search.judge import GeminiJudge, run_batches, CHAT_RUBRIC, DEF_RUBRIC
pd.options.display.max_colwidth = 90

rows = json.load(open("data/eval_queries.json", encoding="utf-8"))
test = [r for r in rows if r["split"] == "test"]
by_q = {r["qid"]: r for r in rows}
by_id = products_by_id()
catalogue = load_catalogue()
live = json.load(open("results/tuned_params.json"))["live"]
qvecs = json.load(open("results/query_vectors.json"))
vec_by_text = {ev.query_text_for_embedding(r["query"]): qvecs[r["qid"]] for r in rows}
emb = GeminiEmbedder()
def embed_fn(texts):
    """Re-use the Part 2 query embeddings; embed only texts not seen before (multi-turn demos)."""
    missing = [t for t in texts if t not in vec_by_text]
    if missing:
        vec_by_text.update(zip(missing, emb.embed(missing, kind="query", task="embed_chat_queries")))
    return [vec_by_text[t] for t in texts]
llm = GroqChat()
print(f"Ready: {len(test)} test questions; live settings loaded")

GitHub: OK
Ready: 79 test questions; live settings loaded

## 2. The context design
This is what the chat model sees for every message. The system prompt sets the rules: candidates only, at most three, reasons from the facts, honest "no close match", the shopper's language, and context as a soft hint. The message then gives the conversation, the limits, a short summary of the page and visit, and the candidate products with their facts and AI-written uses from Part 1.

Below are the rules, and the complete message for one test question.

In [2]:
print(chat.SYSTEM_PROMPT)
ex = next(r for r in test if r["style"] == "constraint")
msgs = [{"role": "user", "content": ex["query"]}]
cons = chat.merged_constraints([ex["query"]])
cands = []
for t, v in zip(chat.retrieval_texts([ex["query"]]), embed_fn([ev.query_text_for_embedding(ex["query"])])):
    cands += [p["product_id"] for p in pipeline.run(t, mode=pipeline.LIVE_MODE, query_vec=v, k=6, params=live, constraints=cons)["results"]]
print("\n----- message for:", ex["query"], "-----\n")
print(chat.build_user_prompt(msgs, cons, {"page_category": "Kitchenware", "categories_browsed": {"Kitchenware": 2},
                                          "product_types_viewed": ["tawa"], "price_band": {"min": 1850, "max": 3290, "median": 2350}}, cands))

You are "Ask Sahulat", the shopping assistant of Sahulat Home, an online household-goods store in Pakistan.

Rules:
1. Recommend ONLY products listed under CANDIDATES, by their id. Never invent products, prices, stock or features.
2. Pick at most 3, best first. For each, give one short reason that follows from its listed facts or uses.
3. Candidates already meet the stated budget and stock limits. If the shopper asks for cheaper, prefer lower prices.
4. If no candidate does what the shopper needs, set "no_match" to true, say so plainly, and suggest different words to search. Never force a product.
5. Reply in the language of the shopper's last message: English, Urdu script, or Roman Urdu.
6. PAGE and VISIT are soft hints for unclear requests only. The shopper's own words always win.
7. Keep "reply" under 60 words. No marketing words.

Return JSON only: {"reply": "...", "picks": [{"id": "...", "why": "..."}], "no_match": false}

----- message for: pressure cooker under 5000 -----

CONVERSATION (latest last):
Shopper: pressure cooker under 5000

LIMITS: max price Rs 5,000
PAGE: opened from the Kitchenware page | VISIT: browsed Kitchenware (2 pages); viewed tawa; prices viewed Rs 1,850 to Rs 3,290

CANDIDATES:
- KIT-022 | Mini Pressure Cooker, 3 Litre | Rs 4,350 | in stock | uses: quickly cooking small portions of dal; making single‑serve soups; softening vegetables; preparing small batches of rice | specs: capacity: 3 L; material: Hard aluminium; safety: Gasket release window
- KIT-053 | Glass Boil-Over Preventer Disc | Rs 450 | in stock | uses: prevent boil‑over while cooking rice; keep stovetop clean; reduce mess from sauces | specs: material: Heat-resistant glass; diameter: 7 cm
- KIT-043 | Insulated Hot Pot Casserole, 2.5 Litre | Rs 1,890 | in stock | uses: keeping soups hot for serving; transporting stews to a gathering; serving hot dishes at a buffet | specs: capacity: 2.5 L; material: Stainless steel inner, PU insulation; lid: Locking
- KIT-005 | Heavy-Duty Zinc Alloy Garlic Press | Rs 1,150 | in stock | uses: pressing garlic cloves into paste; quickly mincing garlic for curries; adding fresh garlic flavor without chopping | specs: material: Zinc alloy; finish: Chrome; length: 18 cm
- KIT-006 | Rocker Garlic Crusher, Stainless Steel | Rs 890 | in stock | uses: crushing garlic cloves into fine pieces; making garlic paste without a board; quickly preparing garlic for sauces | specs: material: Stainless steel; shape: Curved rocker; length: 13 cm
- KIT-019 | Non-Stick Karahi with Glass Lid, 26 cm | Rs 4,250 | in stock | uses: frying vegetables; making curries; stir‑frying meat; cooking eggs | specs: material: Aluminium, non-stick; diameter: 26 cm; lid: Tempered glass

**Observations:** This is the context design at the centre of the chat. The model never searches the catalogue itself: it receives one message built by code, with four parts.

1. The conversation (the last 6 messages).
2. The limits, read by rules, not by the model (“max price Rs 5,000”).
3. The page and visit summary, marked as a soft hint (rule 6). The visit in this example is made up for illustration; section 3 sends no context.
4. The candidates: up to 6 products from the same search the site uses, each with its id, price, stock, specs and the uses from my Part 1 definitions.

The example shows why this order matters. The budget filter runs before the model sees anything, so the Rs 5,950 and Rs 11,900 pressure cookers are not candidates at all. Only the Rs 4,350 mini cooker is, and the model cannot break the budget without inventing a product, which the code would drop (rule 1 and the grounding check). The other five candidates are weaker matches (a boil-over disc, a hot pot, garlic presses, a karahi), because search always fills the list. That tests rule 4: the model should pick only the mini cooker and not force the rest. Giving each product’s uses, not just its specs, lets the model explain a pick in the shopper’s terms (“for small portions of dal”) while staying within the facts. Asking for JSON with product ids, not free text, is what lets the code check every pick.

## 3. The chat on all 79 test questions
Each question is sent as a single message, with no context, using the same code as the live site. Answers are saved as they arrive, so if Colab disconnects, re-running the cell continues where it stopped. The calls are paced to Groq's free limit of 8,000 tokens per minute, so expect 20-25 minutes.

In [3]:
RUNS_FILE = "results/chat_test_runs.json"
runs = json.load(open(RUNS_FILE)) if os.path.exists(RUNS_FILE) else {}
t0 = time.time()
for i, r in enumerate(test, start=1):
    if r["qid"] in runs:
        continue
    res = chat.respond([{"role": "user", "content": r["query"]}], context=None, embed_fn=embed_fn, llm=llm, params=live)
    runs[r["qid"]] = {"reply": res["reply"], "picks": [p["product_id"] for p in res["products"]],
                      "whys": [p["why"] for p in res["products"]], "no_match": res["no_match"],
                      "search_no_close_match": res["search_no_close_match"], **res["diagnostics"]}
    if i % 5 == 0 or i == len(test):
        json.dump(runs, open(RUNS_FILE, "w"), indent=1, ensure_ascii=False)
        print(f"  {len(runs)}/{len(test)} answered ({(time.time() - t0) / 60:.1f} min)")
json.dump(runs, open(RUNS_FILE, "w"), indent=1, ensure_ascii=False)
fallbacks = [q for q, x in runs.items() if x.get("fallback")]
print(f"Done: {len(runs)} answers; chat model unavailable (search results shown instead) for {len(fallbacks)}")

  5/79 answered (0.1 min)
  10/79 answered (1.0 min)
  15/79 answered (2.0 min)
  20/79 answered (2.1 min)
  25/79 answered (3.1 min)
  30/79 answered (4.1 min)
  35/79 answered (4.2 min)
  40/79 answered (5.2 min)
  45/79 answered (6.2 min)
  50/79 answered (7.1 min)
  55/79 answered (7.2 min)
  60/79 answered (8.2 min)
  65/79 answered (9.2 min)
  70/79 answered (9.3 min)
  75/79 answered (10.2 min)
  79/79 answered (11.2 min)
Done: 79 answers; chat model unavailable (search results shown instead) for 0

**Note:** All 79 test questions were answered by the chat model in 11.2 minutes, with no fallbacks. The time is mostly the pacing that keeps the run within Groq’s free limit, not the model itself.

## 4. Automatic scores
The chat's first suggestion compared with the search bar's first result on the same questions, plus the checks done in code: grounding, limits, unsupported claim words and no-match handling.

In [4]:
search_runs = {x["qid"]: x for x in ev.run_queries(test, pipeline.LIVE_MODE, qvecs, params=live)}
def rel(q): return set(by_q[q]["relevant_ids"])
ans = [r["qid"] for r in test if not r["expects_no_match"]]
nom = [r["qid"] for r in test if r["expects_no_match"]]
rate = lambda xs: round(sum(xs) / len(xs), 3) if xs else None

chat_first = {q: bool(runs[q]["picks"]) and runs[q]["picks"][0] in rel(q) for q in ans}
chat_any = {q: any(p in rel(q) for p in runs[q]["picks"]) for q in ans}
search_first = {q: bool(search_runs[q]["ids"]) and search_runs[q]["ids"][0] in rel(q) for q in ans}
search_top3 = {q: any(i in rel(q) for i in search_runs[q]["ids"][:3]) for q in ans}
viol = sum(1 for q in runs for pid in runs[q]["picks"]
           if (by_q[q]["expected_max_price"] is not None and by_id[pid]["price_pkr"] > by_q[q]["expected_max_price"])
           or (by_q[q]["expected_in_stock"] and not by_id[pid]["in_stock"]))
chat_cw = [(not runs[q]["no_match"]) and (q in nom or not runs[q]["picks"] or runs[q]["picks"][0] not in rel(q)) for q in runs]
search_cw = [(not search_runs[q]["no_close_match"]) and (q in nom or not search_runs[q]["ids"] or search_runs[q]["ids"][0] not in rel(q)) for q in runs]

summary = pd.DataFrame({
    "search bar": {"first result correct": rate(list(search_first.values())),
                            "a correct product among the first 3": rate(list(search_top3.values())),
                            "correct 'no close match'": rate([search_runs[q]["no_close_match"] for q in nom]),
                            "wrongly says 'no close match'": rate([search_runs[q]["no_close_match"] for q in ans]),
                            "confidently wrong": rate(search_cw)},
    "Ask Sahulat chat": {"first result correct": rate(list(chat_first.values())),
                         "a correct product among the first 3": rate(list(chat_any.values())),
                         "correct 'no close match'": rate([runs[q]["no_match"] for q in nom]),
                         "wrongly says 'no close match'": rate([runs[q]["no_match"] for q in ans]),
                         "confidently wrong": rate(chat_cw)}})
display(summary)
dropped = sum(len(x["dropped_ids"]) for x in runs.values())
flagged = {q: x["claim_flags"] for q, x in runs.items() if x["claim_flags"]}
n_picks = sum(len(x["picks"]) for x in runs.values())
print(f"Grounding: {dropped} suggested product ids were not among the search candidates and were dropped by code")
print(f"Limits: {viol} of {n_picks} shown picks break the question's budget or stock limit")
print(f"Unsupported claim words in reasons: {len(flagged)} answers flagged {flagged if flagged else ''}")

style_rows = {}
for r in test:
    if r["expects_no_match"]:
        continue
    s = style_rows.setdefault(r["style"], {"search first": [], "chat first": []})
    s["search first"].append(search_first[r["qid"]]); s["chat first"].append(chat_first[r["qid"]])
display(pd.DataFrame({k: {c: rate(v) for c, v in d.items()} for k, d in style_rows.items()}).T)

                                     search bar  Ask Sahulat chat
first result correct                      1.000             0.957
a correct product among the first 3       1.000             0.957
correct 'no close match'                  0.333             0.889
wrongly says 'no close match'             0.014             0.029
confidently wrong                         0.076             0.025

Grounding: 0 suggested product ids were not among the search candidates and were dropped by code
Limits: 0 of 121 shown picks break the question's budget or stock limit
Unsupported claim words in reasons: 7 answers flagged {'Q020': {'ORG-023': ['perfect']}, 'Q040': {'KIT-054': ['perfect']}, 'Q056': {'FUR-020': ['perfect']}, 'Q075': {'KIT-017': ['perfect']}, 'Q080': {'KIT-036': ['perfect']}, 'Q084': {'KIT-028': ['perfect']}, 'Q112': {'ORG-043': ['perfect']}}

            search first  chat first
name                 1.0       0.941
precise              1.0       1.000
vague                1.0       0.909
constraint           1.0       1.000
urdu                 1.0       0.889
trap                 1.0       1.000

**Observations:** The chat’s main gain is honesty about what the store doesn’t sell. On the 9 out-of-catalogue questions, it said “no close match” for 8, against 3 for the search bar alone. Its confidently-wrong rate is a third of the search bar’s (2.5% vs 7.6%). This is the check I said section 7 of Part 2 lacked: the model reads each candidate’s uses and decides whether it does the job, instead of relying on a similarity score. The cost is caution: it put a correct product first for 67 of 70 answerable questions (0.96, against 1.00 for the search bar). Two of those three misses were answerable questions it wrongly called “no close match”. By style, the misses were one name search, one vague and one Roman Urdu question.

The code checks found no grounding failures (0 products outside the search candidates) and no limit violations (0 of 121 picks). But 7 answers used “perfect” in a reason, despite the rule against marketing words. The automatic check flagged all 7, but it only flags; the word would still reach the shopper. Under the CCP’s deceptive-marketing guidelines, that is a claim the store cannot back up. This is a failure of relying on the prompt alone, and it needs a fix in code, not just in the instructions.

## 5. Multi-turn conversations and context
Three scripted conversations, run exactly as the live site runs them:
- **A.** A follow-up that tightens the budget, then adds stock, opened from the Kitchenware page.
- **B.** Roman Urdu, with a "cheaper" follow-up.
- **C.** Opened from the Furniture page while the shopper describes a plumbing problem. Their own words should win over the page.

In [5]:
def converse(turns, context):
    msgs = []
    for text in turns:
        msgs.append({"role": "user", "content": text})
        res = chat.respond(msgs, context=context, embed_fn=embed_fn, llm=llm, params=live)
        msgs.append({"role": "assistant", "content": res["reply"]})
        shown = "; ".join(f'{p["title"]} (Rs {p["price_pkr"]:,}, {"in stock" if p["in_stock"] else "out of stock"})' for p in res["products"]) or "(none)"
        print(f"SHOPPER: {text}\nASSISTANT: {res['reply']}\n   shown: {shown}\n   limits: {res['constraints']}\n")

kitchen = {"page_category": "Kitchenware", "categories_browsed": {"Kitchenware": 3}, "product_types_viewed": ["karahi", "tawa"],
           "price_band": {"min": 1850, "max": 4250, "median": 2350}}
furniture = {"page_category": "Furniture", "categories_browsed": {"Furniture": 4}, "product_types_viewed": ["sofa_cum_bed"],
             "price_band": {"min": 20000, "max": 64500, "median": 46500}}
print("=== A ==="); converse(["I need something for making rotis at home", "something cheaper, under 2000", "only ones in stock please"], kitchen)
print("=== B ==="); converse(["bijli chali jaye to roshni ke liye kuch chahiye", "is se sasta wala?"], None)
print("=== C ==="); converse(["my kitchen sink is blocked, water won't drain"], furniture)

=== A ===
SHOPPER: I need something for making rotis at home
ASSISTANT: Here are suitable items:
   shown: Granite-Coated Flat Tawa, 12 inch, Induction Base (Rs 3,290, in stock); Wooden Chakla Belan Set, 10 inch (Rs 1,290, in stock)
   limits: {'max_price': None, 'in_stock': False}

SHOPPER: something cheaper, under 2000
ASSISTANT: Here are some affordable options for making rotis:
   shown: Wooden Chakla Belan Set, 10 inch (Rs 1,290, in stock); Steel Chimta, Flat 14 inch (Rs 390, in stock); Wooden Hand Churner (Madhani), 45 cm (Rs 650, in stock)
   limits: {'max_price': 2000, 'in_stock': False}

SHOPPER: only ones in stock please
ASSISTANT: Maaf, in items mein roti banane ke liye koi cheez nahi hai. Aap "tawa", "roti maker" ya "chapati press" jaise lafz try karen.
   shown: (none)
   limits: {'max_price': 2000, 'in_stock': True}

=== B ===
SHOPPER: bijli chali jaye to roshni ke liye kuch chahiye
ASSISTANT: بجلی بند ہونے پر فوری روشنی کے لیے دو آپشن ہیں۔
   shown: Rechargeable LED Emergency Light, 60 LEDs (Rs 2,450, in stock); Rechargeable LED Bulb, 12 W, B22 (Rs 990, in stock)
   limits: {'max_price': None, 'in_stock': False}

SHOPPER: is se sasta wala?
ASSISTANT: Sab se sasta TOL-027 hai, sirf Rs 990 aur 4 ghante tak chal sakta hai. Dusra option TOL-026 hai, Rs 2,450 aur 8 ghante tak runtime deta hai.
   shown: Rechargeable LED Bulb, 12 W, B22 (Rs 990, in stock); Rechargeable LED Emergency Light, 60 LEDs (Rs 2,450, in stock)
   limits: {'max_price': None, 'in_stock': False}

=== C ===
SHOPPER: my kitchen sink is blocked, water won't drain
ASSISTANT: You can try a drain auger or a plunger to clear the blockage.
   shown: Drain Auger, 5 m Steel Cable (Rs 1,890, in stock); Flange Plunger, Heavy-Duty (Rs 990, in stock); Rubber Cup Plunger with Wooden Handle (Rs 590, in stock)
   limits: {'max_price': None, 'in_stock': False}

**Observations:** The chat carried budget and stock limits correctly across turns (under Rs 2,000 and in stock were both remembered), and its reasons stayed within the product facts: the 4- and 8-hour runtimes it quoted are in the specs. In conversation C, opened from the Furniture page, “my kitchen sink is blocked” still got a drain auger and plungers, so the page context did not override what the shopper typed. Conversation A exposed a real multi-turn failure. On “only ones in stock please”, the assistant said nothing fits, though the chakla belan (Rs 1,290) and chimta (Rs 390) it had just shown are both in stock and under budget. For a follow-up, the chat searches only the latest message and the one before it, so “rotis”, two messages back, was lost, and filler words (“only”, “ones”, “please”) were treated as product words. The same conversation also shows a forced pick (a madhani “for making rotis”) and a reply in Roman Urdu to an English message. Conversation B replied to Roman Urdu in Urdu script and showed an internal product code (“TOL-027”) to the shopper. The language rule and the “never force a product” rule are followed most of the time, but not reliably.

## 6. The judge
Gemini grades the 79 chat answers and all 195 definitions from Part 1. It uses the same Y / P / N scale I used in my hand-check, so the two can be compared. Verdicts are saved as they arrive; if Gemini's free daily limit runs out, re-run the cell later and it carries on.

In [6]:
judge = GeminiJudge()
print("Judge model:", judge.model)
chat_items = []
for r in test:
    x = runs[r["qid"]]
    chat_items.append({"id": r["qid"], "request": r["query"], "assistant_reply": x["reply"],
                       "suggested": [{"title": by_id[p]["title"], "price_pkr": by_id[p]["price_pkr"], "in_stock": by_id[p]["in_stock"],
                                      "facts": by_id[p]["attributes"], "reason_given": w} for p, w in zip(x["picks"], x["whys"])]})
chat_grades = run_batches(judge, CHAT_RUBRIC, chat_items, "judge_chat", "results/judge_chat.json", batch_size=8)

defs = json.load(open("data/definitions_v2.json"))["items"]
def_items = [{"id": pid, "title": by_id[pid]["title"], "facts": by_id[pid]["attributes"], "definition": defs[pid]["text"]}
             for pid in sorted(defs)]
def_grades = run_batches(judge, DEF_RUBRIC, def_items, "judge_definitions", "results/judge_definitions.json", batch_size=15)

Judge model: models/gemini-flash-lite-latest
  graded 8/79
  graded 16/79
  graded 24/79
  graded 32/79
  graded 40/79
  graded 48/79
  graded 56/79
  graded 64/79
  graded 72/79
  graded 79/79
  graded 15/195
  graded 30/195
  graded 45/195
  graded 60/195
  graded 75/195
  graded 90/195
  graded 105/195
  graded 120/195
  graded 135/195
  graded 150/195
  graded 165/195
  graded 180/195
  graded 195/195

In [7]:
cg = pd.DataFrame(chat_grades.values())
print(f"Chat answers graded: {len(cg)} of {len(test)}")
for col in ["first_pick", "reasons_supported", "language_match"]:
    if col in cg:
        print(f"  {col}: " + ", ".join(f"{k} {v}" for k, v in cg[col].value_counts().items()))
dg = pd.DataFrame(def_grades.values())
print(f"\nDefinitions graded: {len(dg)} of {len(defs)}")
if len(dg):
    vc = dg["verdict"].value_counts()
    print("  " + ", ".join(f"{k} {v} ({v / len(dg):.0%})" for k, v in vc.items()))
    display(dg[dg["verdict"] != "Y"][["id", "verdict", "note"]].head(15))

# How far does the judge agree with me? Compare with my 20 hand-checked definitions from Part 1.
if os.path.exists("results/definition_handcheck.json"):
    mine = json.load(open("results/definition_handcheck.json"))
    pairs = [(mine[p]["verdict"], def_grades[p]["verdict"]) for p in mine if p in def_grades]
    agree = sum(a == b for a, b in pairs)
    print(f"\nJudge vs my hand-check on the same {len(pairs)} definitions: same verdict on {agree} ({agree / max(len(pairs), 1):.0%})")
    display(pd.crosstab(pd.Series([a for a, _ in pairs], name="my verdict"), pd.Series([b for _, b in pairs], name="judge verdict")))

Chat answers graded: 79 of 79
  first_pick: good 67, none 10, partial 2
  reasons_supported: yes 69, n/a 10
  language_match: yes 79

Definitions graded: 195 of 195
  Y 185 (95%), P 10 (5%)

,id,verdict,note
17,FUR-018,P,Facts do not state that the chair is stackable.
28,FUR-029,P,"Facts describe a corner shelf unit, not a wall shelf."
82,KIT-039,P,Snipping garlic cloves is incorrect for herb scissors.
111,ORG-009,P,Fact does not support storing boots.
116,ORG-014,P,Facts do not mention stackability.
126,ORG-024,P,Facts do not support storing towels.
131,ORG-029,P,"Facts mention 5 compartments plus a drawer, definition misses drawer count."
133,ORG-031,P,Preventing spills in bags is incorrect for pantry containers.
137,ORG-035,P,"Mentioned storing zip-lock and freezer bags, but facts specify grocery plastic bags."
191,TOL-041,P,Mentioning gas fittings is unsupported; PTFE tape is for water.

Judge vs my hand-check on the same 20 definitions: same verdict on 11 (55%)

judge verdict  P   Y
my verdict
P              1   9
Y              0  10

**Observations:** The judge graded all 79 chat answers and all 195 definitions.

On the chat, its first-pick grades line up with the automatic scores in section 4: 67 good and 10 with no product suggested. It graded the remaining 2 “partial” and never “wrong”, although my labels count both as wrong picks. It marked every reason as supported, including the 7 that used “perfect”, which the code’s claim check flagged. It also marked every reply as matching the shopper’s language, which my check in section 7 below shows is wrong.

On the definitions, it rated 185 accurate (95%) and 10 partly right, with none wrong. Several of its 10 notes are sensible, such as the fridge bins “stack” claim, which I also marked, and “snipping garlic” for herb scissors. Compared with my 20 hand-checked definitions from Part 1, it agreed on only 11 (55%). Every disagreement went the same way: of my 10 “partly right” verdicts, it called 9 accurate. Most of those were about wrong or invented Urdu names, which the judge did not catch, although the names were in the text it graded. It also missed three of my four use errors (“shredding carrots” for a fine rasp, wall plugs “for drywall”, a charpai “for the living room”).

So the judge is useful as a first filter and never contradicted me when I called something accurate. But it is clearly more lenient than a careful human: it misses local-language errors, marketing words and context-specific mistakes. Its 95% should be read as an upper bound, not the true accuracy, and that is why its chat verdicts are spot-checked by me in section 7 below.

## 7. My check of the judge (16 chat verdicts, 20%)
16 of the judge's chat verdicts, sampled at random with a fixed seed. For each, I read the request, the reply and the suggestions, and record whether I agree with the judge's grade.

In [9]:
CHECK = sorted(random.Random("judge-check").sample(sorted(r["qid"] for r in test), 16))
for q in CHECK:
    x, g = runs[q], chat_grades.get(q, {})
    print(f"{q} | {by_q[q]['query']}")
    print("   reply:", x["reply"])
    print("   suggested:", "; ".join(f'{by_id[p]["title"]} (Rs {by_id[p]["price_pkr"]:,})' for p in x["picks"]) or "(none)")
    print("   reasons:", " | ".join(w for w in x["whys"] if w) or "(none)")
    print(f"   JUDGE: first_pick={g.get('first_pick')}, reasons_supported={g.get('reasons_supported')}, "
          f"language_match={g.get('language_match')}  {g.get('note', '')}\n")

Q022 | bookcase
   reply: Here are suitable options:
   suggested: Corner Shelf Unit, 5 Tiers (Rs 6,950); Floating Wall Shelves, Set of 3 (Rs 2,950)
   reasons: Fits a corner and provides 5 shelves for books and decor | Wall‑mounted shelves for displaying books and small items
   JUDGE: first_pick=partial, reasons_supported=yes, language_match=yes  Suggested a corner shelf and floating shelves instead of a standard bookcase.

Q032 | flip rotis without burning my fingers
   reply: Aap ke liye Steel Chimta sab se behtar hai, kyun ke ye chapati ko asani se ulta karne ke liye design ki gayi hai aur haath ko jalne se bachati hai.
   suggested: Steel Chimta, Flat 14 inch (Rs 390)
   reasons: Chapati flip karne ke liye flat stainless steel chimta
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q039 | stop oil splashing everywhere while frying
   reply: Aap ke liye sab se behtar hai Splatter Guard Screen, jo tel ke chhidakne se rokta hai.
   suggested: Splatter Guard Screen, 33 cm (Rs 990); Oil Mister Spray Bottle, 200 ml (Rs 1,150); Glass Oil Dispenser Bottle, 500 ml with Drip-Free Spout (Rs 790)
   reasons: oil splatter ko rokta hai aur stovetop saaf rakhta hai | fine mist se kam tel istemal hota hai, splatter kam hota hai | drip‑free spout se tel girne ka khatra kam hota hai
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q047 | hold two pieces of wood together while the glue dries
   reply: Quick‑Grip Bar Clamps will hold the wood securely while the glue sets.
   suggested: Quick-Grip Bar Clamps, Set of 2 (Rs 1,350)
   reasons: designed for holding wood pieces while gluing
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q049 | stop water leaking from a pipe thread
   reply: Use PTFE Thread Seal Tape to seal the thread and a pipe wrench to tighten the fitting.
   suggested: PTFE Thread Seal Tape, Pack of 5 (Rs 250); Pipe Wrench, 14 inch (Rs 1,650)
   reasons: seals pipe threads to prevent leaks | tightens pipe fittings
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q056 | use my laptop comfortably in bed
   reply: Here are some options for using your laptop comfortably in bed:
   suggested: Laptop Bed Table with Foldable Legs (Rs 2,950); Adjustable Laptop Table with Tilting Top (Rs 4,950); Under-Desk Footrest, Adjustable Angle (Rs 2,450)
   reasons: Foldable legs and flat MDF top make it ideal for a stable bedside laptop surface | Adjustable height and tilting top let you set the perfect viewing angle while lying down | Provides foot support to reduce fatigue when working from bed
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q066 | the kitchen sink drains really slowly
   reply: Your sink can be cleared with a drain auger or a plunger. Here are the best options:
   suggested: Drain Auger, 5 m Steel Cable (Rs 1,890); Rubber Cup Plunger with Wooden Handle (Rs 590); Flange Plunger, Heavy-Duty (Rs 990)
   reasons: 5 m steel cable easily reaches and removes kitchen sink blockages | Rubber cup plunger clears minor sink clogs quickly | Heavy‑duty flange plunger works on stubborn drain blockages
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q067 | guests are staying over and we have no spare bed
   reply: Here are some options for a spare bed:
   suggested: Sofa Cum Bed, 3-Seater, Fabric (Rs 64,500); Woven Rope Charpai, Sheesham Frame (Rs 18,500); Metal Bunk Bed, Single over Single (Rs 46,500)
   reasons: Sofa that converts to a 180 x 120 cm guest bed | Charpai provides a simple sleeping area at a low price | Metal bunk gives two beds if you need extra space
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q069 | plastic shopping bags are piling up in the kitchen
   reply: Aap ke liye sab se behtar hai Wall‑Mounted Plastic Bag Holder, phir Plastic Drawer Organizer Trays aur Expandable Under‑Sink Shelf.
   suggested: Wall-Mounted Plastic Bag Holder (Rs 590); Plastic Drawer Organizer Trays, 8 Pieces (Rs 1,490); Expandable Under-Sink Shelf (Rs 2,650)
   reasons: Bag holder se zip‑lock aur freezer bags ko asani se organize aur drawer space bacha sakte hain | Drawer trays se choti shopping bags ko alag alag sections mein rakh sakte hain | Under‑sink shelf extra storage deta hai, jahan bags ko neatly rakh sakte hain
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q077 | knife sharpener under 1500
   reply: Here is a suitable option:
   suggested: 3-Stage Manual Knife Sharpener (Rs 990)
   reasons: Three sharpening stages (diamond, ceramic, tungsten) for quick blade restoration
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q083 | storage for winter blankets under 2000, in stock
   reply: Here are three options under Rs 2,000:
   suggested: Jumbo Vacuum Bags, Set of 3 (Rs 1,390); Under-Bed Storage Bag with Zip, Set of 2 (Rs 1,590); Hanging Closet Shelves, 6 Sections (Rs 1,350)
   reasons: Vacuum bags compress quilts and coats to save space | Under‑bed bags keep extra blankets hidden and organized | Shelves let you fold and stack blankets neatly
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q094 | jootay rakhne ki rack
   reply: Aap ke liye ye teen options behtar hain:
   suggested: Over-the-Door Shoe Organizer, 24 Pockets (Rs 1,450); Stackable Shoe Rack, 4 Tiers (Rs 2,450); Bamboo Shoe Rack, 2 Tiers (Rs 2,950)
   reasons: 24 clear pockets se jootay asani se dikhte aur floor space bachaata hai | 4 tiers ka steel rack 12 joote tak rakh sakta hai aur vertical stacking se jagah bachat hai | Bamboo ka 2-tier rack natural look deta hai aur 6 joote tak sambhal sakta hai
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q103 | mosquito net for a bed
   reply: Sorry, we don’t have a mosquito net in the current list. Try searching for "mosquito net" or "bed net".
   suggested: (none)
   reasons: (none)
   JUDGE: first_pick=none, reasons_supported=n/a, language_match=yes  No products suggested.

Q108 | hair curling tongs
   reply: Sorry, none of the listed items are hair curling tongs. Try searching for "curling iron" or "hair tongs".
   suggested: (none)
   reasons: (none)
   JUDGE: first_pick=none, reasons_supported=n/a, language_match=yes  No hair curling tongs available in the inventory.

Q109 | office chair under Rs 10000
   reply: Sorry, none of the listed items are office chairs within your budget. Try searching with terms like “office chair” or “desk chair”.
   suggested: (none)
   reasons: (none)
   JUDGE: first_pick=none, reasons_supported=n/a, language_match=yes  No office chairs available within the specified budget.

Q114 | cover for a bean bag
   reply: Aap ke liye Bean Bag Cover Only, Large best hai.
   suggested: Bean Bag Cover Only, Large (Rs 3,950)
   reasons: Large cotton canvas cover for replacing or customizing a bean bag
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

In [ ]:
# My verdict on each judge grade: "agree" or "disagree", with a note where I disagree
MY_CHECK = {
    "Q022": ("?", ""), "Q032": ("?", ""), "Q039": ("?", ""), "Q047": ("?", ""),
    "Q049": ("?", ""), "Q056": ("?", ""), "Q066": ("?", ""), "Q067": ("?", ""),
    "Q069": ("?", ""), "Q077": ("?", ""), "Q083": ("?", ""), "Q094": ("?", ""),
    "Q103": ("?", ""), "Q108": ("?", ""), "Q109": ("?", ""), "Q114": ("?", ""),
}
assert sorted(MY_CHECK) == CHECK, "The IDs must match the sample shown above"
marks = [v for v, _ in MY_CHECK.values()]
if "?" in marks:
    print(f"{marks.count('?')} still marked '?'.")
else:
    print(f"I agree with the judge on {marks.count('agree')} of 16 chat verdicts ({marks.count('agree') / 16:.0%})")
    json.dump({q: {"my_view": v, "note": n} for q, (v, n) in MY_CHECK.items()}, open("results/judge_handcheck.json", "w"), indent=1)

**Observations**

## 8. Cost and latency
Token use for this whole run, and per chat turn. We run on free tiers, so the actual cost is \$0. The estimate uses published paid prices: Groq `gpt-oss-120b` at \$0.15 / \$0.60 per million input / output tokens, and Gemini embeddings at \$0.15 per million tokens. The judge model's price is not included in the per-turn figure, because it is an evaluation cost, not a running cost.

In [ ]:
usage = pd.DataFrame(USAGE.summary()).T
display(usage)
turns = [x for x in runs.values() if not x.get("fallback")]
tin = sum(x["tokens_in"] for x in turns) / len(turns)
tout = sum(x["tokens_out"] for x in turns) / len(turns)
lat = sorted(x["latency_ms"] for x in turns)
p = PRICES["openai/gpt-oss-120b"]
per_turn = tin / 1e6 * p["in"] + tout / 1e6 * p["out"]
embed_per_query = 12 / 1e6 * PRICES["gemini-embedding-001"]["in"]   # about 12 tokens per search
print(f"Average chat turn: {tin:,.0f} input + {tout:,.0f} output tokens; median latency {lat[len(lat) // 2] / 1000:.1f} s "
      f"(slowest {lat[-1] / 1000:.1f} s)")
print(f"Estimated cost at paid prices: ${per_turn * 1000:.2f} per 1,000 chat turns; "
      f"${embed_per_query * 1000:.4f} per 1,000 searches (embedding only); hosting on Vercel Hobby: $0")
json.dump({"avg_tokens_in": tin, "avg_tokens_out": tout, "median_latency_s": lat[len(lat) // 2] / 1000,
           "usd_per_1000_chat_turns": per_turn * 1000, "usd_per_1000_searches": embed_per_query * 1000},
          open("results/part3_cost.json", "w"), indent=1)

## 9. Saving results

In [ ]:
summary.to_json("results/part3_chat_vs_search.json", indent=1)
subprocess.run(["git", "add", "results"], check=True)
subprocess.run(["git", "commit", "-q", "-m", "Part 3 run: chat evaluation, judge, judge hand-check, cost"])
subprocess.run(["git", "pull", "-q", "--rebase"])
r = subprocess.run(["git", "push", "-q"], capture_output=True, text=True)
print("Pushed to GitHub" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])