# Sahulat Home: generative search for a household-goods store
**DATA722 Generative AI & Strategic Forecasting, Phase 2 (use case C: Generative Search). Maham Naseem Alavi**

Live site: https://sahulat-home.vercel.app · Code: `mahamnalavi/data722-generative-search`

*(Added when the five notebooks were combined; not part of the original runs.)*

> **Please read, don't re-run.** This notebook combines the five notebooks I ran in Google Colab, in the order they were run. Every code cell and output is exactly as it came out of those runs. Re-running it would call the AI providers again, spend free quota, give different AI answers and overwrite the recorded outputs. The first chat run (Part 3a) would also now run the fixed code, so its "before" evidence would be lost.

## Summary of results
*(Added when the five notebooks were combined; not part of the original runs.)*

**The problem (Part 2, test set).** Ordinary keyword search finds no correct product in its top 10 for **47%** of questions that describe a need instead of naming a product (36% of all answerable questions).

**AI-written utility definitions (Part 1).** All 195 products got a definition of what they are for. Prompt v2 removed v1's unsupported claim and its wrong use (a Quran stand described as a floor cushion). My hand-check of 20: **10 accurate, 10 partly right, 0 wrong**. Local Urdu names were the weak point.

**Search (Part 2, 79 test questions scored once with settings chosen on 35 dev questions).**

| | Keyword | Meaning, store text | **Meaning, AI definitions (live)** | Hybrid |
|---|---|---|---|---|
| Correct product first (70 answerable) | 0.51 | 0.91 | **1.00** | 0.87 |
| Correct product in top 5 | 0.63 | 0.99 | **1.00** | 1.00 |
| Confidently wrong (79) | 42% | 15% | **7.6%** | 21% |
| Budget / stock violations | 0 | 0 | **0** | 0 |

**Page and visit context (Part 2).** 0 of 70 correct results lost to a misleading visit (context-override errors). The price variant matching the visit came first 81% of the time, against 36% without context. The cost is a few first places, traced to the price boost.

**Ask Sahulat chat (Part 3, second run after fixes).** Correct product first 0.96. Said "no close match" for **8 of 9** things the store doesn't sell (search bar: 3 of 9). Confidently wrong **1.3%**. 0 limit violations, 0 replies in the wrong language, 0 unsupported claim words.

**Judge.** A Gemini judge agreed with my definition hand-check on only 11 of 20, and missed language and wording problems in the first chat run, so it is used as a first filter, not as the final word.

**Cost.** \$0 on free tiers. At paid prices: about \$0.19 per 1,000 chat turns, \$0.0018 per 1,000 searches, and \$0.023 to write all 195 definitions.

## Contents and where the brief's requirements are
*(Added when the five notebooks were combined; not part of the original runs.)*

| Part | What it covers |
|---|---|
| **Part 1**: definitions and embeddings | Catalogue audit; definition prompts v1 → v2; claim check (and a bug in it, fixed); my hand-check of 20; embeddings; cost |
| **Part 2**: evaluating retrieval | The 114 Phase 1 questions (dev/test); keyword → meaning → hybrid; tuning on dev; test results; failures and fixes; page and visit context; cost |
| **Part 3a**: chat, first run | The chat as first built, its scores, conversations and judge: the "before" evidence |
| **Part 3**: chat, second run | The fixes, the full re-run, before/after comparison, the judge, my check of the judge, cost and latency |
| **Part 4**: MCP server | The catalogue search exposed as MCP tools for other assistants |

| Requirement | Where |
|---|---|
| Prompts and context design | Part 1 sections 3–4 (definition prompts v1, v2); Part 3a section 2 and Part 3 section 2 (chat prompt and message, before and after) |
| Evaluation of the Phase 1 cases, with scores | Part 2 sections 4–9 (keyword miss rate, Hit@k, no-match, confidently wrong, constraint violations, context-override errors); Part 1 section 5 (definition accuracy); Part 3 sections 4–8 (chat) |
| At least one failure and the fix | Part 1 section 4 (claim-check bug); Part 2 section 7 (confidence check after filters) and section 8 (budget words read as product words); Part 3 "What changed" and section 6 (chat: language, topic memory, marketing words, product codes) |
| Token and cost figures | Part 1 section 7; Part 2 section 10; Part 3 section 9 |
| Evidence of what was tried | Prompt v1 vs v2; hybrid vs definitions (Part 2 section 6 decision); page-weight probe (Part 2 section 9); the two chat runs (Parts 3a and 3) |

Each part keeps its own section numbers. The decisions log (`docs/DECISIONS.md` in the repository) records every design decision with its date and reason.

---

# Sahulat Home generative search, Part 1: catalogue, utility definitions and embeddings

Sahulat Home is a fictional Pakistani household-goods store; all products, brands, prices and stock levels are synthetic. Its listings describe **features** (material, size, pieces) similar to what is standard practice in e-commerce.

However, Sahulat Home also offers generative, context-aware search. Shoppers can find products by what they need them for, not only by name. Results also take into account the page they searched from and what they have browsed and searched for during the current visit (categories, products and price range). Nothing is kept after the visit ends. This is especially useful because shoppers often know **what they need a product for but not what it’s called**

This notebook builds the layer that connects the two. In this part I:
1. audit the synthetic catalogue and fix the category set;
2. generate a utility-focused **semantic definition** for every product with an LLM, comparing two prompt versions;
3. hand-check a sample of definitions for accuracy;
4. embed the products for meaning-based search and save everything for the live site;
5. record tokens and cost.

In RAG (retrieval-augmented generation) terms, this is the retrieval side: the definitions and embeddings are what the search looks things up in. The generation side, a chat assistant that answers only from retrieved products, comes in Part 3.

**AI use.** The code was written with Claude (Anthropic) as a coding assistant. I made the design decisions, choosing between options Claude proposed. The runs, hand-check verdicts and observations are my own. `docs/DECISIONS.md` in the repository records what was tried, what changed and why.

## 1. Setup
Installs the two providers' libraries, reads the API keys from Colab Secrets (they are never printed), pulls the project from GitHub and loads the shared `search` package. The live website runs the same package, so the results below describe the deployed system, not a copy.

In [1]:
!pip install -q groq google-genai

import os, sys, json, random, subprocess, time
import pandas as pd
from google.colab import userdata

os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")
os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")
token = userdata.get("GITHUB_TOKEN")

REPO = "/content/data722-generative-search"
url = f"https://x-access-token:{token}@github.com/mahamnalavi/data722-generative-search.git"
if not os.path.exists(REPO):
    r = subprocess.run(["git", "clone", "-q", url, REPO], capture_output=True, text=True)
else:
    r = subprocess.run(["git", "-C", REPO, "pull", "-q"], capture_output=True, text=True)
print("GitHub:", "OK" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])
subprocess.run(["git", "-C", REPO, "config", "user.name", "Maham (Colab run)"])
subprocess.run(["git", "-C", REPO, "config", "user.email", "mahamnalavi@users.noreply.github.com"])

sys.path.insert(0, REPO)
os.chdir(REPO)
import search
from search import load_catalogue, keyword_index
from search.llm import GroqChat, GeminiEmbedder, USAGE
from search.definitions import PROMPT_V1, PROMPT_V2, build_prompt, definition_text, unsupported_claims
from search.semantic import save_index, rank
pd.options.display.max_colwidth = 140
os.makedirs("results", exist_ok=True)
print("Search code loaded:", search.VERSION)

GitHub: OK
Search code loaded: v2-context-chat

## 2. Catalogue audit
A per-category summary (size, product types, price range, stock) and basic data-quality checks, used to fix the category set on evidence.

In [2]:
products = load_catalogue()
df = pd.DataFrame(products)
audit = df.groupby("category").agg(
    products=("product_id", "count"),
    product_types=("product_type", "nunique"),
    price_min=("price_pkr", "min"), price_median=("price_pkr", "median"), price_max=("price_pkr", "max"),
    out_of_stock=("in_stock", lambda s: f"{(~s).mean():.0%}"),
)
display(audit)
variants = df.groupby("product_type").size()
print(f"Total: {len(df)} products, {df.product_type.nunique()} product types, "
      f"{(variants > 1).sum()} types sold in 2-3 price variants, {(~df.in_stock).sum()} out of stock")
print("Missing values:", int(df.isna().sum().sum()), "| Duplicate titles:", int(df.title.duplicated().sum()))
print("\nExample of one product type in several price variants (used to test budgets and price-based personalisation):")
display(df[df.product_type == "pressure_cooker"][["product_id", "title", "price_pkr", "stock_qty"]])

,products,product_types,price_min,price_median,price_max,out_of_stock
category,,,,,,
Furniture,44,37,1450,9475.0,64500,11%
Kitchenware,59,35,290,1250.0,11900,10%
Organizers,48,35,450,1620.0,4450,17%
Tools,44,37,250,1250.0,19900,7%

Total: 195 products, 144 product types, 49 types sold in 2-3 price variants, 22 out of stock
Missing values: 0 | Duplicate titles: 0

Example of one product type in several price variants (used to test budgets and price-based personalisation):

,product_id,title,price_pkr,stock_qty
19,KIT-020,"Aluminium Pressure Cooker, 5 Litre",5950,20
20,KIT-021,"Stainless Steel Pressure Cooker, 7 Litre, Induction Base",11900,3
21,KIT-022,"Mini Pressure Cooker, 3 Litre",4350,42

**Decision:** I kept the four categories (Kitchenware, Tools, Organizers, Furniture). They are reasonably balanced (44-59 products each), no data is missing, and the 195-product total is inside the planned 150-200 range.

**Observations:** The catalogue has 195 products across four categories: Kitchenware 59, Organizers 48, Tools 44, Furniture 44. That’s balanced enough that no category dominates the evaluation, and the total sits within the range of 150–200 that I planned.

Prices span very different ranges by category: Organizers stay between Rs 450 and Rs 4,450, while Furniture runs from Rs 1,450 to Rs 64,500 (median Rs 9,475). That matters for budget questions, because a phrase like “under 5,000” rules out most furniture but almost no organizers. 49 of the 144 product types come in two or three price variants, which is what lets me test price-based personalisation.

22 products (11%) are out of stock, with Organizers having the most (8), so stock limits are tested too. No values are missing and no titles are duplicated. I kept the four categories as they are.

## 3. Semantic definitions: first attempt (prompt v1)
A simple prompt asks `gpt-oss-120b` (on Groq) to describe 10 hard-to-name products. Each definition is then checked automatically for claims the catalogue does not support, for example "dishwasher safe" when the specs never say so.

This matters beyond accuracy. Under the Competition Commission of Pakistan's April 2023 deceptive-marketing guidelines (Section 10, Competition Act 2010), product claims must be substantiated, so a definition shown to shoppers cannot invent features.

In [3]:
llm = GroqChat()
by_id = {p["product_id"]: p for p in products}
SAMPLE = ["KIT-003", "KIT-025", "KIT-007", "TOL-001", "ORG-005", "FUR-001", "FUR-036", "KIT-053", "TOL-018", "KIT-015"]

def generate(version, ids, batch_size=5, task="definitions"):
    """Ask the model for definitions in batches of 5. Any product missing from a batch reply
    is retried on its own (twice); if it still fails, it gets a title-only fallback and is reported."""
    out = {}
    ok = lambda item: bool(item) and bool(definition_text(item))
    for i in range(0, len(ids), batch_size):
        batch = [by_id[x] for x in ids[i:i + batch_size]]
        try:
            data, _ = llm.chat_json([{"role": "user", "content": build_prompt(version, batch)}],
                                    task=f"{task}_{version}", max_tokens=2500, n_items=len(batch))
            for item in data.get("items", []):
                if item.get("product_id") in by_id and ok(item):
                    out[item["product_id"]] = item
        except Exception as e:
            print("  batch problem, retrying one by one:", type(e).__name__)
        for p in batch:
            for attempt in range(2):
                if p["product_id"] in out:
                    break
                try:
                    data, _ = llm.chat_json([{"role": "user", "content": build_prompt(version, [p])}],
                                            task=f"{task}_{version}", max_tokens=1200)
                    item = (data.get("items") or [{}])[0]
                    if ok(item):
                        out[p["product_id"]] = {**item, "product_id": p["product_id"]}
                except Exception as e:
                    print(f"  {p['product_id']} attempt {attempt + 1} failed:", type(e).__name__)
            if p["product_id"] not in out:
                print(f"  FALLBACK used for {p['product_id']} (title only); reported in the results")
                out[p["product_id"]] = {"product_id": p["product_id"], "what_it_is": p["title"], "fallback": True}
        print(f"  {version}: {len(out)}/{len(ids)} done")
    return out

print("Prompt v1:\n" + PROMPT_V1.split("Products:")[0])
v1 = generate("v1", SAMPLE)

def check_table(defs):
    rows = []
    for pid, d in defs.items():
        text = definition_text(d)
        rows.append({"product_id": pid, "title": by_id[pid]["title"], "definition": text,
                     "unsupported_claims": ", ".join(unsupported_claims(text, by_id[pid])) or "-"})
    return pd.DataFrame(rows)

t1 = check_table(v1)
display(t1)
print(f"v1: {(t1.unsupported_claims != '-').sum()} of {len(t1)} definitions contain a claim the catalogue does not support")
json.dump(v1, open("results/definitions_v1_sample.json", "w"), indent=1, ensure_ascii=False)

Prompt v1:
You write short descriptions for an online household-goods store in Pakistan.
For each product below, describe what it is and what people use it for.

Return JSON: {"items": [{"product_id": "...", "definition": "..."}]}


  v1: 5/10 done
  v1: 10/10 done

,product_id,title,definition,unsupported_claims
0,KIT-003,Adjustable Mandoline with 5 Thickness Settings,"A kitchen mandoline made of ABS with stainless‑steel blades, offering five adjustable thickness settings and a julienne insert, plus a h...",-
1,KIT-025,"Wooden Hand Churner (Madhani), 45 cm","A traditional wooden hand churner (Madhani) crafted from sheesham wood, 45 cm long with a star‑shaped churn head, used for manually chur...",-
2,KIT-007,Stainless Steel Bench Scraper with Measuring Edge,"A stainless‑steel bench scraper featuring a 15 × 11 cm blade, wooden handle, and built‑in inch and centimetre measuring marks, ideal for...",-
3,TOL-001,"Electronic Wall Scanner, 4-in-1","A 4‑in‑1 electronic wall scanner that detects wood studs, metal objects, live AC wires and deep‑scan targets, with an LCD display and po...",-
4,ORG-005,"Lazy Susan Turntable, 30 cm","A 30 cm clear acrylic Lazy Susan turntable that rotates 360°, providing easy access to spices, condiments or small kitchen items stored ...",-
5,FUR-001,"Cane Mooda Stool, Natural","A round stool made from woven cane and reed, standing 45 cm tall with a 40 cm seat diameter, ideal for casual seating in living rooms or...",-
6,FUR-036,"Wooden Folding Rehal, Carved","A hand‑carved Sheesham‑wood rehal that folds flat (30 cm when open), used as a decorative floor cushion or low seating piece in living r...",-
7,KIT-053,Glass Boil-Over Preventer Disc,"A 7 cm diameter disc of heat‑resistant glass that sits on top of a pot to prevent water or milk from boiling over, protecting stovetops ...",-
8,TOL-018,"Drain Auger, 5 m Steel Cable","A 5‑metre long, 6 mm spring‑steel cable with a crank‑drum handle, designed to clear clogs in drains and pipes.",-
9,KIT-015,"Cast Iron Tawa, 12 inch","A 12‑inch pre‑seasoned cast‑iron tawa, weighing about 2.1 kg, perfect for making flatbreads, pancakes, and stir‑frying on the stove.",perfect

v1: 1 of 10 definitions contain a claim the catalogue does not support

**Observations on v1:** The automatic check flagged only 1 of the 10 v1 definitions: “perfect” in the cast iron tawa’s definition, a marketing word. Reading them myself showed bigger problems the check could not see. Most definitions mainly repeat the specs (“made of ABS with stainless-steel blades… five thickness settings”) and only mention the use at the end, so they add little that a shopper would actually type.

Additionally, none include Urdu or Roman Urdu names, even for products shoppers know by those names. The rehal is described as “a decorative floor cushion or low seating piece”, when it is a folding stand for holding the Quran or a book while reading. That is a confidently wrong definition that passed the automatic check, because the check only looks for claim words, not for the wrong use. This is why v2 asks for structured uses, shopper phrases and local names, and why the hand-check and the judge are needed alongside the automatic check.

## 4. Semantic definitions: revised prompt (v2)
v2 targets the main risk in generated product text, unsupported claims. It restricts the model to the given facts, rules out safety, health, durability and marketing claims, and asks for structured fields (what it is, uses, shopper phrases, Urdu or Roman Urdu names). Structured fields can be checked one by one, and the local names give Urdu and Roman Urdu searches something to match.

The comparison below shows how v1 and v2 actually differ on the same 10 products. v2 then runs on all 195 products, in about 40 calls paced to stay under Groq's free limit of 8,000 tokens per minute.

In [4]:
print("Prompt v2:\n" + PROMPT_V2.split("Products:")[0])
v2_sample = generate("v2", SAMPLE)
t2 = check_table(v2_sample)
display(t2)
print(f"Flagged unsupported claims on the same 10 products: v1 = {(t1.unsupported_claims != '-').sum()}, "
      f"v2 = {(t2.unsupported_claims != '-').sum()}")

Prompt v2:
You write search definitions for an online household-goods store in Pakistan.
A shopper may not know a product's name, so they describe the job they need done.
For each product, write what it is FOR, in plain everyday words.

Rules:
1. Use only the facts given (title, category, specs). Do not add features, materials,
   certifications, safety, health or durability claims that are not in the facts.
2. Uses must follow directly from what the product is. No marketing words
   ("best", "premium", "perfect", "must-have").
3. Include phrases a shopper might type, in English, and common Urdu or Roman Urdu
   names only if you are confident they are used in Pakistan (otherwise leave the list empty).
4. Keep each field short.

Return JSON exactly in this shape:
{"items": [{"product_id": "...",
            "what_it_is": "one sentence",
            "used_for": ["2-4 short uses"],
            "shopper_phrases": ["3-5 things a shopper might type"],
            "local_names": ["0-3 Urdu or Roman Urdu names"]}]}


  v2: 5/10 done
  v2: 10/10 done

,product_id,title,definition,unsupported_claims
0,KIT-003,Adjustable Mandoline with 5 Thickness Settings,A hand‑held slicer with adjustable thickness settings and a julienne insert. Used for: thinly slice vegetables; make uniform potato chip...,-
1,KIT-025,"Wooden Hand Churner (Madhani), 45 cm",A wooden hand‑crank churner for making butter or curd. Used for: hand‑churn butter at home; make fresh curd or lassi; stir thick mixture...,-
2,KIT-007,Stainless Steel Bench Scraper with Measuring Edge,A stainless‑steel bench scraper with built‑in inch and centimetre measurement markings. Used for: scrape dough from work surface; measur...,-
3,TOL-001,"Electronic Wall Scanner, 4-in-1","A handheld electronic scanner that detects wood, metal, live AC wires and deep objects behind walls. Used for: locate studs in walls; fi...",-
4,ORG-005,"Lazy Susan Turntable, 30 cm",A clear acrylic rotating turntable for easy access to items on a kitchen shelf or countertop. Used for: store spices for quick reach; di...,-
5,FUR-001,"Cane Mooda Stool, Natural",A round stool made of cane and reed for sitting. Used for: extra seating in living room; footrest while watching TV; small table for hol...,-
6,FUR-036,"Wooden Folding Rehal, Carved",A hand‑carved sheesham wood folding rehal for holding the Qur'an. Used for: prayer stand; displaying books; decorative accent. Shoppers ...,-
7,KIT-053,Glass Boil-Over Preventer Disc,A glass disc placed on a pot to stop water from boiling over. Used for: prevent boil‑over while cooking rice; keep stovetop clean; reduc...,-
8,TOL-018,"Drain Auger, 5 m Steel Cable",A 5 m steel cable auger with a crank handle for clearing clogged drains. Used for: unclog bathroom sink; remove hair blockage in shower ...,-
9,KIT-015,"Cast Iron Tawa, 12 inch",A 12‑inch pre‑seasoned cast‑iron tawa for cooking flatbreads and pancakes. Used for: making roti or chapati; cooking pancakes; searing v...,-

Flagged unsupported claims on the same 10 products: v1 = 1, v2 = 0

In [5]:
t0 = time.time()
remaining = [p["product_id"] for p in products if p["product_id"] not in v2_sample]
v2 = {**v2_sample, **generate("v2", remaining)}
print(f"Generated {len(v2)} definitions in {(time.time() - t0) / 60:.1f} minutes")

payload = {"prompt_version": "v2", "model": llm.model, "generated": time.strftime("%Y-%m-%d %H:%M"),
           "items": {pid: {**v2[pid], "text": definition_text(v2[pid])} for pid in sorted(v2)}}
json.dump(payload, open("data/definitions_v2.json", "w"), indent=1, ensure_ascii=False)

all_checks = check_table(v2)
flagged = all_checks[all_checks.unsupported_claims != "-"]
has_local = sum(1 for d in v2.values() if d.get("local_names"))
fallbacks = [pid for pid, d in v2.items() if d.get("fallback")]
print(f"Fallback (title only) used for {len(fallbacks)} products: {fallbacks or 'none'}")
print(f"Automatic check, all {len(v2)} products: {len(flagged)} flagged ({len(flagged) / len(v2):.0%}); "
      f"{has_local} include Urdu/Roman Urdu names")
display(flagged)

  v2: 5/185 done
  v2: 10/185 done
  v2: 15/185 done
  v2: 20/185 done
  v2: 25/185 done
  v2: 30/185 done
  v2: 35/185 done
  v2: 40/185 done
  v2: 45/185 done
  v2: 50/185 done
  v2: 55/185 done
  v2: 60/185 done
  v2: 65/185 done
  v2: 70/185 done
  v2: 75/185 done
  v2: 80/185 done
  v2: 85/185 done
  v2: 90/185 done
  v2: 95/185 done
  v2: 100/185 done
  v2: 105/185 done
  v2: 110/185 done
  v2: 115/185 done
  v2: 120/185 done
  v2: 125/185 done
  v2: 130/185 done
  v2: 135/185 done
  v2: 140/185 done
  v2: 145/185 done
  v2: 150/185 done
  v2: 155/185 done
  v2: 160/185 done
  v2: 165/185 done
  v2: 170/185 done
  v2: 175/185 done
  v2: 180/185 done
  v2: 185/185 done
Generated 195 definitions in 7.3 minutes
Fallback (title only) used for 0 products: none
Automatic check, all 195 products: 6 flagged (3%); 162 include Urdu/Roman Urdu names

,product_id,title,definition,unsupported_claims
11,KIT-002,"Silicone Egg Yolk Separator, Food-Grade",A food‑grade silicone tool for separating egg yolks from whites. Used for: splitting yolk for sauces; collecting whites for baking; easy...,food grade
13,KIT-005,Heavy-Duty Zinc Alloy Garlic Press,A heavy‑duty garlic press made of zinc alloy with a chrome finish. Used for: pressing garlic cloves into paste; quickly mincing garlic f...,heavy duty
76,TOL-014,Heavy-Duty Caulking Gun,A steel-frame gun that pushes caulk out of standard cartridges. Used for: sealing gaps around windows; filling cracks in walls; applying...,heavy duty
79,TOL-017,"Flange Plunger, Heavy-Duty",A heavy‑duty plunger with a flange rubber cup and plastic handle. Used for: unclogging toilets with a flange cup; clearing bathroom drai...,heavy duty
101,TOL-040,Heavy-Duty Staple Gun with 600 Staples,A steel heavy‑duty staple gun that holds 600 staples (6‑10 mm). Used for: securing upholstery fabric; attaching carpet padding; fastenin...,heavy duty
131,ORG-027,"Bamboo Shoe Rack, 2 Tiers",A two‑tier bamboo shoe rack. Used for: hold up to 6 pairs of shoes; organize shoes in a natural wood look; save space in a hallway. Shop...,eco

**Correction:** Reading the 6 flagged rows, 5 were false alarms: the check treated “Heavy-Duty” in a title and “heavy duty” in a definition as different words. I fixed the check to treat hyphens as spaces and re-ran it below on the same definitions.

In [6]:
# Re-check with the corrected claim checker (hyphens treated as spaces). The original output above is kept.
import importlib, search.definitions as defs_mod
subprocess.run(["git", "-C", REPO, "pull", "-q"], check=True)
importlib.reload(defs_mod)
unsupported_claims = defs_mod.unsupported_claims
re_v1 = check_table(v1)
re_all = check_table(v2)
re_flagged = re_all[re_all.unsupported_claims != "-"]
print(f"Corrected check: v1 sample {(re_v1.unsupported_claims != '-').sum()} of 10 flagged; "
      f"all 195 v2 definitions: {len(re_flagged)} flagged ({len(re_flagged) / len(v2):.0%}), was 6")
display(re_flagged)
json.dump({"v1_sample_flagged": int((re_v1.unsupported_claims != '-').sum()), "v2_all_flagged": len(re_flagged),
           "v2_flagged_ids": re_flagged.product_id.tolist()}, open("results/claim_check_corrected.json", "w"), indent=1)

Corrected check: v1 sample 1 of 10 flagged; all 195 v2 definitions: 1 flagged (1%), was 6

,product_id,title,definition,unsupported_claims
131,ORG-027,"Bamboo Shoe Rack, 2 Tiers",A two‑tier bamboo shoe rack. Used for: hold up to 6 pairs of shoes; organize shoes in a natural wood look; save space in a hallway. Shop...,eco

**Observation:** On the same 10 products, v2 had no unsupported claim words (v1 had 1, “perfect”), and it fixed v1’s most serious error: the rehal went from “a decorative floor cushion” to “a folding stand for holding the Qur’an”. Structured fields made the uses explicit (“Used for: making roti or chapati”) instead of burying them after the specs. However, v2 is not perfect: it calls the madhani “hand-crank” when it is turned by hand. Across all 195 products, v2 generated every definition in 7.3 minutes with no fallbacks, and 162 include an Urdu or Roman Urdu name. The automatic check first flagged 6, but reading them showed 5 false alarms caused by my checker treating “Heavy-Duty” and “heavy duty” as different words. After fixing the checker, 1 genuine flag remains (“eco” for the bamboo shoe rack).

## 5. Hand check: definition accuracy
20 products, 5 per category, drawn at random with a fixed seed per category so the sample can be reproduced. I judged each definition against the product's facts:
- **Y**: accurate and useful
- **P**: partly right (a small error, or an obvious use missing)
- **N**: wrong or misleading

In [7]:
payload = json.load(open("data/definitions_v2.json"))   # reload, in case Colab restarted since section 4
HANDCHECK = []
for c in ["Kitchenware", "Tools", "Organizers", "Furniture"]:
    ids = sorted(p["product_id"] for p in products if p["category"] == c)
    HANDCHECK += sorted(random.Random("handcheck-" + c).sample(ids, 5))

for pid in HANDCHECK:
    p = by_id[pid]
    print(f"{pid} | {p['title']}  (Rs {p['price_pkr']:,})")
    print("   FACTS:", "; ".join(f"{k}: {v}" for k, v in p["attributes"].items()))
    print("   DEFINITION:", payload["items"][pid]["text"], "\n")

KIT-013 | Fine Mesh Conical Strainer (Chinois), 20 cm  (Rs 1,690)
   FACTS: material: Stainless steel 18/8; mesh: Extra fine; diameter: 20 cm
   DEFINITION: A 20 cm stainless steel conical strainer with an extra‑fine mesh. Used for: sieving fine sauces; removing seeds from purees; straining tea leaves; filtering powdered spices. Shoppers say: fine mesh strainer; conical chinois 20 cm; stainless steel tea strainer; sieve for sauces; small kitchen strainer. Also called: چینی سٹرینر, چینی سٹرینر 20 سینٹی میٹر.

KIT-030 | Fine Rasp Grater with Soft Grip  (Rs 1,250)
   FACTS: material: Stainless steel photo-etched blade; length: 30 cm; includes: Blade cover
   DEFINITION: A handheld stainless‑steel grater with a soft grip handle. Used for: grating cheese; shredding carrots; rubbing nutmeg; making zest. Shoppers say: cheese grater; fine grater for zest; stainless steel rasp; small kitchen grater. Also called: rasp grater, grater.

KIT-031 | 4-Sided Box Grater  (Rs 890)
   FACTS: material: Stainless steel; sides: 4 (fine, medium, coarse, slicer); height: 24 cm
   DEFINITION: A four‑sided stainless‑steel box grater with fine, medium, coarse and slicer sides. Used for: grating cheese; shredding vegetables; coarse grating potatoes; slicing cucumbers. Shoppers say: box grater 4 side; multi side grater; stainless steel grater; kitchen grater for veg. Also called: box grater, grater.

KIT-040 | Handheld Vegetable Spiralizer, 4 Blades  (Rs 1,190)
   FACTS: material: PP plastic, steel blades; blades: 4 interchangeable
   DEFINITION: A handheld tool with four interchangeable blades for turning vegetables into spirals or ribbons. Used for: making zucchini noodles; creating curly carrot strips; preparing decorative salad toppings. Shoppers say: vegetable spiralizer; zucchini noodles tool; spiral cut veggies; handheld veggie slicer. Also called: سبزی سپائرلائزر, سبزی کا سپائرل میکر.

KIT-041 | Cast Aluminium Lemon Squeezer  (Rs 790)
   FACTS: material: Enamel-coated aluminium; type: Hand press
   DEFINITION: A hand‑press lemon squeezer made of enamel‑coated cast aluminium. Used for: extracting juice from lemons; pressing small citrus fruits; making fresh lemonade. Shoppers say: lemon squeezer hand press; cast aluminium citrus press; manual lemon juicer. Also called: لیموں کا رس نکالنے والا, لیموں کا سqueezer.

TOL-003 | Magnetic Torpedo Level, 9 inch  (Rs 650)
   FACTS: length: 9 in; vials: 3; base: Magnetic
   DEFINITION: A 9‑inch magnetic level with three vials for checking straightness. Used for: checking walls for plumb; aligning shelves; installing picture frames. Shoppers say: level for wall mounting; magnetic level 9 inch; how to check if a surface is level. Also called: مقناطیسی لیول, magnetic level.

TOL-015 | Pipe Wrench, 14 inch  (Rs 1,650)
   FACTS: length: 14 in; material: Drop-forged steel; jaw: Up to 2 in
   DEFINITION: A 14‑inch pipe wrench made of drop‑forged steel for turning pipes. Used for: tightening pipe fittings; removing stuck pipe nuts; plumbing repairs. Shoppers say: 14 inch pipe wrench; pipe wrench steel; plumbing wrench. Also called: پائپ رنچ, pipe wrench.

TOL-030 | Retractable Utility Knife with 5 Blades  (Rs 450)
   FACTS: blade: 18 mm snap-off; spares: 5; lock: Auto-lock slider
   DEFINITION: A retractable utility knife that comes with five snap‑off blades. Used for: cutting cardboard or packaging; trimming carpet or vinyl; opening boxes. Shoppers say: retractable utility knife 5 blades; snap off knife for home; handheld cutting knife; utility knife with auto lock; box cutting knife. Also called: یوزٹیلیٹی نائف, کٹر چاقو.

TOL-036 | Wall Plug and Screw Kit, 200 Pieces  (Rs 690)
   FACTS: pieces: 200; sizes: 6 mm and 8 mm plugs, matching screws
   DEFINITION: A kit of 200 wall plugs and matching screws in 6 mm and 8 mm sizes. Used for: fixing shelves to walls; installing picture frames; mounting light fixtures. Shoppers say: wall plug and screw kit; 200 pieces plugs screws; 6mm and 8mm wall anchors; fixings for drywall. Also called: وال پلگ, سکرو کٹ.

TOL-039 | 3.6 V Cordless Screwdriver, USB  (Rs 3,650)
   FACTS: voltage: 3.6 V; battery: Li-ion 1500 mAh; bits: 10
   DEFINITION: A small cordless screwdriver that runs on a 3.6 V Li‑ion battery and includes 10 bits. Used for: tightening screws in furniture; assembling flat‑pack items; installing light fixtures; quick repairs without a cord. Shoppers say: cordless screwdriver; battery powered screwdriver; screwdriver with USB charger; small electric screwdriver; DIY screwdriver. Also called: بغیر تار کے سکرو ڈرائیور, cordless screwdriver.

ORG-003 | Adjustable Bamboo Drawer Dividers, Set of 4  (Rs 2,950)
   FACTS: material: Bamboo; length: Spring-loaded 44-55 cm; pieces: 4
   DEFINITION: A set of four bamboo drawer dividers that adjust to fit drawer width. Used for: separating utensils in kitchen drawer; organising office supplies; keeping cutlery sorted. Shoppers say: bamboo drawer dividers; adjustable drawer organizer; drawer separator set; kitchen drawer organizer bamboo; spring loaded drawer dividers.

ORG-005 | Lazy Susan Turntable, 30 cm  (Rs 1,290)
   FACTS: diameter: 30 cm; material: Clear acrylic; rotation: 360 degrees
   DEFINITION: A clear acrylic rotating turntable for easy access to items on a kitchen shelf or countertop. Used for: store spices for quick reach; display condiments on a countertop; organise small jars in cabinets. Shoppers say: lazy susan turntable 30 cm; clear acrylic rotating tray; kitchen turntable. Also called: لیزی سوزن.

ORG-014 | Clear Fridge Organizer Bins, Set of 4  (Rs 1,950)
   FACTS: pieces: 4; material: BPA-free PET; handles: Built-in
   DEFINITION: Clear PET bins with built-in handles for arranging items inside a refrigerator. Used for: store fruits and vegetables; separate dairy products; keep leftovers organized; stack items without sliding. Shoppers say: clear fridge bins; refrigerator organizer bins; transparent fridge storage; fridge bins set of 4.

ORG-020 | Velvet Hangers, Pack of 20  (Rs 1,890)
   FACTS: pieces: 20; material: Velvet-flocked ABS; hook: 360-degree
   DEFINITION: Velvet‑flocked plastic hangers with a 360‑degree hook. Used for: hang shirts; keep dresses from slipping; organize coats; store trousers. Shoppers say: velvet hangers pack; soft plastic hangers; 360 degree hook hangers; wardrobe velvet hangers.

ORG-034 | Over-the-Sink Roll-Up Drying Rack  (Rs 1,450)
   FACTS: size: 52 x 32 cm; material: Silicone-coated steel; folds: Rolls up
   DEFINITION: A roll‑up drying rack that fits over the sink, made of silicone‑coated steel. Used for: dry dishes in sink area; store small utensils while drying; save countertop space; easy to roll away. Shoppers say: over sink drying rack; roll up dish rack; silicone coated drying rack; sink countertop dryer; foldable dish rack. Also called: sink ke upar rack, roll up drying rack.

FUR-003 | Woven Rope Charpai, Sheesham Frame  (Rs 18,500)
   FACTS: material: Sheesham legs, nylon rope weave; size: 190 x 90 cm
   DEFINITION: A woven rope charpai with a sheesham wood frame. Used for: relaxing in the living room; outdoor seating on a balcony; guest sleeping area. Shoppers say: rope charpai; sheesham frame charpai; woven rope bed. Also called: چَرپائی, روپ چارپائی.

FUR-004 | Storage Ottoman, Fabric, 76 cm  (Rs 8,950)
   FACTS: size: 76 x 38 x 38 cm; material: Linen-look fabric, MDF; lid: Hinged
   DEFINITION: A fabric-covered ottoman with a hinged lid for hidden storage. Used for: extra seating; storing blankets or magazines; footrest in living room. Shoppers say: ottoman with storage; fabric storage ottoman; living room footrest; hidden storage ottoman. Also called: اُٹمان, Ottoman.

FUR-016 | Drop-Leaf Dining Table, Seats 2-4  (Rs 19,900)
   FACTS: size_open: 120 x 75 cm; size_folded: 75 x 40 cm; material: Rubberwood
   DEFINITION: A drop‑leaf dining table that seats 2‑4 people. Used for: small family meals; compact dining space; temporary work surface; folded storage when not in use. Shoppers say: drop leaf dining table; foldable dining table; 2 to 4 seat table; compact dining table. Also called: ڈائننگ ٹیبل, فولڈنگ ٹیبل.

FUR-023 | Sheesham Wood Bedside Table, Open Shelf  (Rs 12,500)
   FACTS: size: 45 x 40 x 55 cm; material: Solid sheesham; shelves: 1 open
   DEFINITION: A sheesham wood bedside table with an open shelf. Used for: holding a lamp or alarm clock; displaying books or decor; quick access to bedside items. Shoppers say: sheesham bedside table; wooden nightstand with shelf; open shelf bedside table; solid wood bedside table; bedroom table sheesham. Also called: شیشم ٹیبل, نائٹ اسٹینڈ.

FUR-039 | Single-Seat Recliner, Fabric  (Rs 54,500)
   FACTS: mechanism: Manual lever; material: Fabric, solid wood frame
   DEFINITION: A single‑seat fabric recliner with a manual lever and solid wood frame Used for: Relax and recline after work; Watch TV comfortably; Read a book in a cozy seat. Shoppers say: fabric recliner chair; single seat recliner; manual lever recliner; living room recliner; reclining chair. Also called: ریکلائنر.

In [9]:
# My verdicts: (Y / P / N, note)
VERDICTS = {
    "KIT-013": ("P", "Urdu name 'Chini strainer' is invented."), "KIT-030": ("P", "Zest and nutmeg are right, but a fine rasp isn’t really for “shredding carrots”; that’s a box grater."), "KIT-031": ("Y", "No issue observed"), "KIT-040": ("Y", "No issue observed"), "KIT-041": ("P", "Uses fine, but one local name is garbled mixed script:لیموں کا سqueezer"),
    "TOL-003": ("P", "Uses correct but Urdu name is not commonly used and doesn't imply the same product."), "TOL-015": ("Y", "No issue observed."), "TOL-030": ("P", "Uses fine; small spelling slip in the other second Urdu name (not cutter کٹر)"), "TOL-036": ("P", "Fixings for drywall: 6/8 mm wall plugs are for brick or concrete walls, which most Pakistani homes have, not drywall. This is a minor issue in use that needs correction."), "TOL-039": ("Y", "No issue observed."),
    "ORG-003": ("Y", "No issue observed."), "ORG-005": ("P", "Uses fine; Urdu should also have tranlation for 'kitchen table' and 'table' as they are more commonly used words."), "ORG-014": ("P", "Uses mainly correct but they also state 'Stack items without sliding' even though facts never say they stack. This is a small unsupported claim."), "ORG-020": ("Y", "No issue observed."), "ORG-034": ("Y", "No issue observed."),
    "FUR-003": ("P", "Uses are OK, but 'living room' isn’t where a charpai usually goes; the Urdu spelling چَرپائی is off and چارپائی is correct"), "FUR-004": ("P", "Uses are correct but Urdu spelling for Ottoman is incorrect; the correct is اوٹومن"), "FUR-016": ("Y", "No issue observed."), "FUR-023": ("Y", "No issue observed."), "FUR-039": ("Y", "No issue observed."),
}
assert sorted(VERDICTS) == sorted(HANDCHECK), "The IDs above must match the sample shown"
marks = [v for v, _ in VERDICTS.values()]
if "?" in marks:
    print(f"{marks.count('?')} products still marked '?'. Fill them in and run again.")
else:
    y, p_, n = marks.count("Y"), marks.count("P"), marks.count("N")
    print(f"Definition accuracy (hand check, n=20): strict {y / 20:.0%} (Y only), lenient {(y + p_) / 20:.0%} (Y + P); wrong: {n}")
    json.dump({pid: {"verdict": v, "note": n_} for pid, (v, n_) in VERDICTS.items()},
              open("results/definition_handcheck.json", "w"), indent=1)

Definition accuracy (hand check, n=20): strict 50% (Y only), lenient 100% (Y + P); wrong: 0

**Observation:** I judged 20 definitions (5 per category): 10 accurate (Y), 10 partly right (P), none wrong. That is 50% strict and 100% lenient accuracy. Observation highlights are:
1. Most P verdicts were about the local names, not the uses: an invented Urdu name (“Chini strainer” for a chinois), misspellings, and names that aren’t commonly used.
2. Four involved the uses or claims: a fine rasp described as “shredding carrots”, wall plugs “for drywall” (Pakistani walls are mostly brick), fridge bins said to “stack” when the facts don’t say so, and a charpai suggested for the living room. These are minor, so the uses are reliable enough to show shoppers in the “What it’s for” box, which shows uses only. The local names are not, so I keep them only as hidden search text.

A better fix would be a short hand-made glossary of common Urdu product names instead of letting the model invent them.

## 6. Embeddings
Gemini (`gemini-embedding-001`, 768 dimensions) turns each product's text into a vector that represents its meaning, so products can be matched to a query by meaning rather than shared words. Two indexes are saved, so that the effect of the definitions can be isolated in Part 2:
- **catalogue text**: title, subcategory and description, as written by the store
- **definitions**: title plus the AI definition

A quick side-by-side on 6 queries follows. The scored comparison on 114 labelled queries is in Part 2.

In [10]:
payload = json.load(open("data/definitions_v2.json"))
emb = GeminiEmbedder()
ids = [p["product_id"] for p in products]
cat_texts = [f'{p["title"]}. {p["subcategory"]}. {p["description"]}' for p in products]
def_texts = [f'{p["title"]}. {payload["items"][p["product_id"]]["text"]}' for p in products]

meta = {"model": emb.model, "dims": emb.dims, "task_type": "RETRIEVAL_DOCUMENT"}
cat_vecs = emb.embed(cat_texts, kind="document", task="embed_products")
save_index("emb_catalogue", ids, cat_vecs, {**meta, "text": "title + subcategory + description"})
def_vecs = emb.embed(def_texts, kind="document", task="embed_products")
save_index("emb_definitions_v2", ids, def_vecs, {**meta, "text": "title + definition v2"})
print(f"Saved 2 indexes: {len(cat_vecs)} products x {len(cat_vecs[0])} numbers each")

  Gemini rate limit; waiting 30s (attempt 1)
  Gemini rate limit; waiting 30s (attempt 2)
  Gemini rate limit; waiting 30s (attempt 3)
  Gemini rate limit; waiting 30s (attempt 1)
  Gemini rate limit; waiting 30s (attempt 1)
  Gemini rate limit; waiting 30s (attempt 2)
Saved 2 indexes: 195 products x 768 numbers each

In [11]:
from search.semantic import load_index
load_index.cache_clear()
idx_cat, idx_def = load_index("emb_catalogue"), load_index("emb_definitions_v2")
TRY = ["something to separate egg whites from yolks", "slice potatoes thin for chips",
       "pyaz barik katne wali cheez", "find the wooden beam behind my wall before drilling",
       "stop milk from boiling over", "seat for my elderly mother to pray"]
qvecs = emb.embed(TRY, kind="query", task="embed_queries")
title = lambda pid: by_id[pid]["title"][:45]
rows = []
for q, qv in zip(TRY, qvecs):
    kw = [title(pid) for pid, _ in keyword_index().search(q, 3)] or ["(no match)"]
    rows.append({"query": q,
                 "keyword top 3": " | ".join(kw),
                 "embeddings, catalogue text": " | ".join(title(pid) for pid, _ in rank(qv, idx_cat, 3)),
                 "embeddings, definitions": " | ".join(title(pid) for pid, _ in rank(qv, idx_def, 3))})
display(pd.DataFrame(rows))

,query,keyword top 3,"embeddings, catalogue text","embeddings, definitions"
0,something to separate egg whites from yolks,"Silicone Egg Yolk Separator, Food-Grade | Egg Holder Drawer for Fridge, 21 Eggs | 3-Piece Stainless Steel Egg Separator Set","Silicone Egg Yolk Separator, Food-Grade | 3-Piece Stainless Steel Egg Separator Set | Egg Holder Drawer for Fridge, 21 Eggs","3-Piece Stainless Steel Egg Separator Set | Silicone Egg Yolk Separator, Food-Grade | Egg Holder Drawer for Fridge, 21 Eggs"
1,slice potatoes thin for chips,(no match),"Adjustable Mandoline with 5 Thickness Setting | 8-Blade Apple Slicer and Corer | Compact V-Blade Mandoline, 3 Inserts","Adjustable Mandoline with 5 Thickness Setting | Compact V-Blade Mandoline, 3 Inserts | 4-Sided Box Grater"
2,pyaz barik katne wali cheez,(no match),"Pull-String Chopper, 900 ml, 5 Blades | Pull-String Manual Chopper, 500 ml | Adjustable Mandoline with 5 Thickness Setting","Adjustable Mandoline with 5 Thickness Setting | Pull-String Manual Chopper, 500 ml | Pizza Cutter Wheel with Finger Guard"
3,find the wooden beam behind my wall before drilling,Rubber Cup Plunger with Wooden Handle | Wall-Mounted Plastic Bag Holder | Wall Pegboard Kit with 10 Accessories,"Electronic Wall Scanner, 4-in-1 | Drill Bit Set, 13 Pieces, Masonry and Wood | Wall-Mounted Fold-Down Desk","Electronic Wall Scanner, 4-in-1 | Drill Bit Set, 13 Pieces, Masonry and Wood | Magnetic Torpedo Level, 9 inch"
4,stop milk from boiling over,"Glass Boil-Over Preventer Disc | Metal Bunk Bed, Single over Single | Over-the-Door Shoe Organizer, 24 Pockets","Glass Boil-Over Preventer Disc | Splatter Guard Screen, 33 cm | 3-Piece Stainless Steel Egg Separator Set","Glass Boil-Over Preventer Disc | Splatter Guard Screen, 33 cm | 3-Piece Stainless Steel Egg Separator Set"
5,seat for my elderly mother to pray,"Folding Steel Chair, Padded Seat | Single-Seat Recliner, Fabric | Foldable Prayer Chair with Backrest","Foldable Prayer Chair with Backrest | Wooden Rocking Chair | Folding Steel Chair, Padded Seat",Foldable Prayer Chair with Backrest | Wooden Rocking Chair | Floor Cushion Gaddi Set with Bolster

**Observations:** On these 6 examples, keyword search fails on 2 queries outright (“slice potatoes thin for chips” and the Roman Urdu “pyaz barik katne wali cheez” both return nothing). For “wooden beam behind my wall” it returns wrong products (a plunger, a bag holder), because it only matches shared words. Both meaning-based methods put a correct product first in all 6 cases, including the Roman Urdu query, where they found the chopper and the mandoline. To my surprise, meaning search on the store’s own text did about as well as on the AI definitions here, because the embedding model already links needs to product names quite well. So these 6 examples show that meaning search beats keyword search, but not yet whether the definitions add value on top. That is tested on 114 labelled questions in Part 2. The “rate limit, waiting” messages show the free Gemini tier slowing the run; the code waited and finished without errors.

## 7. Tokens and cost
Every AI call in this notebook is logged. The project runs on free tiers, so the actual cost is \$0. The estimate below uses published paid prices:
- Groq `gpt-oss-120b`: \$0.15 per million input tokens and \$0.60 per million output tokens (third-party price index, October 2026)
- Gemini `gemini-embedding-001`: \$0.15 per million tokens (Google Developers Blog)

Gemini does not report token counts for embeddings, so those are estimated at about 4 characters per token.

In [12]:
usage = pd.DataFrame(USAGE.summary()).T
display(usage)
print(f"Total tokens: {int(usage.tokens_in.sum() + usage.tokens_out.sum()):,} | "
      f"estimated cost at paid prices: ${usage.est_cost_usd.sum():.4f}")
usage.to_json("results/part1_usage.json", indent=1)

,model,calls,items,tokens_in,tokens_out,seconds,est_cost_usd
definitions_v1,openai/gpt-oss-120b,2,10,787,555,1.7,0.00045
definitions_v2,openai/gpt-oss-120b,39,195,22548,25568,69.9,0.01872
embed_products,gemini-embedding-001,20,390,25218,0,8.1,0.00378
embed_queries,gemini-embedding-001,1,6,52,0,0.5,0.00001

Total tokens: 74,728 | estimated cost at paid prices: $0.0230

## 8. Saving results
The definitions, both indexes and the result files are committed to the project repository. The live site redeploys from the repository, so it picks them up automatically.

In [13]:
files = ["data/definitions_v2.json", "data/emb_catalogue.json", "data/emb_definitions_v2.json", "results"]
subprocess.run(["git", "add", *files], check=True)
subprocess.run(["git", "commit", "-q", "-m", "Part 1 run: definitions v2, embeddings, hand-check, usage"])
subprocess.run(["git", "pull", "-q", "--rebase"])
r = subprocess.run(["git", "push", "-q"], capture_output=True, text=True)
print("Pushed to GitHub" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])
print(subprocess.run(["git", "log", "--oneline", "-1"], capture_output=True, text=True).stdout)

Pushed to GitHub
0f3527f Part 1 run: definitions v2, embeddings, hand-check, usage

---

# Sahulat Home generative search, Part 2: evaluating retrieval

**Question:** does searching by AI-written utility definitions find the right products more often than ordinary keyword search? And does it keep plain product-name searches working? The best method on dev becomes the live site’s search.

**The comparison ladder** (each step adds one thing):
1. **Keyword**: BM25 over the store's own text, as a typical store search works today
2. **Meaning, catalogue text**: embeddings of the store's own text
3. **Meaning, AI definitions**: embeddings of the utility definitions from Part 1
4. **Hybrid**: keyword and definitions merged with reciprocal rank fusion, the method I planned to use on the live site

Section 8 measures a failure found during development and its fix; section 9 evaluates the page and visit context. The chat assistant is evaluated in Part 3.

**Method.** 114 labelled questions (the Phase 1 cases), split 30% dev and 70% test. The hybrid weights and the "no close match" threshold are tuned on dev only. The test split is then scored once with those settings, so the test numbers are not tuned to the answers. The questions were written by Claude (Anthropic), a different model family from the app's chat model (gpt-oss) and its embedding model (Gemini).

**AI use.** As in Part 1: code written with Claude as a coding assistant; design decisions, runs and observations are mine.

## 1. Setup
Loads the keys, pulls the latest project from GitHub (including Part 1's outputs) and loads the shared search and evaluation code.

In [ ]:
!pip install -q google-genai

import os, sys, json, subprocess, time
import pandas as pd
from google.colab import userdata

os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")
token = userdata.get("GITHUB_TOKEN")
REPO = "/content/data722-generative-search"
url = f"https://x-access-token:{token}@github.com/mahamnalavi/data722-generative-search.git"
if not os.path.exists(REPO):
    r = subprocess.run(["git", "clone", "-q", url, REPO], capture_output=True, text=True)
else:
    r = subprocess.run(["git", "-C", REPO, "pull", "-q"], capture_output=True, text=True)
print("GitHub:", "OK" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])
subprocess.run(["git", "-C", REPO, "config", "user.name", "Maham (Colab run)"])
subprocess.run(["git", "-C", REPO, "config", "user.email", "mahamnalavi@users.noreply.github.com"])
sys.path.insert(0, REPO); os.chdir(REPO)

for f in ["data/emb_catalogue.json", "data/emb_definitions_v2.json", "data/definitions_v2.json"]:
    assert os.path.exists(f), f"{f} is missing: run Notebook 01 first (it saves this file to GitHub)"
from search import pipeline, products_by_id
from search.llm import GeminiEmbedder, USAGE
from search import evaluate as ev
pd.options.display.max_colwidth = 90
os.makedirs("results", exist_ok=True)
by_id = products_by_id()
print("Ready. Default settings:", pipeline.PARAMS)

GitHub: OK
Ready. Default settings: {'rrf_k': 60, 'w_keyword': 1.0, 'w_semantic': 1.0, 'no_match_similarity': 0.6, 'strong_keyword_score': 8.0, 'semantic_pool': 50, 'strip_constraint_words': True, 'ctx_scale': 1.0, 'ctx_depth': 20, 'ctx_k': 10, 'b_page': 0.006, 'b_cat_browsed': 0.003, 'b_type': 0.008, 'b_price': 0.01}

## 2. The test questions
The 114 labelled questions by style and split. Each question lists the products that count as a correct answer. 13 have none, and for those the right behaviour is to say "no close match".

In [ ]:
rows = json.load(open("data/eval_queries.json", encoding="utf-8"))
dev = [r for r in rows if r["split"] == "dev"]
test = [r for r in rows if r["split"] == "test"]
display(pd.crosstab(pd.Series([r["style"] for r in rows], name="style"), pd.Series([r["split"] for r in rows], name="split"), margins=True))
examples = pd.DataFrame(rows).groupby("style").head(2)[["qid", "style", "query", "relevant_ids", "note"]]
display(examples)

split       dev  test  All
style
constraint    4     9   13
name          7    17   24
no_match      4     9   13
precise      10    22   32
trap          1     2    3
urdu          4     9   13
vague         5    11   16
All          35    79  114

,qid,style,query,relevant_ids,note
0,Q001,name,aluminium pressure cooker,"[KIT-020, KIT-021, KIT-022]",generated from catalogue title
1,Q002,name,cast iron tawa,"[KIT-015, KIT-016, KIT-017]",generated from catalogue title
24,Q025,precise,something to separate egg whites from yolks,"[KIT-001, KIT-002]",
25,Q026,precise,slice potatoes really thin and even for chips,"[KIT-003, KIT-004]",
56,Q057,vague,my rotis go cold before everyone sits down to eat,"[KIT-043, KIT-044]",
57,Q058,vague,the back corners of my kitchen cabinet are wasted,"[ORG-005, ORG-006, ORG-038]",
72,Q073,constraint,light for load shedding under Rs 1500,[TOL-027],
73,Q074,constraint,pressure cooker under 5000,[KIT-022],
85,Q086,urdu,pyaz barik katne wali cheez,"[KIT-056, KIT-057, KIT-003, KIT-004]",
86,Q087,urdu,anday ki zardi alag karne wala,"[KIT-001, KIT-002]",
98,Q099,no_match,refrigerator,[],out of catalogue
99,Q100,no_match,split air conditioner 1.5 ton,[],out of catalogue
111,Q112,trap,separator for my clothes in the drawer,"[ORG-003, ORG-004, ORG-043]",'separator' should not pull in the egg separator
112,Q113,trap,a stand for my plants,[FUR-027],many products are 'stands'

**Note:** The 114 questions cover seven styles, from exact product names to vague needs, Roman Urdu, budget limits, “trap” wording and products the store doesn’t sell. The 35/79 dev/test split means all tuning happens on dev, and test is scored once. The questions were written by Claude, a different model family from the one the app uses. Claude also helped build the search, though, so the questions may suit it better than real shoppers’ wording would.

## 3. Query embeddings
Every question is embedded once, exactly as the live site does it (budget and stock words removed, lower-case). The vectors are saved, so re-running this notebook does not use more Gemini quota.

In [ ]:
VEC_FILE = "results/query_vectors.json"
if os.path.exists(VEC_FILE):
    qvecs = json.load(open(VEC_FILE))
    print(f"Loaded {len(qvecs)} saved query fingerprints")
else:
    emb = GeminiEmbedder()
    texts = [ev.query_text_for_embedding(r["query"]) for r in rows]
    vecs = emb.embed(texts, kind="query", task="embed_eval_queries")
    qvecs = {r["qid"]: v for r, v in zip(rows, vecs)}
    json.dump(qvecs, open(VEC_FILE, "w"))
    print(f"Embedded {len(qvecs)} questions")

Loaded 114 saved query fingerprints

## 4. The ladder on dev, before tuning
All four methods on the 35 dev questions with default settings, to see where each one starts.

In [ ]:
MODES = ["keyword", "semantic_catalogue", "semantic_definitions", "hybrid"]
def ladder(rows_, params_by_mode):
    table, styles, runs_all = {}, {}, {}
    for mode in MODES:
        runs = ev.run_queries(rows_, mode, qvecs, params=params_by_mode.get(mode))
        runs_all[mode] = runs
        table[mode] = ev.metrics(rows_, runs)
        styles[mode] = ev.hit_by_style(rows_, runs, k=5)
    return pd.DataFrame(table).T, pd.DataFrame(styles).T, runs_all

dev_table, dev_styles, _ = ladder(dev, {})
display(dev_table[["hit@1", "hit@5", "hit@10", "mrr", "correct_no_match", "false_no_match", "confidently_wrong", "constraint_violations"]])
print("Hit@5 by question style (dev):"); display(dev_styles)

,hit@1,hit@5,hit@10,mrr,correct_no_match,false_no_match,confidently_wrong,constraint_violations
keyword,0.548,0.645,0.677,0.586,0.75,0.129,0.314,0/17
semantic_catalogue,0.871,1.0,1.0,0.908,0.5,0.032,0.143,0/30
semantic_definitions,0.903,1.0,1.0,0.932,0.5,0.0,0.143,0/30
hybrid,0.677,0.871,1.0,0.79,0.5,0.0,0.343,0/30

Hit@5 by question style (dev):

                      constraint  name  precise  trap  urdu  vague
keyword                     0.75   1.0      0.4   1.0   0.5    0.6
semantic_catalogue          1.00   1.0      1.0   1.0   1.0    1.0
semantic_definitions        1.00   1.0      1.0   1.0   1.0    1.0
hybrid                      1.00   1.0      0.7   1.0   1.0    0.8

**Observations:** With default settings on the 35 dev questions (31 the store can answer, 4 it can’t), keyword search has no correct product in the top 10 for about a third of the answerable questions (Hit@10 0.68). It does well on exact names (Hit@5 1.0) but poorly on described needs (precise 0.4, Roman Urdu 0.5, vague 0.6), the gap this project is meant to close. Both meaning-based methods find a correct product in the top 5 for every answerable dev question. Searching the AI definitions is slightly better than searching the store’s own text at putting the right product first (Hit@1 0.90 vs 0.87, one question’s difference), so on dev the definitions add only a little.

The hybrid, with its default equal weights, did worse than meaning search alone (Hit@5 0.87, Hit@1 0.68). It also had the highest confidently-wrong rate (0.34): keyword matches on words shared with unrelated products pull wrong products up the list. This is why in the next section i.e. section 5, we tune the weights. No method broke a budget or stock limit (0 violations), because those are applied as hard filters, not left to the ranking.

## 5. Tuning on dev
1. **Hybrid weights:** how much the meaning-based list counts against the keyword list, chosen by best dev Hit@5.
2. **"No close match" threshold**, for each meaning-based method: the similarity below which the system says nothing fits, chosen by the best balance between catching true no-match questions and not wrongly flagging answerable ones.

Caveat: dev contains only 4 no-match questions, so the threshold is a rough estimate.

In [ ]:
rrf_best, rrf_table = ev.tune_rrf(dev, qvecs)
print("Hybrid weights chosen on dev:", rrf_best)
display(pd.DataFrame(rrf_table).sort_values(["hit@5", "mrr"], ascending=False).head(6))

tuned = {"keyword": {}}
for mode in ["semantic_catalogue", "semantic_definitions", "hybrid"]:
    base = rrf_best if mode == "hybrid" else {}
    nm_best, nm_table = ev.tune_no_match(dev, qvecs, mode=mode, params=base)
    tuned[mode] = {**base, **nm_best}
    print(f"{mode}: no-match threshold {nm_best['no_match_similarity']}, strong keyword score {nm_best['strong_keyword_score']}")
json.dump(tuned, open("results/tuned_params.json", "w"), indent=1)

Hybrid weights chosen on dev: {'rrf_k': 10, 'w_semantic': 3.0, 'w_keyword': 1.0}

   rrf_k  w_semantic  w_keyword  hit@5    mrr  hit@1
4     10         3.0        1.0  0.935  0.897  0.839
3     10         2.0        1.0  0.935  0.859  0.774
2     10         1.5        1.0  0.935  0.851  0.774
9     60         3.0        1.0  0.903  0.859  0.806
1     10         1.0        1.0  0.903  0.809  0.710
8     60         2.0        1.0  0.871  0.840  0.774

semantic_catalogue: no-match threshold 0.59, strong keyword score 6.0
semantic_definitions: no-match threshold 0.6, strong keyword score 6.0
hybrid: no-match threshold 0.6, strong keyword score 6.0

**Observation:** Tuning on dev chose rrf_k = 10 and a weight of 3 for the meaning-based list against 1 for keyword. A small rrf_k makes the top few places in each list count much more than lower ones, and the weight of 3 means meaning search mostly sets the order, with keyword matches as a tie-breaker. This raised the hybrid from Hit@5 0.87 to 0.94 and Hit@1 from 0.68 to 0.84 on dev. It is still slightly behind meaning search alone on dev (Hit@5 1.0, Hit@1 0.90), so the hybrid has to earn its place on test, mainly on name searches and on not being confidently wrong.

The “no close match” threshold came out at 0.60 for the definitions and the hybrid (0.59 for the catalogue text). A keyword score of 6.0 or more counts as a confident name match. With only 4 no-match questions in dev, these values are a rough estimate.

## 6. Results on test (scored once)
The 79 test questions, scored with the settings chosen on dev. These are the reported numbers.

In [ ]:
test_table, test_styles, test_runs = ladder(test, tuned)
cols = ["hit@1", "hit@5", "hit@10", "mrr", "correct_no_match", "false_no_match", "confidently_wrong", "constraint_violations", "avg_ms"]
display(test_table[cols])
print("Hit@5 by question style (test):"); display(test_styles)

miss = ev.keyword_miss_rate(test, test_runs["keyword"])
print(f"Keyword miss rate (Phase 1 problem measure): {miss['utility_queries_only']:.0%} of described-need questions "
      f"and {miss['all_answerable']:.0%} of all answerable questions have no correct product in keyword search's top 10.")
name = {m: ev.hit_by_style(test, test_runs[m], k=1).get("name") for m in ["keyword", "hybrid"]}
print(f"Name searches, Hit@1: keyword {name['keyword']:.0%} vs hybrid {name['hybrid']:.0%} "
      f"({'no loss' if name['hybrid'] >= name['keyword'] else 'hybrid is worse on names'})")

,hit@1,hit@5,hit@10,mrr,correct_no_match,false_no_match,confidently_wrong,constraint_violations,avg_ms
keyword,0.514,0.629,0.643,0.562,0.111,0.129,0.418,0/30,0.4
semantic_catalogue,0.914,0.986,1.0,0.948,0.222,0.014,0.152,0/50,11.4
semantic_definitions,1.0,1.0,1.0,1.0,0.333,0.014,0.076,0/50,12.2
hybrid,0.871,1.0,1.0,0.927,0.111,0.014,0.215,0/50,11.8

Hit@5 by question style (test):

                      constraint  name  precise  trap   urdu  vague
keyword                    0.889   1.0    0.227   1.0  0.333  0.818
semantic_catalogue         1.000   1.0    0.955   1.0  1.000  1.000
semantic_definitions       1.000   1.0    1.000   1.0  1.000  1.000
hybrid                     1.000   1.0    1.000   1.0  1.000  1.000

Keyword miss rate (Phase 1 problem measure): 47% of described-need questions and 36% of all answerable questions have no correct product in keyword search's top 10.
Name searches, Hit@1: keyword 100% vs hybrid 100% (no loss)

**Observations:** Keyword search has no correct product in its top 10 for 47% of described-need test questions (36% of all answerable ones). That is the problem this project set out to fix. It handles exact names perfectly but gets only 23% of precise descriptions and 33% of Roman Urdu questions right in the top 5. Meaning search on the AI definitions was the best method on every measure. It put a correct product first for all 70 answerable test questions, against 0.91 for the store’s own text, so the definitions add real value. It also had the lowest confidently-wrong rate (7.6%, against 15% for the store’s text). The hybrid found a correct product in the top 5 every time, but ranked it first less often (0.87). It was confidently wrong more often (21%), because keyword matches on shared words pull wrong products up and override the “no close match” check. Hit@1 of 1.0 is a ceiling, and the questions were written by someone who knew the catalogue, so real shoppers would likely score lower. No method broke a budget or stock limit. Search took about 12 ms, not counting the embedding call.

**Decision:** I switched the live site and the chat from the hybrid to meaning search on the definitions, with keyword search as the backup if Gemini is unavailable. Dev already favoured it (Hit@1 0.90 vs 0.84 for the tuned hybrid, Hit@5 1.0 vs 0.94), but I made the switch after seeing these test results, so the test numbers for the chosen method are slightly optimistic.

## 7. Where the hybrid fails (test)
Every test question the hybrid got wrong (no correct product in its top 5, or a confident wrong answer), with what it showed instead.

In [ ]:
by_q = {r["qid"]: r for r in test}
fails = []
for x in test_runs["hybrid"]:
    q = by_q[x["qid"]]
    rel = set(q["relevant_ids"])
    hit5 = any(i in rel for i in x["ids"][:5])
    wrong_confident = (not x["no_close_match"]) and (q["expects_no_match"] or not hit5)
    if (not q["expects_no_match"] and not hit5) or wrong_confident:
        fails.append({"qid": x["qid"], "style": q["style"], "query": q["query"],
                      "expected": ", ".join(t for t in q["relevant_types"]) or "(no match)",
                      "flagged_no_match": x["no_close_match"], "similarity": x["top_similarity"],
                      "showed (top 3)": " | ".join(by_id[i]["title"][:38] for i in x["ids"][:3])})
fail_df = pd.DataFrame(fails)
print(f"{len(fail_df)} of {len(test)} test questions failed")
display(fail_df)

8 of 79 test questions failed

,qid,style,query,expected,flagged_no_match,similarity,showed (top 3)
0,Q099,no_match,refrigerator,(no match),False,0.6338,"Clear Fridge Organizer Bins, Set of 4 | Egg Holder Drawer for Fridge, 21 Eggs | Over-t..."
1,Q100,no_match,split air conditioner 1.5 ton,(no match),False,0.5464,"Aluminium Step Ladder, 5 Steps | Bookcase, 5 Shelves, 180 cm | Folding Room Divider, 3..."
2,Q102,no_match,prayer mat,(no match),False,0.6576,"Foldable Prayer Chair with Backrest | Silicone Baking Mat, Half-Sheet Size | Floor Cus..."
3,Q103,no_match,mosquito net for a bed,(no match),False,0.6148,"Metal Bunk Bed, Single over Single | Under-Bed Storage Bag with Zip, Set of | Woven Ro..."
4,Q106,no_match,laptop bag,(no match),False,0.5700,"Vacuum Storage Bags, Set of 6 with Han | Bean Bag Cover Only, Large | Adjustable Lapto..."
5,Q107,no_match,scanner for documents,(no match),False,0.6081,"Electronic Wall Scanner, 4-in-1 | Laser Distance Meter, 40 m | Magazine File Holders, ..."
6,Q108,no_match,hair curling tongs,(no match),False,0.6232,"Silicone-Tipped Locking Tongs, Set of | Steel Chimta, Flat 14 inch | Pliers Set, 3 Pi..."
7,Q109,no_match,office chair under Rs 10000,(no match),False,0.6869,"Folding Steel Chair, Padded Seat | Bean Bag Chair, XL, with Filling | Foldable Prayer ..."

**Observations:** 8 of the 79 test questions failed with the hybrid, all of them about things the store doesn’t sell. Every answerable question had a correct product in the top 5. Only 1 of the 9 out-of-catalogue questions (“gas heater for winter”) was flagged “no close match”; the other 8 got ordinary results with no warning. There are three causes. First, for five questions meaning search scored the nearest product above the 0.60 cut-off (“prayer mat” → the prayer chair at 0.66), because out-of-catalogue questions and real matches score in the same range. Second, for two questions (“laptop bag”, “split air conditioner 1.5 ton”) the similarity was below 0.60, but a shared word or number gave a keyword score over 6.0, which my rule treats as a confident name match. That second cause is specific to the hybrid. Meaning search on the definitions alone has no keyword rule: it failed on 6 of these 9 questions instead of 8, and made no mistakes on answerable ones. This list is part of why I switched (section 6). Third, “office chair under Rs 10000”: the store’s only office chair is over budget, and the other chairs still scored above the cut-off (see the correction below).

**Correction:** The “office chair under Rs 10000” result exposed a bug. The store’s only office chair costs Rs 32,500, so the budget filter correctly removed it, but the “no close match” check still used that chair’s scores, from before filtering. I fixed the check to consider only products that can actually be shown. Because I found this on the test set, I kept the thresholds chosen on dev (0.60 and 6.0). Sections 6 and 7 above already use the fixed check (I re-ran the notebook after fixing it); re-tuning on dev with the fix chose the same thresholds. The table below re-scores dev and test with the old check for comparison.

In [ ]:
# Re-score with the corrected confidence check (only products that pass the budget/stock filter count).
# No new AI calls: it reuses the saved question fingerprints. The original output above is kept.
import importlib, search.pipeline as pl_mod
subprocess.run(["git", "-C", REPO, "pull", "-q"], check=True)
importlib.reload(pl_mod); importlib.reload(ev)

fix2 = []
for split_name, split_rows in (("dev", dev), ("test", test)):
    for label, flag in (("before fix", False), ("after fix", True)):
        runs = ev.run_queries(split_rows, "hybrid", qvecs, params={**tuned["hybrid"], "confidence_after_filters": flag})
        m = ev.metrics(split_rows, runs)
        fix2.append({"split": split_name, "version": label, "hit@5": m["hit@5"], "correct_no_match": m["correct_no_match"],
                     "false_no_match": m["false_no_match"], "confidently_wrong": m["confidently_wrong"]})
        if split_name == "test" and flag:
            after_runs = {x["qid"]: x for x in runs}
display(pd.DataFrame(fix2))

print("The 8 failed test questions, after the fix:")
display(pd.DataFrame([{"qid": f["qid"], "query": f["query"], "flagged before": f["flagged_no_match"],
                       "flagged after": after_runs[f["qid"]]["no_close_match"],
                       "best similarity, all products": f["similarity"],
                       "best similarity, products that can be shown": after_runs[f["qid"]]["top_similarity_shown"]}
                      for f in fails]))

json.dump(fix2, open("results/part2_confidence_fix_before_after.json", "w"), indent=1)
subprocess.run(["git", "add", "results/part2_confidence_fix_before_after.json"], check=True)
subprocess.run(["git", "commit", "-q", "-m", "Part 2: confidence check after filters, before/after"])
subprocess.run(["git", "pull", "-q", "--rebase"])
r = subprocess.run(["git", "push", "-q"], capture_output=True, text=True)
print("Pushed to GitHub" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])

,split,version,hit@5,correct_no_match,false_no_match,confidently_wrong
0,dev,before fix,0.935,0.500,0.000,0.200
1,dev,after fix,0.935,0.500,0.000,0.200
2,test,before fix,1.000,0.111,0.014,0.215
3,test,after fix,1.000,0.111,0.014,0.215

The 8 failed test questions, after the fix:

,qid,query,flagged before,flagged after,"best similarity, all products","best similarity, products that can be shown"
0,Q099,refrigerator,False,False,0.6338,0.6338
1,Q100,split air conditioner 1.5 ton,False,False,0.5464,0.5464
2,Q102,prayer mat,False,False,0.6576,0.6576
3,Q103,mosquito net for a bed,False,False,0.6148,0.6148
4,Q106,laptop bag,False,False,0.5700,0.5700
5,Q107,scanner for documents,False,False,0.6081,0.6081
6,Q108,hair curling tongs,False,False,0.6232,0.6232
7,Q109,office chair under Rs 10000,False,False,0.6869,0.6241

Pushed to GitHub

**Observations on the correction:** The fix changed no score on dev or test: every rate is the same before and after. The office chair question shows why. With the Rs 32,500 office chair removed, the best similarity among the products that can be shown fell from 0.687 to 0.624, but the remaining chairs (a folding steel chair, a prayer chair) are still close enough in meaning to clear the 0.60 cut-off. So this question turned out to be the same problem as the other five: out-of-catalogue questions and real matches score in the same range. The fix is still correct, because the system should never feel confident because of a product it is about to hide. It just didn’t change the outcome for this test set. A fairer fix for the underlying problem would be a check of whether the remaining products do the job the shopper asked for, not only how similar they are. The chat assistant in Part 3 does that.

## 8. A failure found during development: budget words read as product words
While testing on 24 October, "emergency light under 2000" returned "Under-Bed Storage Bag": keyword matching treated "under" as a product word. On 30 October a second form appeared in chat follow-ups, where a repeated budget phrase left "under" behind again.

**Fix:** the rule-based reader now removes every budget and stock phrase before matching, and applies the limits as hard filters instead.

Below, the same queries run with the old behaviour (`strip_constraint_words=False`) and with the fix. The set is all 16 questions that state a budget or stock limit, dev and test together: this is a bug fix, not a tuned setting, so no split is needed.

In [ ]:
lim = [r for r in rows if r["expected_max_price"] is not None or r["expected_in_stock"]]
RAW_FILE = "results/query_vectors_raw.json"
if os.path.exists(RAW_FILE):
    raw_vecs = json.load(open(RAW_FILE))
else:
    emb = GeminiEmbedder()
    raw_vecs = dict(zip([r["qid"] for r in lim],
                        emb.embed([r["query"].strip().lower() for r in lim], kind="query", task="embed_eval_queries_raw")))
    json.dump(raw_vecs, open(RAW_FILE, "w"))

fix_rows = []
for mode in ["keyword", "hybrid", "semantic_definitions"]:
    p = tuned[mode]
    before = ev.run_queries(lim, mode, raw_vecs, params={**p, "strip_constraint_words": False})
    after = ev.run_queries(lim, mode, qvecs, params=p)
    for label, runs in (("before fix", before), ("after fix", after)):
        m = ev.metrics(lim, runs)
        fix_rows.append({"method": mode, "version": label, "hit@1": m["hit@1"], "hit@5": m["hit@5"],
                         "confidently_wrong": m["confidently_wrong"], "constraint_violations": m["constraint_violations"]})
fix_table = pd.DataFrame(fix_rows)
display(fix_table)

example = next(r for r in lim if r["query"].startswith("light for load shedding"))
print(f'Example, keyword search for "{example["query"]}":')
for label, prm in (("before fix", {"strip_constraint_words": False}), ("after fix", {})):
    res = pipeline.run(example["query"], mode="keyword", params=prm, k=3)
    print(f"  {label}: " + (" | ".join(x["title"] for x in res["results"]) or "(nothing)"))

,method,version,hit@1,hit@5,confidently_wrong,constraint_violations
0,keyword,before fix,0.769,0.846,0.250,0/59
1,keyword,after fix,0.769,0.846,0.250,0/47
2,hybrid,before fix,1.000,1.000,0.188,0/80
3,hybrid,after fix,0.923,1.000,0.250,0/80
4,semantic_definitions,before fix,1.000,1.000,0.188,0/80
5,semantic_definitions,after fix,1.000,1.000,0.188,0/80

Example, keyword search for "light for load shedding under Rs 1500":
  before fix: Under-Cabinet Jar Opener, Adjustable | Telescopic Magnetic Pickup Tool with LED
  after fix: Telescopic Magnetic Pickup Tool with LED

**Observations:** On the 16 questions that state a budget or stock limit, the fix leaves keyword search’s scores unchanged (Hit@1 0.77, Hit@5 0.85), because in most of these questions the correct product was already first. The difference is in what appears next to it. Before the fix, 15 of the 39 products keyword search showed in its top 3 were unwanted “Under-…” items (under-bed bags, an under-cabinet jar opener, an under-desk footrest), matched only on the word “under”. After the fix, 2 of 31 remain, both fair word matches (“desk”, “bag”). The example shows this: “light for load shedding under Rs 1500” returned a jar opener before the fix. Even after it, keyword search still can’t find the rechargeable bulb, because “load shedding” appears nowhere in the store’s text; that is the gap meaning search closes. None of my Phase 1 metrics capture junk in places 2 and 3, which is a limitation of how I measured. For the hybrid, the fix cost one question its correct first result (Hit@1 1.00 → 0.92), and confidently-wrong rose by one. Embedding the full question, budget words included, happened to rank one product better there (“light for load shedding under Rs 1500”: after the fix, the hybrid’s keyword half pulled an LED pickup tool above the rechargeable bulb). I kept the fix anyway: the limits are applied as hard filters in both versions, so budget words add nothing a shopper needs, and removing them is the only version that works the same way for every method.

The definitions method, which the live site now uses, scores the same before and after the fix (Hit@1 1.00, Hit@5 1.00): embedding the question with or without “under Rs 1500” put the same correct product first every time, so meaning search is not thrown by budget words the way keyword matching is. The fix still matters for it, because the same budget reader supplies the hard limits, and the keyword backup takes over when Gemini is unavailable. Its confidently-wrong rate here (0.19) comes entirely from the 3 questions in this set the store can’t answer within the limits (an office chair under Rs 10,000, a bean bag with filling under Rs 5,000, a headlamp in stock): none were flagged “no close match”, the same weakness as in section 7.

## 9. Page and visit context
The search receives a short summary of the shopper's visit: the category page it was opened from, the categories and product types browsed, and the price range viewed. It uses this as a small re-ranking boost that runs **after** the budget and stock filter, so it can never bring back an excluded item. It can only move results a few places within the top 20, so it never overrides what the shopper typed.

**How it is tested.** For each answerable question there are three versions:
- **no context**
- **a helpful session**: opened from the right category page, browsing that category, prices around one correct product
- **a misleading session**: opened from a different category, browsing and pricing there

The weights for each part (page, product types viewed, price) are tuned on dev to help when the context is right without losing correct results when it is wrong.

**Caveat.** These sessions are synthetic. They can only show the personalisation the generator built in, so this measures whether context helps or harms retrieval, not whether real shoppers benefit.

In [ ]:
from search import load_catalogue
catalogue = load_catalogue()
LIVE_MODE = pipeline.LIVE_MODE   # "semantic_definitions": the method the live site now uses (decision 35)
ctx_best, ctx_table = ev.tune_context(dev, qvecs, catalogue, tuned[LIVE_MODE], mode=LIVE_MODE)
live = {**tuned[LIVE_MODE], **ctx_best}
print("Context weights chosen on dev:", {k: ctx_best[k] for k in ("b_page", "b_type", "b_price")})
display(pd.DataFrame(ctx_table).sort_values("objective", ascending=False).head(6)[
    ["b_page", "b_type", "b_price", "objective", "hit@1_helpful", "hit@5_misleading", "price_variant_first_helpful", "context_override_errors"]])

Context weights chosen on dev: {'b_page': 0.003, 'b_type': 0.0, 'b_price': 0.01}

,b_page,b_type,b_price,objective,hit@1_helpful,hit@5_misleading,price_variant_first_helpful,context_override_errors
7,0.003,0.000,0.01,2.315,0.903,1.0,0.824,0/31
9,0.003,0.004,0.01,2.315,0.903,1.0,0.824,0/31
15,0.006,0.004,0.01,2.315,0.903,1.0,0.824,0/31
17,0.006,0.008,0.01,2.315,0.903,1.0,0.824,0/31
13,0.006,0.000,0.01,2.315,0.903,1.0,0.824,0/31
11,0.003,0.008,0.01,2.315,0.903,1.0,0.824,0/31

In [ ]:
ctx_runs = ev.run_with_context(test, LIVE_MODE, qvecs, catalogue, params=live)
ctx_m = ev.context_metrics(test, ctx_runs, catalogue)
display(pd.DataFrame({kind: {"Hit@1": ctx_m[f"hit@1_{kind}"], "Hit@5": ctx_m[f"hit@5_{kind}"]}
                      for kind in ("none", "helpful", "misleading")}).T.rename(index={"none": "no context", "helpful": "helpful session", "misleading": "misleading session"}))
print(f"Context-override errors (a correct top-5 result lost because of a misleading session): {ctx_m['context_override_errors']}")
print(f"Price personalisation ({ctx_m['price_variant_queries']} questions with several price variants): the variant matching the "
      f"visit's price range comes first {ctx_m['price_variant_first_none']:.0%} of the time without context, "
      f"{ctx_m['price_variant_first_helpful']:.0%} with it")

                    Hit@1  Hit@5
no context          1.000    1.0
helpful session     0.957    1.0
misleading session  0.914    1.0

Context-override errors (a correct top-5 result lost because of a misleading session): 0/70
Price personalisation (36 questions with several price variants): the variant matching the visit's price range comes first 36% of the time without context, 81% with it

**Page context on ambiguous words.** The same word means different products on different pages: "box", "stand" and "cutter". Each is searched without page context and as if opened from each page. This checks whether a product that fits that page appears in the top 3.

In [ ]:
AMB_FILE = "results/query_vectors_ambiguous.json"
words = [w for w, _ in ev.AMBIGUOUS]
if os.path.exists(AMB_FILE):
    amb_vecs = json.load(open(AMB_FILE))
else:
    amb_vecs = dict(zip(words, GeminiEmbedder().embed(words, kind="query", task="embed_ambiguous")))
    json.dump(amb_vecs, open(AMB_FILE, "w"))
amb = pd.DataFrame(ev.page_context_check(amb_vecs, catalogue, live, mode=LIVE_MODE))
display(amb)
if live["b_page"] == 0:
    print("Dev tuning set the page weight to 0. For comparison, the same check with the default page weight:")
    display(pd.DataFrame(ev.page_context_check(amb_vecs, catalogue, {**live, "b_page": 0.006, "b_cat_browsed": 0.003}, mode=LIVE_MODE)))
tuned["live"] = live
json.dump(tuned, open("results/tuned_params.json", "w"), indent=1)

,word,page,fits page in top 3: without page,top result: without page,fits page in top 3: with page,top result: with page
0,box,Organizers,True,"Cable Management Box, Large",True,"Cable Management Box, Large"
1,box,Tools,False,"Cable Management Box, Large",False,"Cable Management Box, Large"
2,box,Kitchenware,True,"Cable Management Box, Large",True,"Cable Management Box, Large"
3,stand,Furniture,True,"Plant Stand, 3 Tiers, Metal",True,"Plant Stand, 3 Tiers, Metal"
4,stand,Organizers,True,"Plant Stand, 3 Tiers, Metal",True,"Plant Stand, 3 Tiers, Metal"
5,cutter,Kitchenware,True,8-Blade Apple Slicer and Corer,True,8-Blade Apple Slicer and Corer
6,cutter,Tools,True,8-Blade Apple Slicer and Corer,True,8-Blade Apple Slicer and Corer

In [ ]:
# Probe: how strong must the page boost be before it changes ambiguous words? (no AI calls; chosen on dev, not test)
probe = []
for bp in (0.003, 0.006, 0.012, 0.02):
    p = {**live, "b_page": bp, "b_cat_browsed": bp / 2}
    amb_p = pd.DataFrame(ev.page_context_check(amb_vecs, catalogue, p, mode=LIVE_MODE))
    m = ev.context_metrics(dev, ev.run_with_context(dev, LIVE_MODE, qvecs, catalogue, params=p), catalogue)
    probe.append({"page weight": bp,
                  "ambiguous words: fits the page in top 3 (of 7)": int(amb_p["fits page in top 3: with page"].sum()),
                  "dev Hit@1, helpful": m["hit@1_helpful"], "dev Hit@1, misleading": m["hit@1_misleading"],
                  "dev Hit@5, misleading": m["hit@5_misleading"], "dev context-override errors": m["context_override_errors"]})
display(pd.DataFrame(probe))

,page weight,ambiguous words: fits the page in top 3 (of 7),"dev Hit@1, helpful","dev Hit@1, misleading","dev Hit@5, misleading",dev context-override errors
0,0.003,6,0.903,0.839,1.000,0/31
1,0.006,6,0.903,0.839,1.000,0/31
2,0.012,6,0.903,0.774,0.968,1/31
3,0.020,7,0.903,0.742,0.968,1/31

**Observations:** On dev, every combination of page and price weights scored the same, so the tuning chose the weakest: page 0.003, product types viewed 0, price 0.010. On test, context never cost a correct result: Hit@5 stayed at 1.0 with no context, a helpful session and a misleading one, so there were 0 context-override errors in 70 questions (a Phase 1 metric). Price personalisation clearly works: for the 36 questions where the product comes in several price variants, the variant matching the visit’s price range came first 81% of the time with context, against 36% without. The cost is in first places: Hit@1 fell from 1.00 to 0.96 with a helpful session (3 questions) and 0.91 with a misleading one (6 questions). I checked each case: the cause is that the price boost is larger than the gap between first and second place, and it lifts the closest-price variant of any product type with several variants, not only the one the shopper asked for. Turning off the page boost restores none of them; turning off the price boost restores all 9.

Page context had no visible effect on the ambiguous words. For 6 of the 7 word-and-page pairs, meaning search already had a product fitting that page in the top 3 without being told the page. The exception is “box” searched from the Tools page, which never showed the toolbox. A probe on dev showed that only a much stronger page weight (0.020) fixes that case, and it then lost a correct result in a misleading session and lowered Hit@1 with misleading context from 0.84 to 0.74. My Phase 1 design says context must never override what the shopper typed, so I kept the weak setting. Page context is therefore safe but weak, and making it stronger without letting it override the shopper is future work. These sessions are synthetic, so this shows whether context helps or harms retrieval, not whether real shoppers benefit.

## 10. Tokens and cost
The Gemini calls made in this part. Scoring itself runs locally and costs nothing.

In [ ]:
usage = pd.DataFrame(USAGE.summary()).T
display(usage if len(usage) else "No AI calls this run (query fingerprints were loaded from the saved file).")

,model,calls,items,tokens_in,tokens_out,seconds,est_cost_usd
embed_eval_queries,gemini-embedding-001,6,114,810,0,3.6,0.00012
embed_eval_queries_raw,gemini-embedding-001,1,16,119,0,0.6,0.00002
embed_ambiguous,gemini-embedding-001,1,3,3,0,0.3,0.0

**Observations:** This part made only 8 AI calls, all Gemini embeddings: 114 questions, 16 questions with their budget words kept for the section 8 comparison, and 3 ambiguous words. That’s 932 tokens in total, about \$0.00014 at paid prices, and \$0 on the free tier. All scoring and tuning ran locally on saved fingerprints, so re-running this notebook costs nothing. A question averages about 7 tokens, so each live search costs about one millionth of a dollar for its embedding call.

## 11. Saving results
The tables, per-question results and tuned settings (including the context weights the live site will use) are committed to the project repository.

In [ ]:
test_table.to_json("results/part2_test_metrics.json", indent=1)
dev_table.to_json("results/part2_dev_metrics.json", indent=1)
test_styles.to_json("results/part2_test_hit5_by_style.json", indent=1)
rows_out = []
for mode, runs in test_runs.items():
    for x in runs:
        rows_out.append({"qid": x["qid"], "mode": mode, "query": by_q[x["qid"]]["query"], "style": by_q[x["qid"]]["style"],
                         "top5": " | ".join(x["ids"][:5]), "no_close_match": x["no_close_match"], "top_similarity": x["top_similarity"]})
pd.DataFrame(rows_out).to_csv("results/part2_test_per_query.csv", index=False)
json.dump({"keyword_miss_rate": miss, "name_hit1": name}, open("results/part2_headlines.json", "w"), indent=1)
fix_table.to_json("results/part2_budget_fix_before_after.json", indent=1)
json.dump(ctx_m, open("results/part2_context_test.json", "w"), indent=1)
amb.to_json("results/part2_page_context_ambiguous.json", indent=1)

pd.DataFrame(probe).to_json("results/part2_page_weight_probe.json", indent=1)
subprocess.run(["git", "add", "results"], check=True)
subprocess.run(["git", "commit", "-q", "-m", "Part 2 run: retrieval ladder, budget-word fix, context evaluation, tuned settings"])
subprocess.run(["git", "pull", "-q", "--rebase"])
r = subprocess.run(["git", "push", "-q"], capture_output=True, text=True)
print("Pushed to GitHub" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])

Pushed to GitHub

---

*(Added when the five notebooks were combined; not part of the original runs.)*

**Part 3a is the first run of the chat evaluation, before the fixes.** It is kept as it came out of Colab. The session ended before its hand-check, cost and saving cells ran, so those three empty code cells are left out here. Its raw answer files were lost with that session; the numbers used for the comparison in Part 3 section 6 are read from the outputs below (`results/part3_first_run.json`).

# Sahulat Home generative search, Part 3: the "Ask Sahulat" chat, judged


Part 2 measured retrieval: does the right product come back? This part measures the **generation** side of the RAG system, the "Ask Sahulat" chat assistant on the live site. For each message, the assistant:
1. reads budget and stock limits by rules;
2. retrieves candidates with the same search as the search bar (meaning search on the AI definitions, chosen in Part 2), page and visit context included;
3. asks `gpt-oss-120b` (on Groq) to pick up to three candidates and explain each, in the shopper's language, or to say honestly that nothing fits;
4. checks the answer in code: products the search did not return are dropped, limits are re-checked, and reasons are scanned for unsupported claims.

**Questions:**
- Does the chat pick the right product more often than the search bar's first result?
- Does it stay grounded and within limits, and say "no close match" when it should?
- What does an independent judge (Gemini, a different company) think of its answers and of the Part 1 definitions, and how far can that judge be trusted, measured against my own checks?
- What does a chat turn cost?

**Method.** All 79 test questions, single turn and without context, so the numbers are comparable with Part 2. Then scripted multi-turn conversations with page context. Then the judge, and my hand-check of 16 judge verdicts (20%).

**AI use.** Code written with Claude (Anthropic) as a coding assistant. Design decisions, runs, hand-checks and observations are mine.

## 1. Setup
Loads the keys, pulls the project (including the outputs of Parts 1 and 2) and the settings tuned on dev, which are the same ones the live site uses.

In [1]:
!pip install -q groq google-genai

import os, sys, json, random, subprocess, time
import pandas as pd
from google.colab import userdata

os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")
os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")
token = userdata.get("GITHUB_TOKEN")
REPO = "/content/data722-generative-search"
url = f"https://x-access-token:{token}@github.com/mahamnalavi/data722-generative-search.git"
if not os.path.exists(REPO):
    r = subprocess.run(["git", "clone", "-q", url, REPO], capture_output=True, text=True)
else:
    r = subprocess.run(["git", "-C", REPO, "pull", "-q"], capture_output=True, text=True)
print("GitHub:", "OK" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])
subprocess.run(["git", "-C", REPO, "config", "user.name", "Maham (Colab run)"])
subprocess.run(["git", "-C", REPO, "config", "user.email", "mahamnalavi@users.noreply.github.com"])
sys.path.insert(0, REPO); os.chdir(REPO)

for f in ["data/definitions_v2.json", "data/emb_definitions_v2.json", "results/query_vectors.json", "results/tuned_params.json"]:
    assert os.path.exists(f), f"{f} is missing: run Notebooks 01 and 02 first"
from search import chat, pipeline, products_by_id, load_catalogue
from search import evaluate as ev
from search.llm import GroqChat, GeminiEmbedder, USAGE, PRICES
from search.judge import GeminiJudge, run_batches, CHAT_RUBRIC, DEF_RUBRIC
pd.options.display.max_colwidth = 90

rows = json.load(open("data/eval_queries.json", encoding="utf-8"))
test = [r for r in rows if r["split"] == "test"]
by_q = {r["qid"]: r for r in rows}
by_id = products_by_id()
catalogue = load_catalogue()
live = json.load(open("results/tuned_params.json"))["live"]
qvecs = json.load(open("results/query_vectors.json"))
vec_by_text = {ev.query_text_for_embedding(r["query"]): qvecs[r["qid"]] for r in rows}
emb = GeminiEmbedder()
def embed_fn(texts):
    """Re-use the Part 2 query embeddings; embed only texts not seen before (multi-turn demos)."""
    missing = [t for t in texts if t not in vec_by_text]
    if missing:
        vec_by_text.update(zip(missing, emb.embed(missing, kind="query", task="embed_chat_queries")))
    return [vec_by_text[t] for t in texts]
llm = GroqChat()
print(f"Ready: {len(test)} test questions; live settings loaded")

GitHub: OK
Ready: 79 test questions; live settings loaded

## 2. The context design
This is what the chat model sees for every message. The system prompt sets the rules: candidates only, at most three, reasons from the facts, honest "no close match", the shopper's language, and context as a soft hint. The message then gives the conversation, the limits, a short summary of the page and visit, and the candidate products with their facts and AI-written uses from Part 1.

Below are the rules, and the complete message for one test question.

In [2]:
print(chat.SYSTEM_PROMPT)
ex = next(r for r in test if r["style"] == "constraint")
msgs = [{"role": "user", "content": ex["query"]}]
cons = chat.merged_constraints([ex["query"]])
cands = []
for t, v in zip(chat.retrieval_texts([ex["query"]]), embed_fn([ev.query_text_for_embedding(ex["query"])])):
    cands += [p["product_id"] for p in pipeline.run(t, mode=pipeline.LIVE_MODE, query_vec=v, k=6, params=live, constraints=cons)["results"]]
print("\n----- message for:", ex["query"], "-----\n")
print(chat.build_user_prompt(msgs, cons, {"page_category": "Kitchenware", "categories_browsed": {"Kitchenware": 2},
                                          "product_types_viewed": ["tawa"], "price_band": {"min": 1850, "max": 3290, "median": 2350}}, cands))

You are "Ask Sahulat", the shopping assistant of Sahulat Home, an online household-goods store in Pakistan.

Rules:
1. Recommend ONLY products listed under CANDIDATES, by their id. Never invent products, prices, stock or features.
2. Pick at most 3, best first. For each, give one short reason that follows from its listed facts or uses.
3. Candidates already meet the stated budget and stock limits. If the shopper asks for cheaper, prefer lower prices.
4. If no candidate does what the shopper needs, set "no_match" to true, say so plainly, and suggest different words to search. Never force a product.
5. Reply in the language of the shopper's last message: English, Urdu script, or Roman Urdu.
6. PAGE and VISIT are soft hints for unclear requests only. The shopper's own words always win.
7. Keep "reply" under 60 words. No marketing words.

Return JSON only: {"reply": "...", "picks": [{"id": "...", "why": "..."}], "no_match": false}

----- message for: pressure cooker under 5000 -----

CONVERSATION (latest last):
Shopper: pressure cooker under 5000

LIMITS: max price Rs 5,000
PAGE: opened from the Kitchenware page | VISIT: browsed Kitchenware (2 pages); viewed tawa; prices viewed Rs 1,850 to Rs 3,290

CANDIDATES:
- KIT-022 | Mini Pressure Cooker, 3 Litre | Rs 4,350 | in stock | uses: quickly cooking small portions of dal; making single‑serve soups; softening vegetables; preparing small batches of rice | specs: capacity: 3 L; material: Hard aluminium; safety: Gasket release window
- KIT-053 | Glass Boil-Over Preventer Disc | Rs 450 | in stock | uses: prevent boil‑over while cooking rice; keep stovetop clean; reduce mess from sauces | specs: material: Heat-resistant glass; diameter: 7 cm
- KIT-043 | Insulated Hot Pot Casserole, 2.5 Litre | Rs 1,890 | in stock | uses: keeping soups hot for serving; transporting stews to a gathering; serving hot dishes at a buffet | specs: capacity: 2.5 L; material: Stainless steel inner, PU insulation; lid: Locking
- KIT-005 | Heavy-Duty Zinc Alloy Garlic Press | Rs 1,150 | in stock | uses: pressing garlic cloves into paste; quickly mincing garlic for curries; adding fresh garlic flavor without chopping | specs: material: Zinc alloy; finish: Chrome; length: 18 cm
- KIT-006 | Rocker Garlic Crusher, Stainless Steel | Rs 890 | in stock | uses: crushing garlic cloves into fine pieces; making garlic paste without a board; quickly preparing garlic for sauces | specs: material: Stainless steel; shape: Curved rocker; length: 13 cm
- KIT-019 | Non-Stick Karahi with Glass Lid, 26 cm | Rs 4,250 | in stock | uses: frying vegetables; making curries; stir‑frying meat; cooking eggs | specs: material: Aluminium, non-stick; diameter: 26 cm; lid: Tempered glass

**Observations:** This is the context design at the centre of the chat. The model never searches the catalogue itself: it receives one message built by code, with four parts.

1. The conversation (the last 6 messages).
2. The limits, read by rules, not by the model (“max price Rs 5,000”).
3. The page and visit summary, marked as a soft hint (rule 6). The visit in this example is made up for illustration; section 3 sends no context.
4. The candidates: up to 6 products from the same search the site uses, each with its id, price, stock, specs and the uses from my Part 1 definitions.

The example shows why this order matters. The budget filter runs before the model sees anything, so the Rs 5,950 and Rs 11,900 pressure cookers are not candidates at all. Only the Rs 4,350 mini cooker is, and the model cannot break the budget without inventing a product, which the code would drop (rule 1 and the grounding check). The other five candidates are weaker matches (a boil-over disc, a hot pot, garlic presses, a karahi), because search always fills the list. That tests rule 4: the model should pick only the mini cooker and not force the rest. Giving each product’s uses, not just its specs, lets the model explain a pick in the shopper’s terms (“for small portions of dal”) while staying within the facts. Asking for JSON with product ids, not free text, is what lets the code check every pick.

## 3. The chat on all 79 test questions
Each question is sent as a single message, with no context, using the same code as the live site. Answers are saved as they arrive, so if Colab disconnects, re-running the cell continues where it stopped. The calls are paced to Groq's free limit of 8,000 tokens per minute, so expect 20-25 minutes.

In [3]:
RUNS_FILE = "results/chat_test_runs.json"
runs = json.load(open(RUNS_FILE)) if os.path.exists(RUNS_FILE) else {}
t0 = time.time()
for i, r in enumerate(test, start=1):
    if r["qid"] in runs:
        continue
    res = chat.respond([{"role": "user", "content": r["query"]}], context=None, embed_fn=embed_fn, llm=llm, params=live)
    runs[r["qid"]] = {"reply": res["reply"], "picks": [p["product_id"] for p in res["products"]],
                      "whys": [p["why"] for p in res["products"]], "no_match": res["no_match"],
                      "search_no_close_match": res["search_no_close_match"], **res["diagnostics"]}
    if i % 5 == 0 or i == len(test):
        json.dump(runs, open(RUNS_FILE, "w"), indent=1, ensure_ascii=False)
        print(f"  {len(runs)}/{len(test)} answered ({(time.time() - t0) / 60:.1f} min)")
json.dump(runs, open(RUNS_FILE, "w"), indent=1, ensure_ascii=False)
fallbacks = [q for q, x in runs.items() if x.get("fallback")]
print(f"Done: {len(runs)} answers; chat model unavailable (search results shown instead) for {len(fallbacks)}")

  5/79 answered (0.1 min)
  10/79 answered (1.0 min)
  15/79 answered (2.0 min)
  20/79 answered (2.1 min)
  25/79 answered (3.1 min)
  30/79 answered (4.1 min)
  35/79 answered (4.2 min)
  40/79 answered (5.2 min)
  45/79 answered (6.2 min)
  50/79 answered (7.1 min)
  55/79 answered (7.2 min)
  60/79 answered (8.2 min)
  65/79 answered (9.2 min)
  70/79 answered (9.3 min)
  75/79 answered (10.2 min)
  79/79 answered (11.2 min)
Done: 79 answers; chat model unavailable (search results shown instead) for 0

**Note:** All 79 test questions were answered by the chat model in 11.2 minutes, with no fallbacks. The time is mostly the pacing that keeps the run within Groq’s free limit, not the model itself.

## 4. Automatic scores
The chat's first suggestion compared with the search bar's first result on the same questions, plus the checks done in code: grounding, limits, unsupported claim words and no-match handling.

In [4]:
search_runs = {x["qid"]: x for x in ev.run_queries(test, pipeline.LIVE_MODE, qvecs, params=live)}
def rel(q): return set(by_q[q]["relevant_ids"])
ans = [r["qid"] for r in test if not r["expects_no_match"]]
nom = [r["qid"] for r in test if r["expects_no_match"]]
rate = lambda xs: round(sum(xs) / len(xs), 3) if xs else None

chat_first = {q: bool(runs[q]["picks"]) and runs[q]["picks"][0] in rel(q) for q in ans}
chat_any = {q: any(p in rel(q) for p in runs[q]["picks"]) for q in ans}
search_first = {q: bool(search_runs[q]["ids"]) and search_runs[q]["ids"][0] in rel(q) for q in ans}
search_top3 = {q: any(i in rel(q) for i in search_runs[q]["ids"][:3]) for q in ans}
viol = sum(1 for q in runs for pid in runs[q]["picks"]
           if (by_q[q]["expected_max_price"] is not None and by_id[pid]["price_pkr"] > by_q[q]["expected_max_price"])
           or (by_q[q]["expected_in_stock"] and not by_id[pid]["in_stock"]))
chat_cw = [(not runs[q]["no_match"]) and (q in nom or not runs[q]["picks"] or runs[q]["picks"][0] not in rel(q)) for q in runs]
search_cw = [(not search_runs[q]["no_close_match"]) and (q in nom or not search_runs[q]["ids"] or search_runs[q]["ids"][0] not in rel(q)) for q in runs]

summary = pd.DataFrame({
    "search bar": {"first result correct": rate(list(search_first.values())),
                            "a correct product among the first 3": rate(list(search_top3.values())),
                            "correct 'no close match'": rate([search_runs[q]["no_close_match"] for q in nom]),
                            "wrongly says 'no close match'": rate([search_runs[q]["no_close_match"] for q in ans]),
                            "confidently wrong": rate(search_cw)},
    "Ask Sahulat chat": {"first result correct": rate(list(chat_first.values())),
                         "a correct product among the first 3": rate(list(chat_any.values())),
                         "correct 'no close match'": rate([runs[q]["no_match"] for q in nom]),
                         "wrongly says 'no close match'": rate([runs[q]["no_match"] for q in ans]),
                         "confidently wrong": rate(chat_cw)}})
display(summary)
dropped = sum(len(x["dropped_ids"]) for x in runs.values())
flagged = {q: x["claim_flags"] for q, x in runs.items() if x["claim_flags"]}
n_picks = sum(len(x["picks"]) for x in runs.values())
print(f"Grounding: {dropped} suggested product ids were not among the search candidates and were dropped by code")
print(f"Limits: {viol} of {n_picks} shown picks break the question's budget or stock limit")
print(f"Unsupported claim words in reasons: {len(flagged)} answers flagged {flagged if flagged else ''}")

style_rows = {}
for r in test:
    if r["expects_no_match"]:
        continue
    s = style_rows.setdefault(r["style"], {"search first": [], "chat first": []})
    s["search first"].append(search_first[r["qid"]]); s["chat first"].append(chat_first[r["qid"]])
display(pd.DataFrame({k: {c: rate(v) for c, v in d.items()} for k, d in style_rows.items()}).T)

                                     search bar  Ask Sahulat chat
first result correct                      1.000             0.957
a correct product among the first 3       1.000             0.957
correct 'no close match'                  0.333             0.889
wrongly says 'no close match'             0.014             0.029
confidently wrong                         0.076             0.025

Grounding: 0 suggested product ids were not among the search candidates and were dropped by code
Limits: 0 of 121 shown picks break the question's budget or stock limit
Unsupported claim words in reasons: 7 answers flagged {'Q020': {'ORG-023': ['perfect']}, 'Q040': {'KIT-054': ['perfect']}, 'Q056': {'FUR-020': ['perfect']}, 'Q075': {'KIT-017': ['perfect']}, 'Q080': {'KIT-036': ['perfect']}, 'Q084': {'KIT-028': ['perfect']}, 'Q112': {'ORG-043': ['perfect']}}

            search first  chat first
name                 1.0       0.941
precise              1.0       1.000
vague                1.0       0.909
constraint           1.0       1.000
urdu                 1.0       0.889
trap                 1.0       1.000

**Observations:** The chat’s main gain is honesty about what the store doesn’t sell. On the 9 out-of-catalogue questions, it said “no close match” for 8, against 3 for the search bar alone. Its confidently-wrong rate is a third of the search bar’s (2.5% vs 7.6%). This is the check I said section 7 of Part 2 lacked: the model reads each candidate’s uses and decides whether it does the job, instead of relying on a similarity score. The cost is caution: it put a correct product first for 67 of 70 answerable questions (0.96, against 1.00 for the search bar). Two of those three misses were answerable questions it wrongly called “no close match”. By style, the misses were one name search, one vague and one Roman Urdu question.

The code checks found no grounding failures (0 products outside the search candidates) and no limit violations (0 of 121 picks). But 7 answers used “perfect” in a reason, despite the rule against marketing words. The automatic check flagged all 7, but it only flags; the word would still reach the shopper. Under the CCP’s deceptive-marketing guidelines, that is a claim the store cannot back up. This is a failure of relying on the prompt alone, and it needs a fix in code, not just in the instructions.

## 5. Multi-turn conversations and context
Three scripted conversations, run exactly as the live site runs them:
- **A.** A follow-up that tightens the budget, then adds stock, opened from the Kitchenware page.
- **B.** Roman Urdu, with a "cheaper" follow-up.
- **C.** Opened from the Furniture page while the shopper describes a plumbing problem. Their own words should win over the page.

In [5]:
def converse(turns, context):
    msgs = []
    for text in turns:
        msgs.append({"role": "user", "content": text})
        res = chat.respond(msgs, context=context, embed_fn=embed_fn, llm=llm, params=live)
        msgs.append({"role": "assistant", "content": res["reply"]})
        shown = "; ".join(f'{p["title"]} (Rs {p["price_pkr"]:,}, {"in stock" if p["in_stock"] else "out of stock"})' for p in res["products"]) or "(none)"
        print(f"SHOPPER: {text}\nASSISTANT: {res['reply']}\n   shown: {shown}\n   limits: {res['constraints']}\n")

kitchen = {"page_category": "Kitchenware", "categories_browsed": {"Kitchenware": 3}, "product_types_viewed": ["karahi", "tawa"],
           "price_band": {"min": 1850, "max": 4250, "median": 2350}}
furniture = {"page_category": "Furniture", "categories_browsed": {"Furniture": 4}, "product_types_viewed": ["sofa_cum_bed"],
             "price_band": {"min": 20000, "max": 64500, "median": 46500}}
print("=== A ==="); converse(["I need something for making rotis at home", "something cheaper, under 2000", "only ones in stock please"], kitchen)
print("=== B ==="); converse(["bijli chali jaye to roshni ke liye kuch chahiye", "is se sasta wala?"], None)
print("=== C ==="); converse(["my kitchen sink is blocked, water won't drain"], furniture)

=== A ===
SHOPPER: I need something for making rotis at home
ASSISTANT: Here are suitable items:
   shown: Granite-Coated Flat Tawa, 12 inch, Induction Base (Rs 3,290, in stock); Wooden Chakla Belan Set, 10 inch (Rs 1,290, in stock)
   limits: {'max_price': None, 'in_stock': False}

SHOPPER: something cheaper, under 2000
ASSISTANT: Here are some affordable options for making rotis:
   shown: Wooden Chakla Belan Set, 10 inch (Rs 1,290, in stock); Steel Chimta, Flat 14 inch (Rs 390, in stock); Wooden Hand Churner (Madhani), 45 cm (Rs 650, in stock)
   limits: {'max_price': 2000, 'in_stock': False}

SHOPPER: only ones in stock please
ASSISTANT: Maaf, in items mein roti banane ke liye koi cheez nahi hai. Aap "tawa", "roti maker" ya "chapati press" jaise lafz try karen.
   shown: (none)
   limits: {'max_price': 2000, 'in_stock': True}

=== B ===
SHOPPER: bijli chali jaye to roshni ke liye kuch chahiye
ASSISTANT: بجلی بند ہونے پر فوری روشنی کے لیے دو آپشن ہیں۔
   shown: Rechargeable LED Emergency Light, 60 LEDs (Rs 2,450, in stock); Rechargeable LED Bulb, 12 W, B22 (Rs 990, in stock)
   limits: {'max_price': None, 'in_stock': False}

SHOPPER: is se sasta wala?
ASSISTANT: Sab se sasta TOL-027 hai, sirf Rs 990 aur 4 ghante tak chal sakta hai. Dusra option TOL-026 hai, Rs 2,450 aur 8 ghante tak runtime deta hai.
   shown: Rechargeable LED Bulb, 12 W, B22 (Rs 990, in stock); Rechargeable LED Emergency Light, 60 LEDs (Rs 2,450, in stock)
   limits: {'max_price': None, 'in_stock': False}

=== C ===
SHOPPER: my kitchen sink is blocked, water won't drain
ASSISTANT: You can try a drain auger or a plunger to clear the blockage.
   shown: Drain Auger, 5 m Steel Cable (Rs 1,890, in stock); Flange Plunger, Heavy-Duty (Rs 990, in stock); Rubber Cup Plunger with Wooden Handle (Rs 590, in stock)
   limits: {'max_price': None, 'in_stock': False}

**Observations:** The chat carried budget and stock limits correctly across turns (under Rs 2,000 and in stock were both remembered), and its reasons stayed within the product facts: the 4- and 8-hour runtimes it quoted are in the specs. In conversation C, opened from the Furniture page, “my kitchen sink is blocked” still got a drain auger and plungers, so the page context did not override what the shopper typed. Conversation A exposed a real multi-turn failure. On “only ones in stock please”, the assistant said nothing fits, though the chakla belan (Rs 1,290) and chimta (Rs 390) it had just shown are both in stock and under budget. For a follow-up, the chat searches only the latest message and the one before it, so “rotis”, two messages back, was lost, and filler words (“only”, “ones”, “please”) were treated as product words. The same conversation also shows a forced pick (a madhani “for making rotis”) and a reply in Roman Urdu to an English message. Conversation B replied to Roman Urdu in Urdu script and showed an internal product code (“TOL-027”) to the shopper. The language rule and the “never force a product” rule are followed most of the time, but not reliably.

## 6. The judge
Gemini grades the 79 chat answers and all 195 definitions from Part 1. It uses the same Y / P / N scale I used in my hand-check, so the two can be compared. Verdicts are saved as they arrive; if Gemini's free daily limit runs out, re-run the cell later and it carries on.

In [6]:
judge = GeminiJudge()
print("Judge model:", judge.model)
chat_items = []
for r in test:
    x = runs[r["qid"]]
    chat_items.append({"id": r["qid"], "request": r["query"], "assistant_reply": x["reply"],
                       "suggested": [{"title": by_id[p]["title"], "price_pkr": by_id[p]["price_pkr"], "in_stock": by_id[p]["in_stock"],
                                      "facts": by_id[p]["attributes"], "reason_given": w} for p, w in zip(x["picks"], x["whys"])]})
chat_grades = run_batches(judge, CHAT_RUBRIC, chat_items, "judge_chat", "results/judge_chat.json", batch_size=8)

defs = json.load(open("data/definitions_v2.json"))["items"]
def_items = [{"id": pid, "title": by_id[pid]["title"], "facts": by_id[pid]["attributes"], "definition": defs[pid]["text"]}
             for pid in sorted(defs)]
def_grades = run_batches(judge, DEF_RUBRIC, def_items, "judge_definitions", "results/judge_definitions.json", batch_size=15)

Judge model: models/gemini-flash-lite-latest
  graded 8/79
  graded 16/79
  graded 24/79
  graded 32/79
  graded 40/79
  graded 48/79
  graded 56/79
  graded 64/79
  graded 72/79
  graded 79/79
  graded 15/195
  graded 30/195
  graded 45/195
  graded 60/195
  graded 75/195
  graded 90/195
  graded 105/195
  graded 120/195
  graded 135/195
  graded 150/195
  graded 165/195
  graded 180/195
  graded 195/195

In [7]:
cg = pd.DataFrame(chat_grades.values())
print(f"Chat answers graded: {len(cg)} of {len(test)}")
for col in ["first_pick", "reasons_supported", "language_match"]:
    if col in cg:
        print(f"  {col}: " + ", ".join(f"{k} {v}" for k, v in cg[col].value_counts().items()))
dg = pd.DataFrame(def_grades.values())
print(f"\nDefinitions graded: {len(dg)} of {len(defs)}")
if len(dg):
    vc = dg["verdict"].value_counts()
    print("  " + ", ".join(f"{k} {v} ({v / len(dg):.0%})" for k, v in vc.items()))
    display(dg[dg["verdict"] != "Y"][["id", "verdict", "note"]].head(15))

# How far does the judge agree with me? Compare with my 20 hand-checked definitions from Part 1.
if os.path.exists("results/definition_handcheck.json"):
    mine = json.load(open("results/definition_handcheck.json"))
    pairs = [(mine[p]["verdict"], def_grades[p]["verdict"]) for p in mine if p in def_grades]
    agree = sum(a == b for a, b in pairs)
    print(f"\nJudge vs my hand-check on the same {len(pairs)} definitions: same verdict on {agree} ({agree / max(len(pairs), 1):.0%})")
    display(pd.crosstab(pd.Series([a for a, _ in pairs], name="my verdict"), pd.Series([b for _, b in pairs], name="judge verdict")))

Chat answers graded: 79 of 79
  first_pick: good 67, none 10, partial 2
  reasons_supported: yes 69, n/a 10
  language_match: yes 79

Definitions graded: 195 of 195
  Y 185 (95%), P 10 (5%)

,id,verdict,note
17,FUR-018,P,Facts do not state that the chair is stackable.
28,FUR-029,P,"Facts describe a corner shelf unit, not a wall shelf."
82,KIT-039,P,Snipping garlic cloves is incorrect for herb scissors.
111,ORG-009,P,Fact does not support storing boots.
116,ORG-014,P,Facts do not mention stackability.
126,ORG-024,P,Facts do not support storing towels.
131,ORG-029,P,"Facts mention 5 compartments plus a drawer, definition misses drawer count."
133,ORG-031,P,Preventing spills in bags is incorrect for pantry containers.
137,ORG-035,P,"Mentioned storing zip-lock and freezer bags, but facts specify grocery plastic bags."
191,TOL-041,P,Mentioning gas fittings is unsupported; PTFE tape is for water.

Judge vs my hand-check on the same 20 definitions: same verdict on 11 (55%)

judge verdict  P   Y
my verdict
P              1   9
Y              0  10

**Observations:** The judge graded all 79 chat answers and all 195 definitions.

On the chat, its first-pick grades line up with the automatic scores in section 4: 67 good and 10 with no product suggested. It graded the remaining 2 “partial” and never “wrong”, although my labels count both as wrong picks. It marked every reason as supported, including the 7 that used “perfect”, which the code’s claim check flagged. It also marked every reply as matching the shopper’s language, which my check in section 7 below shows is wrong.

On the definitions, it rated 185 accurate (95%) and 10 partly right, with none wrong. Several of its 10 notes are sensible, such as the fridge bins “stack” claim, which I also marked, and “snipping garlic” for herb scissors. Compared with my 20 hand-checked definitions from Part 1, it agreed on only 11 (55%). Every disagreement went the same way: of my 10 “partly right” verdicts, it called 9 accurate. Most of those were about wrong or invented Urdu names, which the judge did not catch, although the names were in the text it graded. It also missed three of my four use errors (“shredding carrots” for a fine rasp, wall plugs “for drywall”, a charpai “for the living room”).

So the judge is useful as a first filter and never contradicted me when I called something accurate. But it is clearly more lenient than a careful human: it misses local-language errors, marketing words and context-specific mistakes. Its 95% should be read as an upper bound, not the true accuracy, and that is why its chat verdicts are spot-checked by me in section 7 below.

> **Note added later:** the hand-check in section 7 was not completed in this run, because the Colab session ended. It was done on the second run (Part 3, section 8). The 16 replies printed in section 7 below are the evidence referred to above. *(Added when the five notebooks were combined; not part of the original runs.)*

## 7. My check of the judge (16 chat verdicts, 20%)
16 of the judge's chat verdicts, sampled at random with a fixed seed. For each, I read the request, the reply and the suggestions, and record whether I agree with the judge's grade.

In [9]:
CHECK = sorted(random.Random("judge-check").sample(sorted(r["qid"] for r in test), 16))
for q in CHECK:
    x, g = runs[q], chat_grades.get(q, {})
    print(f"{q} | {by_q[q]['query']}")
    print("   reply:", x["reply"])
    print("   suggested:", "; ".join(f'{by_id[p]["title"]} (Rs {by_id[p]["price_pkr"]:,})' for p in x["picks"]) or "(none)")
    print("   reasons:", " | ".join(w for w in x["whys"] if w) or "(none)")
    print(f"   JUDGE: first_pick={g.get('first_pick')}, reasons_supported={g.get('reasons_supported')}, "
          f"language_match={g.get('language_match')}  {g.get('note', '')}\n")

Q022 | bookcase
   reply: Here are suitable options:
   suggested: Corner Shelf Unit, 5 Tiers (Rs 6,950); Floating Wall Shelves, Set of 3 (Rs 2,950)
   reasons: Fits a corner and provides 5 shelves for books and decor | Wall‑mounted shelves for displaying books and small items
   JUDGE: first_pick=partial, reasons_supported=yes, language_match=yes  Suggested a corner shelf and floating shelves instead of a standard bookcase.

Q032 | flip rotis without burning my fingers
   reply: Aap ke liye Steel Chimta sab se behtar hai, kyun ke ye chapati ko asani se ulta karne ke liye design ki gayi hai aur haath ko jalne se bachati hai.
   suggested: Steel Chimta, Flat 14 inch (Rs 390)
   reasons: Chapati flip karne ke liye flat stainless steel chimta
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q039 | stop oil splashing everywhere while frying
   reply: Aap ke liye sab se behtar hai Splatter Guard Screen, jo tel ke chhidakne se rokta hai.
   suggested: Splatter Guard Screen, 33 cm (Rs 990); Oil Mister Spray Bottle, 200 ml (Rs 1,150); Glass Oil Dispenser Bottle, 500 ml with Drip-Free Spout (Rs 790)
   reasons: oil splatter ko rokta hai aur stovetop saaf rakhta hai | fine mist se kam tel istemal hota hai, splatter kam hota hai | drip‑free spout se tel girne ka khatra kam hota hai
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q047 | hold two pieces of wood together while the glue dries
   reply: Quick‑Grip Bar Clamps will hold the wood securely while the glue sets.
   suggested: Quick-Grip Bar Clamps, Set of 2 (Rs 1,350)
   reasons: designed for holding wood pieces while gluing
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q049 | stop water leaking from a pipe thread
   reply: Use PTFE Thread Seal Tape to seal the thread and a pipe wrench to tighten the fitting.
   suggested: PTFE Thread Seal Tape, Pack of 5 (Rs 250); Pipe Wrench, 14 inch (Rs 1,650)
   reasons: seals pipe threads to prevent leaks | tightens pipe fittings
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q056 | use my laptop comfortably in bed
   reply: Here are some options for using your laptop comfortably in bed:
   suggested: Laptop Bed Table with Foldable Legs (Rs 2,950); Adjustable Laptop Table with Tilting Top (Rs 4,950); Under-Desk Footrest, Adjustable Angle (Rs 2,450)
   reasons: Foldable legs and flat MDF top make it ideal for a stable bedside laptop surface | Adjustable height and tilting top let you set the perfect viewing angle while lying down | Provides foot support to reduce fatigue when working from bed
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q066 | the kitchen sink drains really slowly
   reply: Your sink can be cleared with a drain auger or a plunger. Here are the best options:
   suggested: Drain Auger, 5 m Steel Cable (Rs 1,890); Rubber Cup Plunger with Wooden Handle (Rs 590); Flange Plunger, Heavy-Duty (Rs 990)
   reasons: 5 m steel cable easily reaches and removes kitchen sink blockages | Rubber cup plunger clears minor sink clogs quickly | Heavy‑duty flange plunger works on stubborn drain blockages
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q067 | guests are staying over and we have no spare bed
   reply: Here are some options for a spare bed:
   suggested: Sofa Cum Bed, 3-Seater, Fabric (Rs 64,500); Woven Rope Charpai, Sheesham Frame (Rs 18,500); Metal Bunk Bed, Single over Single (Rs 46,500)
   reasons: Sofa that converts to a 180 x 120 cm guest bed | Charpai provides a simple sleeping area at a low price | Metal bunk gives two beds if you need extra space
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q069 | plastic shopping bags are piling up in the kitchen
   reply: Aap ke liye sab se behtar hai Wall‑Mounted Plastic Bag Holder, phir Plastic Drawer Organizer Trays aur Expandable Under‑Sink Shelf.
   suggested: Wall-Mounted Plastic Bag Holder (Rs 590); Plastic Drawer Organizer Trays, 8 Pieces (Rs 1,490); Expandable Under-Sink Shelf (Rs 2,650)
   reasons: Bag holder se zip‑lock aur freezer bags ko asani se organize aur drawer space bacha sakte hain | Drawer trays se choti shopping bags ko alag alag sections mein rakh sakte hain | Under‑sink shelf extra storage deta hai, jahan bags ko neatly rakh sakte hain
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q077 | knife sharpener under 1500
   reply: Here is a suitable option:
   suggested: 3-Stage Manual Knife Sharpener (Rs 990)
   reasons: Three sharpening stages (diamond, ceramic, tungsten) for quick blade restoration
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q083 | storage for winter blankets under 2000, in stock
   reply: Here are three options under Rs 2,000:
   suggested: Jumbo Vacuum Bags, Set of 3 (Rs 1,390); Under-Bed Storage Bag with Zip, Set of 2 (Rs 1,590); Hanging Closet Shelves, 6 Sections (Rs 1,350)
   reasons: Vacuum bags compress quilts and coats to save space | Under‑bed bags keep extra blankets hidden and organized | Shelves let you fold and stack blankets neatly
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q094 | jootay rakhne ki rack
   reply: Aap ke liye ye teen options behtar hain:
   suggested: Over-the-Door Shoe Organizer, 24 Pockets (Rs 1,450); Stackable Shoe Rack, 4 Tiers (Rs 2,450); Bamboo Shoe Rack, 2 Tiers (Rs 2,950)
   reasons: 24 clear pockets se jootay asani se dikhte aur floor space bachaata hai | 4 tiers ka steel rack 12 joote tak rakh sakta hai aur vertical stacking se jagah bachat hai | Bamboo ka 2-tier rack natural look deta hai aur 6 joote tak sambhal sakta hai
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q103 | mosquito net for a bed
   reply: Sorry, we don’t have a mosquito net in the current list. Try searching for "mosquito net" or "bed net".
   suggested: (none)
   reasons: (none)
   JUDGE: first_pick=none, reasons_supported=n/a, language_match=yes  No products suggested.

Q108 | hair curling tongs
   reply: Sorry, none of the listed items are hair curling tongs. Try searching for "curling iron" or "hair tongs".
   suggested: (none)
   reasons: (none)
   JUDGE: first_pick=none, reasons_supported=n/a, language_match=yes  No hair curling tongs available in the inventory.

Q109 | office chair under Rs 10000
   reply: Sorry, none of the listed items are office chairs within your budget. Try searching with terms like “office chair” or “desk chair”.
   suggested: (none)
   reasons: (none)
   JUDGE: first_pick=none, reasons_supported=n/a, language_match=yes  No office chairs available within the specified budget.

Q114 | cover for a bean bag
   reply: Aap ke liye Bean Bag Cover Only, Large best hai.
   suggested: Bean Bag Cover Only, Large (Rs 3,950)
   reasons: Large cotton canvas cover for replacing or customizing a bean bag
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

> **Note added later:** the first run stops here. Its hand-check verdicts, cost (section 8) and saving (section 9) were not run before the session ended. They were run on the second run (Part 3, sections 8–10). *(Added when the five notebooks were combined; not part of the original runs.)*

**Observations**

## 8. Cost and latency
Token use for this whole run, and per chat turn. We run on free tiers, so the actual cost is \$0. The estimate uses published paid prices: Groq `gpt-oss-120b` at \$0.15 / \$0.60 per million input / output tokens, and Gemini embeddings at \$0.15 per million tokens. The judge model's price is not included in the per-turn figure, because it is an evaluation cost, not a running cost.

## 9. Saving results

---

# Sahulat Home generative search, Part 3: the "Ask Sahulat" chat, judged


Part 2 measured retrieval: does the right product come back? This part measures the **generation** side of the RAG system, the "Ask Sahulat" chat assistant on the live site. For each message, the assistant:
1. reads budget and stock limits by rules;
2. retrieves candidates with the same search as the search bar (meaning search on the AI definitions, chosen in Part 2), page and visit context included;
3. asks `gpt-oss-120b` (on Groq) to pick up to three candidates and explain each, in the shopper's language, or to say honestly that nothing fits;
4. checks the answer in code: products the search did not return are dropped, limits are re-checked, and reasons are scanned for unsupported claims.

**Questions:**
- Does the chat pick the right product more often than the search bar's first result?
- Does it stay grounded and within limits, and say "no close match" when it should?
- What does an independent judge (Gemini, a different company) think of its answers and of the Part 1 definitions, and how far can that judge be trusted, measured against my own checks?
- What does a chat turn cost?

**This is the second run.** The first run (`notebook/03a_chat_first_run.ipynb`, kept unchanged as evidence) found failures that a rule in the prompt alone did not prevent: English questions answered in Roman Urdu, a conversation that lost its topic, marketing words, and a product code shown to the shopper. I fixed them in code and ran the whole evaluation again. Section 6 compares the two runs.

**Method.** All 79 test questions, single turn and without context, so the numbers are comparable with Part 2. Then scripted multi-turn conversations with page context. Then the judge, and my hand-check of 16 judge verdicts (20%).

**AI use.** Code written with Claude (Anthropic) as a coding assistant. Design decisions, runs, hand-checks and observations are mine.

## 1. Setup
Loads the keys, pulls the project (including the outputs of Parts 1 and 2) and the settings tuned on dev, which are the same ones the live site uses.

In [1]:
!pip install -q groq google-genai

import os, sys, json, random, subprocess, time
import pandas as pd
from google.colab import userdata

os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")
os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")
token = userdata.get("GITHUB_TOKEN")
REPO = "/content/data722-generative-search"
url = f"https://x-access-token:{token}@github.com/mahamnalavi/data722-generative-search.git"
if not os.path.exists(REPO):
    r = subprocess.run(["git", "clone", "-q", url, REPO], capture_output=True, text=True)
else:
    r = subprocess.run(["git", "-C", REPO, "pull", "-q"], capture_output=True, text=True)
print("GitHub:", "OK" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])
subprocess.run(["git", "-C", REPO, "config", "user.name", "Maham (Colab run)"])
subprocess.run(["git", "-C", REPO, "config", "user.email", "mahamnalavi@users.noreply.github.com"])
sys.path.insert(0, REPO); os.chdir(REPO)

for f in ["data/definitions_v2.json", "data/emb_definitions_v2.json", "results/query_vectors.json", "results/tuned_params.json"]:
    assert os.path.exists(f), f"{f} is missing: run Notebooks 01 and 02 first"
from search import chat, pipeline, products_by_id, load_catalogue
from search import evaluate as ev
from search.llm import GroqChat, GeminiEmbedder, USAGE, PRICES
from search.judge import GeminiJudge, run_batches, CHAT_RUBRIC, DEF_RUBRIC
pd.options.display.max_colwidth = 90

rows = json.load(open("data/eval_queries.json", encoding="utf-8"))
test = [r for r in rows if r["split"] == "test"]
by_q = {r["qid"]: r for r in rows}
by_id = products_by_id()
catalogue = load_catalogue()
live = json.load(open("results/tuned_params.json"))["live"]
qvecs = json.load(open("results/query_vectors.json"))
vec_by_text = {ev.query_text_for_embedding(r["query"]): qvecs[r["qid"]] for r in rows}
emb = GeminiEmbedder()
def embed_fn(texts):
    """Re-use the Part 2 query embeddings; embed only texts not seen before (multi-turn demos)."""
    missing = [t for t in texts if t not in vec_by_text]
    if missing:
        vec_by_text.update(zip(missing, emb.embed(missing, kind="query", task="embed_chat_queries")))
    return [vec_by_text[t] for t in texts]
llm = GroqChat()
print(f"Ready: {len(test)} test questions; live settings loaded")

GitHub: OK
Ready: 79 test questions; live settings loaded

**What changed since the first run.** Each fix moves a rule from the prompt into code, because the first run showed the prompt alone was not enough:

| First-run failure | Evidence | Fix |
|---|---|---|
| Replies in the wrong language | 4 of the 16 sample replies printed in the first run were English questions answered in Roman Urdu; a Roman Urdu message answered in Urdu script | The shopper's language is detected by rules and stated in the message ("REPLY LANGUAGE"); if the reply comes back in another language, the model is asked once more |
| Conversation lost its topic | "only ones in stock please" searched without "rotis" (two messages back), so the chat said nothing fits | A follow-up with no product words of its own is searched together with the last message that named a need; filler words ("only", "ones", "please", "sasta", "wala") no longer count as product words |
| Marketing words | 7 answers used "perfect" in a reason | The prompt names the banned words, and the code replaces any that slip through ("perfect" → "right", "ideal" → "suitable") before the shopper sees them; the model's original wording is still recorded |
| Product codes shown | "Sab se sasta TOL-027 hai" | Any product code in the reply is replaced by the product's name |
| Forced picks | A butter churner offered "for making rotis" | The prompt now says to pick a product only if its facts or uses show it does the job, and that fewer picks are better than a weak one |

Everything else (the search, the settings from Part 2, the test questions, the judge) is unchanged, so the two runs can be compared directly.

## 2. The context design
This is what the chat model sees for every message. The system prompt sets the rules: candidates only, at most three, reasons from the facts, honest "no close match", the shopper's language, and context as a soft hint. The message then gives the conversation, the limits, a short summary of the page and visit, and the candidate products with their facts and AI-written uses from Part 1.

Below are the rules, and the complete message for one test question.

In [2]:
print(chat.SYSTEM_PROMPT)
ex = next(r for r in test if r["style"] == "constraint")
msgs = [{"role": "user", "content": ex["query"]}]
cons = chat.merged_constraints([ex["query"]])
cands = []
for t, v in zip(chat.retrieval_texts([ex["query"]]), embed_fn([ev.query_text_for_embedding(ex["query"])])):
    cands += [p["product_id"] for p in pipeline.run(t, mode=pipeline.LIVE_MODE, query_vec=v, k=6, params=live, constraints=cons)["results"]]
print("\n----- message for:", ex["query"], "-----\n")
print(chat.build_user_prompt(msgs, cons, {"page_category": "Kitchenware", "categories_browsed": {"Kitchenware": 2},
                                          "product_types_viewed": ["tawa"], "price_band": {"min": 1850, "max": 3290, "median": 2350}}, cands))

You are "Ask Sahulat", the shopping assistant of Sahulat Home, an online household-goods store in Pakistan.

Rules:
1. Recommend ONLY products listed under CANDIDATES, by their id. Never invent products, prices, stock or features.
2. Pick at most 3, best first. Pick a candidate only if its facts or uses show it does what the shopper asked; fewer picks are better than a weak one. For each, give one short reason that follows from its listed facts or uses.
3. Candidates already meet the stated budget and stock limits. If the shopper asks for cheaper, prefer lower prices.
4. If no candidate does what the shopper needs, set "no_match" to true, say so plainly, and suggest different words to search. Never force a product.
5. Write the reply and every reason in the REPLY LANGUAGE given in the message.
6. PAGE and VISIT are soft hints for unclear requests only. The shopper's own words always win.
7. Keep "reply" under 60 words. No marketing words such as "perfect", "ideal", "best", "premium". Refer to products by name, never by id.

Return JSON only: {"reply": "...", "picks": [{"id": "...", "why": "..."}], "no_match": false}

----- message for: pressure cooker under 5000 -----

CONVERSATION (latest last):
Shopper: pressure cooker under 5000

REPLY LANGUAGE: English
LIMITS: max price Rs 5,000
PAGE: opened from the Kitchenware page | VISIT: browsed Kitchenware (2 pages); viewed tawa; prices viewed Rs 1,850 to Rs 3,290

CANDIDATES:
- KIT-022 | Mini Pressure Cooker, 3 Litre | Rs 4,350 | in stock | uses: quickly cooking small portions of dal; making single‑serve soups; softening vegetables; preparing small batches of rice | specs: capacity: 3 L; material: Hard aluminium; safety: Gasket release window
- KIT-053 | Glass Boil-Over Preventer Disc | Rs 450 | in stock | uses: prevent boil‑over while cooking rice; keep stovetop clean; reduce mess from sauces | specs: material: Heat-resistant glass; diameter: 7 cm
- KIT-043 | Insulated Hot Pot Casserole, 2.5 Litre | Rs 1,890 | in stock | uses: keeping soups hot for serving; transporting stews to a gathering; serving hot dishes at a buffet | specs: capacity: 2.5 L; material: Stainless steel inner, PU insulation; lid: Locking
- KIT-005 | Heavy-Duty Zinc Alloy Garlic Press | Rs 1,150 | in stock | uses: pressing garlic cloves into paste; quickly mincing garlic for curries; adding fresh garlic flavor without chopping | specs: material: Zinc alloy; finish: Chrome; length: 18 cm
- KIT-006 | Rocker Garlic Crusher, Stainless Steel | Rs 890 | in stock | uses: crushing garlic cloves into fine pieces; making garlic paste without a board; quickly preparing garlic for sauces | specs: material: Stainless steel; shape: Curved rocker; length: 13 cm
- KIT-019 | Non-Stick Karahi with Glass Lid, 26 cm | Rs 4,250 | in stock | uses: frying vegetables; making curries; stir‑frying meat; cooking eggs | specs: material: Aluminium, non-stick; diameter: 26 cm; lid: Tempered glass

**Observations:** This is the context design at the centre of the chat. The model never searches the catalogue itself: it receives one message built by code, with five parts:

1. The conversation (the last 6 messages).
2. The limits, read by rules, not by the model (“max price Rs 5,000”).
3. The page and visit summary, marked as a soft hint (rule 6). The visit in this example is made up for illustration; section 3 sends no context.
4. The candidates: up to 6 products from the same search the site uses, each with its id, price, stock, specs and the uses from my Part 1 definitions.
5. The reply language (“REPLY LANGUAGE: English”), detected from the shopper’s words by rules. The first run showed that asking the model to match the shopper’s language was not reliable on its own.

The example shows why this order matters. The budget filter runs before the model sees anything, so the Rs 5,950 and Rs 11,900 pressure cookers are not candidates at all. Only the Rs 4,350 mini cooker is, and the model cannot break the budget without inventing a product, which the code would drop (rule 1 and the grounding check). The other five candidates are weaker matches (a boil-over disc, a hot pot, garlic presses, a karahi), because search always fills the list. That tests rule 4: the model should pick only the mini cooker and not force the rest. Giving each product’s uses, not just its specs, lets the model explain a pick in the shopper’s terms (“for small portions of dal”) while staying within the facts. Asking for JSON with product ids, not free text, is what lets the code check every pick.

## 3. The chat on all 79 test questions
Each question is sent as a single message, with no context, using the same code as the live site. Answers are saved as they arrive. The calls are paced to Groq's free limit of 8,000 tokens per minute, so expect 12-15 minutes. If Groq's daily limit runs out part-way, the affected questions are marked as fallbacks; wait, then re-run this cell and it retries only those.

In [3]:
RUNS_FILE = "results/chat_test_runs.json"
runs = json.load(open(RUNS_FILE)) if os.path.exists(RUNS_FILE) else {}
t0 = time.time()
for i, r in enumerate(test, start=1):
    if r["qid"] in runs and not runs[r["qid"]].get("fallback"):
        continue   # already answered by the chat model (fallbacks are retried)
    res = chat.respond([{"role": "user", "content": r["query"]}], context=None, embed_fn=embed_fn, llm=llm, params=live)
    runs[r["qid"]] = {"reply": res["reply"], "picks": [p["product_id"] for p in res["products"]],
                      "whys": [p["why"] for p in res["products"]], "no_match": res["no_match"],
                      "search_no_close_match": res["search_no_close_match"], **res["diagnostics"]}
    if i % 5 == 0 or i == len(test):
        json.dump(runs, open(RUNS_FILE, "w"), indent=1, ensure_ascii=False)
        print(f"  {len(runs)}/{len(test)} answered ({(time.time() - t0) / 60:.1f} min)")
json.dump(runs, open(RUNS_FILE, "w"), indent=1, ensure_ascii=False)
fallbacks = [q for q, x in runs.items() if x.get("fallback")]
print(f"Done: {len(runs)} answers; chat model unavailable (search results shown instead) for {len(fallbacks)}")

  5/79 answered (0.0 min)
  10/79 answered (1.0 min)
  15/79 answered (2.0 min)
  20/79 answered (2.1 min)
  25/79 answered (3.1 min)
  30/79 answered (4.1 min)
  35/79 answered (4.1 min)
  40/79 answered (5.1 min)
  45/79 answered (6.1 min)
  50/79 answered (7.1 min)
  55/79 answered (7.2 min)
  60/79 answered (8.2 min)
  65/79 answered (9.2 min)
  70/79 answered (10.2 min)
  75/79 answered (10.3 min)
  79/79 answered (11.2 min)
Done: 79 answers; chat model unavailable (search results shown instead) for 0

**Observation:** As in the first run, all 79 test questions were answered by the chat model in 11.2 minutes, with no fallbacks. The time is mostly the pacing that keeps the run within Groq’s free limit. The language retries added with the fixes did not noticeably slow the run; section 4 shows how many were needed.

## 4. Automatic scores
The chat's first suggestion compared with the search bar's first result on the same questions, plus the checks done in code: grounding, limits, unsupported claim words and no-match handling.

In [4]:
search_runs = {x["qid"]: x for x in ev.run_queries(test, pipeline.LIVE_MODE, qvecs, params=live)}
def rel(q): return set(by_q[q]["relevant_ids"])
ans = [r["qid"] for r in test if not r["expects_no_match"]]
nom = [r["qid"] for r in test if r["expects_no_match"]]
rate = lambda xs: round(sum(xs) / len(xs), 3) if xs else None

chat_first = {q: bool(runs[q]["picks"]) and runs[q]["picks"][0] in rel(q) for q in ans}
chat_any = {q: any(p in rel(q) for p in runs[q]["picks"]) for q in ans}
search_first = {q: bool(search_runs[q]["ids"]) and search_runs[q]["ids"][0] in rel(q) for q in ans}
search_top3 = {q: any(i in rel(q) for i in search_runs[q]["ids"][:3]) for q in ans}
viol = sum(1 for q in runs for pid in runs[q]["picks"]
           if (by_q[q]["expected_max_price"] is not None and by_id[pid]["price_pkr"] > by_q[q]["expected_max_price"])
           or (by_q[q]["expected_in_stock"] and not by_id[pid]["in_stock"]))
chat_cw = [(not runs[q]["no_match"]) and (q in nom or not runs[q]["picks"] or runs[q]["picks"][0] not in rel(q)) for q in runs]
search_cw = [(not search_runs[q]["no_close_match"]) and (q in nom or not search_runs[q]["ids"] or search_runs[q]["ids"][0] not in rel(q)) for q in runs]

summary = pd.DataFrame({
    "search bar": {"first result correct": rate(list(search_first.values())),
                            "a correct product among the first 3": rate(list(search_top3.values())),
                            "correct 'no close match'": rate([search_runs[q]["no_close_match"] for q in nom]),
                            "wrongly says 'no close match'": rate([search_runs[q]["no_close_match"] for q in ans]),
                            "confidently wrong": rate(search_cw)},
    "Ask Sahulat chat": {"first result correct": rate(list(chat_first.values())),
                         "a correct product among the first 3": rate(list(chat_any.values())),
                         "correct 'no close match'": rate([runs[q]["no_match"] for q in nom]),
                         "wrongly says 'no close match'": rate([runs[q]["no_match"] for q in ans]),
                         "confidently wrong": rate(chat_cw)}})
display(summary)
dropped = sum(len(x["dropped_ids"]) for x in runs.values())
flagged = {q: x["claim_flags"] for q, x in runs.items() if x["claim_flags"]}
n_picks = sum(len(x["picks"]) for x in runs.values())
print(f"Grounding: {dropped} suggested product ids were not among the search candidates and were dropped by code")
print(f"Limits: {viol} of {n_picks} shown picks break the question's budget or stock limit")
print(f"Unsupported claim words in reasons: {len(flagged)} answers flagged {flagged if flagged else ''}")

style_rows = {}
for r in test:
    if r["expects_no_match"]:
        continue
    s = style_rows.setdefault(r["style"], {"search first": [], "chat first": []})
    s["search first"].append(search_first[r["qid"]]); s["chat first"].append(chat_first[r["qid"]])
display(pd.DataFrame({k: {c: rate(v) for c, v in d.items()} for k, d in style_rows.items()}).T)

# Checks added after the first run: reply language, words replaced before the shopper sees them, product codes
lang = {q: (chat.detect_language(by_q[q]["query"]), x.get("language_retry", False), chat.detect_language(x["reply"])) for q, x in runs.items()}
mismatch = [q for q, (want, _, got) in lang.items() if got != want and not (want == "roman_urdu" and got == "english")]
print(f"Reply language: {len(mismatch)} of {len(runs)} replies not in the shopper's language {mismatch if mismatch else ''}; "
      f"retried once for {sum(r for _, r, _ in lang.values())}")
cleaned = {q: x["cleaned"] for q, x in runs.items() if x.get("cleaned")}
print(f"Replaced before the shopper saw them (marketing words, product codes): {len(cleaned)} answers {cleaned if cleaned else ''}")

                                     search bar  Ask Sahulat chat
first result correct                      1.000             0.957
a correct product among the first 3       1.000             0.957
correct 'no close match'                  0.333             0.889
wrongly says 'no close match'             0.014             0.043
confidently wrong                         0.076             0.013

Grounding: 1 suggested product ids were not among the search candidates and were dropped by code
Limits: 0 of 97 shown picks break the question's budget or stock limit
Unsupported claim words in reasons: 0 answers flagged

            search first  chat first
name                 1.0       0.941
precise              1.0       1.000
vague                1.0       0.909
constraint           1.0       1.000
urdu                 1.0       0.889
trap                 1.0       1.000

Reply language: 0 of 79 replies not in the shopper's language ; retried once for 0
Replaced before the shopper saw them (marketing words, product codes): 1 answers {'Q006': ['ideal']}

**Observations:** On ranking, the second run matches the first: the chat put a correct product first for 67 of 70 answerable questions (0.96), against 1.00 for the search bar, and said “no close match” for 8 of the 9 things the store doesn’t sell, against 3 for the search bar. All three misses are now over-caution, answerable questions it called “no close match” (4.3%, up from 2.9%), rather than wrong picks. Its confidently-wrong rate fell to 1.3% (1 of 79), a sixth of the search bar’s 7.6%. It also showed fewer products: 97 picks against 121 in the first run, so the new rule to skip weak picks took effect.

The fixes show clearly in the checks. Every reply was in the shopper’s language (0 of 79 wrong, and no retry was needed), so stating the language in the message was enough. No reason contained a claim word (0, against 7 answers with “perfect” in the first run), and the code replaced the one remaining marketing word (“ideal”) before the shopper saw it. The grounding check dropped one suggested product that search had not returned, which shows why that check stays in code. No pick broke a budget or stock limit. This is one run each, and the model’s answers vary from run to run, so a difference of one question (2 vs 3 cautious answers) is within normal variation. The language and claim-word changes are too large for that.

## 5. Multi-turn conversations and context
Three scripted conversations, run exactly as the live site runs them:
- **A.** A follow-up that tightens the budget, then adds stock, opened from the Kitchenware page.
- **B.** Roman Urdu, with a "cheaper" follow-up.
- **C.** Opened from the Furniture page while the shopper describes a plumbing problem. Their own words should win over the page.

In [5]:
def converse(turns, context):
    msgs = []
    for text in turns:
        msgs.append({"role": "user", "content": text})
        res = chat.respond(msgs, context=context, embed_fn=embed_fn, llm=llm, params=live)
        msgs.append({"role": "assistant", "content": res["reply"]})
        shown = "; ".join(f'{p["title"]} (Rs {p["price_pkr"]:,}, {"in stock" if p["in_stock"] else "out of stock"})' for p in res["products"]) or "(none)"
        print(f"SHOPPER: {text}\nASSISTANT: {res['reply']}\n   shown: {shown}\n   limits: {res['constraints']}\n")

kitchen = {"page_category": "Kitchenware", "categories_browsed": {"Kitchenware": 3}, "product_types_viewed": ["karahi", "tawa"],
           "price_band": {"min": 1850, "max": 4250, "median": 2350}}
furniture = {"page_category": "Furniture", "categories_browsed": {"Furniture": 4}, "product_types_viewed": ["sofa_cum_bed"],
             "price_band": {"min": 20000, "max": 64500, "median": 46500}}
print("=== A ==="); converse(["I need something for making rotis at home", "something cheaper, under 2000", "only ones in stock please"], kitchen)
print("=== B ==="); converse(["bijli chali jaye to roshni ke liye kuch chahiye", "is se sasta wala?"], None)
print("=== C ==="); converse(["my kitchen sink is blocked, water won't drain"], furniture)

=== A ===
SHOPPER: I need something for making rotis at home
ASSISTANT: You can roll the dough with the Wooden Chakla Belan Set, and cook the rotis on the Granite‑Coated Flat Tawa.
   shown: Wooden Chakla Belan Set, 10 inch (Rs 1,290, in stock); Granite-Coated Flat Tawa, 12 inch, Induction Base (Rs 3,290, in stock)
   limits: {'max_price': None, 'in_stock': False}

SHOPPER: something cheaper, under 2000
ASSISTANT: You could use the Wooden Chakla Belan Set for rolling the dough and the Steel Chimta to flip the rotis while cooking.
   shown: Wooden Chakla Belan Set, 10 inch (Rs 1,290, in stock); Steel Chimta, Flat 14 inch (Rs 390, in stock)
   limits: {'max_price': 2000, 'in_stock': False}

SHOPPER: only ones in stock please
ASSISTANT: The Wooden Chakla Belan Set lets you roll the dough easily, and the Steel Chimta is handy for flipping the rotis while cooking.
   shown: Wooden Chakla Belan Set, 10 inch (Rs 1,290, in stock); Steel Chimta, Flat 14 inch (Rs 390, in stock)
   limits: {'max_price': 2000, 'in_stock': True}

=== B ===
SHOPPER: bijli chali jaye to roshni ke liye kuch chahiye
ASSISTANT: Aap ke liye Rechargeable LED Emergency Light aur Rechargeable LED Bulb dono achhe hain, dono power outage mein roshni dete hain.
   shown: Rechargeable LED Emergency Light, 60 LEDs (Rs 2,450, in stock); Rechargeable LED Bulb, 12 W, B22 (Rs 990, in stock)
   limits: {'max_price': None, 'in_stock': False}

SHOPPER: is se sasta wala?
ASSISTANT: Aap ke liye Rechargeable LED Bulb Rs 990 mein sasta hai aur power outage mein roshni deta hai.
   shown: Rechargeable LED Bulb, 12 W, B22 (Rs 990, in stock)
   limits: {'max_price': None, 'in_stock': False}

=== C ===
SHOPPER: my kitchen sink is blocked, water won't drain
ASSISTANT: Try a Drain Auger to reach deep clogs, or a plunger for simpler blockages.
   shown: Drain Auger, 5 m Steel Cable (Rs 1,890, in stock); Rubber Cup Plunger with Wooden Handle (Rs 590, in stock)
   limits: {'max_price': None, 'in_stock': False}

**Observations:** All four failures from the first run’s conversations are fixed. In conversation A, “only ones in stock please” now keeps the topic: the chat again suggests the chakla belan (Rs 1,290) and chimta (Rs 390), both in stock and under the Rs 2,000 limit from the turn before, instead of saying nothing fits. It also answers in English, and no longer offers a butter churner “for making rotis”. In conversation B, the Roman Urdu question gets a Roman Urdu reply (the first run switched to Urdu script), and “is se sasta wala?” names the Rs 990 bulb instead of showing its product code. Conversation C still shows the shopper’s words winning over the page: opened from the Furniture page, “my kitchen sink is blocked” got a drain auger and a plunger. Budget and stock limits were carried correctly across every turn, as before. These are three scripted conversations run once, so they show that the specific failures are fixed, not that the chat never loses a topic.

## 6. Before and after the fixes
The first run's numbers come from `results/part3_first_run.json`, read from the printed outputs of `03a_chat_first_run.ipynb` (its raw answer files were lost when that Colab session ended before they were saved). The language check on the first run is limited to the 16 answers printed there, so the same 16 questions are compared here.

In [6]:
first = json.load(open("results/part3_first_run.json"))
f4 = first["section4_summary"]
sample = [d["qid"] for d in first["section7_sample"]]
lang_first = len(first["section7_language_mismatches"])
lang_now = len([q for q in sample if q in mismatch])
claims_now_written = sum(1 for x in runs.values() if x["claim_flags"])
compare = pd.DataFrame({
    "first run": {"first result correct (70 answerable)": f4["first result correct"]["Ask Sahulat chat"],
                  "correct 'no close match' (9)": f4["correct 'no close match'"]["Ask Sahulat chat"],
                  "wrongly says 'no close match'": f4["wrongly says 'no close match'"]["Ask Sahulat chat"],
                  "confidently wrong (79)": f4["confidently wrong"]["Ask Sahulat chat"],
                  "answers with a claim word written by the model": first["claim_word_answers"],
                  "answers with a claim word shown to the shopper": first["claim_word_answers"],
                  "wrong reply language, same 16 questions": f"{lang_first}/16"},
    "second run (fixed)": {"first result correct (70 answerable)": summary.loc["first result correct", "Ask Sahulat chat"],
                  "correct 'no close match' (9)": summary.loc["correct 'no close match'", "Ask Sahulat chat"],
                  "wrongly says 'no close match'": summary.loc["wrongly says 'no close match'", "Ask Sahulat chat"],
                  "confidently wrong (79)": summary.loc["confidently wrong", "Ask Sahulat chat"],
                  "answers with a claim word written by the model": claims_now_written,
                  "answers with a claim word shown to the shopper": 0,
                  "wrong reply language, same 16 questions": f"{lang_now}/16"}})
display(compare)
print(f"Wrong reply language across all 79 (second run only): {len(mismatch)}")
print("\nFirst run, conversation A (for comparison with section 5 above):")
print(first["section5_conversations"].split("=== B ===")[0])
json.dump(compare.astype(str).to_dict(), open("results/part3_before_after.json", "w"), indent=1)

                                               first run second run (fixed)
first result correct (70 answerable)               0.957              0.957
correct 'no close match' (9)                       0.889              0.889
wrongly says 'no close match'                      0.029              0.043
confidently wrong (79)                             0.025              0.013
answers with a claim word written by the model         7                  0
answers with a claim word shown to the shopper         7                  0
wrong reply language, same 16 questions             4/16               0/16

Wrong reply language across all 79 (second run only): 0

First run, conversation A (for comparison with section 5 above):
=== A ===
SHOPPER: I need something for making rotis at home
ASSISTANT: Here are suitable items:
   shown: Granite-Coated Flat Tawa, 12 inch, Induction Base (Rs 3,290, in stock); Wooden Chakla Belan Set, 10 inch (Rs 1,290, in stock)
   limits: {'max_price': None, 'in_stock': False}

SHOPPER: something cheaper, under 2000
ASSISTANT: Here are some affordable options for making rotis:
   shown: Wooden Chakla Belan Set, 10 inch (Rs 1,290, in stock); Steel Chimta, Flat 14 inch (Rs 390, in stock); Wooden Hand Churner (Madhani), 45 cm (Rs 650, in stock)
   limits: {'max_price': 2000, 'in_stock': False}

SHOPPER: only ones in stock please
ASSISTANT: Maaf, in items mein roti banane ke liye koi cheez nahi hai. Aap "tawa", "roti maker" ya "chapati press" jaise lafz try karen.
   shown: (none)
   limits: {'max_price': 2000, 'in_stock': True}

**Observations:** The fixes removed the failures they targeted without costing accuracy. First-place accuracy (0.957) and correct “no close match” (8 of 9) are identical across the two runs. The chat was confidently wrong less often (1 answer, against 2), and said “no close match” for one more answerable question (3, against 2). With one run each, that one-question shift is within the normal variation of a language model.

The targeted problems are gone. Replies in the wrong language fell from 4 of the same 16 questions to 0, and none of the 79 were wrong in the second run. Answers with an unsupported claim word in a reason fell from 7 to 0. That happened at the source: once the prompt named the banned words, the model stopped writing “perfect”. The code’s replacement step is a safety net, and it caught one remaining “ideal”. So the “shown to the shopper” figure of 0 is guaranteed by the code; the “written by the model” figure is the real improvement. Conversation A, printed above from the first run, can be compared turn by turn with section 5: the topic is now kept, and the wrong reply and the forced pick are gone.

The lesson is that rules stated only in the prompt were followed most of the time but not reliably. The ones that matter to a shopper (language, unsupported claims, product codes, the conversation topic) are now set or checked in code, as budget and stock limits already were.

## 7. The judge
Gemini grades the 79 chat answers and all 195 definitions from Part 1. It uses the same Y / P / N scale I used in my hand-check, so the two can be compared. Verdicts are saved as they arrive; if Gemini's free daily limit runs out, I re-run the cell later and it carries on.

In [7]:
judge = GeminiJudge()
print("Judge model:", judge.model)
chat_items = []
for r in test:
    x = runs[r["qid"]]
    chat_items.append({"id": r["qid"], "request": r["query"], "assistant_reply": x["reply"],
                       "suggested": [{"title": by_id[p]["title"], "price_pkr": by_id[p]["price_pkr"], "in_stock": by_id[p]["in_stock"],
                                      "facts": by_id[p]["attributes"], "reason_given": w} for p, w in zip(x["picks"], x["whys"])]})
chat_grades = run_batches(judge, CHAT_RUBRIC, chat_items, "judge_chat", "results/judge_chat.json", batch_size=8)

defs = json.load(open("data/definitions_v2.json"))["items"]
def_items = [{"id": pid, "title": by_id[pid]["title"], "facts": by_id[pid]["attributes"], "definition": defs[pid]["text"]}
             for pid in sorted(defs)]
def_grades = run_batches(judge, DEF_RUBRIC, def_items, "judge_definitions", "results/judge_definitions.json", batch_size=15)

Judge model: models/gemini-flash-lite-latest
  graded 8/79
  graded 16/79
  graded 24/79
  graded 32/79
  graded 40/79
  graded 48/79
  graded 56/79
  graded 64/79
  graded 72/79
  graded 79/79
  graded 15/195
  graded 30/195
  graded 45/195
  graded 60/195
  graded 75/195
  graded 90/195
  graded 105/195
  graded 120/195
  graded 135/195
  graded 150/195
  graded 165/195
  graded 180/195
  graded 195/195

In [8]:
cg = pd.DataFrame(chat_grades.values())
print(f"Chat answers graded: {len(cg)} of {len(test)}")
for col in ["first_pick", "reasons_supported", "language_match"]:
    if col in cg:
        print(f"  {col}: " + ", ".join(f"{k} {v}" for k, v in cg[col].value_counts().items()))
dg = pd.DataFrame(def_grades.values())
print(f"\nDefinitions graded: {len(dg)} of {len(defs)}")
if len(dg):
    vc = dg["verdict"].value_counts()
    print("  " + ", ".join(f"{k} {v} ({v / len(dg):.0%})" for k, v in vc.items()))
    display(dg[dg["verdict"] != "Y"][["id", "verdict", "note"]].head(15))

# How far does the judge agree with me? Compare with my 20 hand-checked definitions from Part 1.
if os.path.exists("results/definition_handcheck.json"):
    mine = json.load(open("results/definition_handcheck.json"))
    pairs = [(mine[p]["verdict"], def_grades[p]["verdict"]) for p in mine if p in def_grades]
    agree = sum(a == b for a, b in pairs)
    print(f"\nJudge vs my hand-check on the same {len(pairs)} definitions: same verdict on {agree} ({agree / max(len(pairs), 1):.0%})")
    display(pd.crosstab(pd.Series([a for a, _ in pairs], name="my verdict"), pd.Series([b for _, b in pairs], name="judge verdict")))

Chat answers graded: 79 of 79
  first_pick: good 67, none 11, partial 1
  reasons_supported: yes 68, n/a 11
  language_match: yes 79

Definitions graded: 195 of 195
  Y 183 (94%), P 12 (6%)

,id,verdict,note
17,FUR-018,P,Facts do not state that the chair is stackable.
28,FUR-029,P,"Called wall shelf in shoppers say, but facts specify corner unit."
82,KIT-039,P,Snipping garlic cloves is not appropriate for herb scissors.
100,KIT-057,P,Grating soft fruits is not supported by facts.
111,ORG-009,P,"Mentions organizing boots, which rarely fit shoe pockets."
116,ORG-014,P,"Mentions stacking, but facts do not state these bins stack."
126,ORG-024,P,Facts do not mention holding towels.
131,ORG-029,P,"Facts state 5 compartments and a drawer, not just 5."
133,ORG-031,P,Preventing spills in bags is incorrect for pantry containers.
137,ORG-035,P,Mentions zip-lock and freezer bags; facts only state plastic bags.
148,ORG-046,P,"Shoppers say mentions wall mug rack, but facts do not state wall mounting."
191,TOL-041,P,Mentioning gas fittings may be dangerous without specific product certification.

Judge vs my hand-check on the same 20 definitions: same verdict on 11 (55%)

judge verdict  P   Y
my verdict
P              1   9
Y              0  10

**Observations:** The judge’s chat grades match the automatic scores in section 4: 67 good first picks, 11 answers with no product (the 8 correct “no close match” answers and the 3 over-cautious ones), and 1 partial, the single confidently-wrong answer. As in the first run, it never used “wrong”. This time its finding that every reply was in the shopper’s language agrees with the code’s own check (0 of 79 wrong). In the first run it gave the same verdict while 4 of the 16 replies printed in that run were in the wrong language, so its language grade cannot be trusted on its own.

On the Part 1 definitions, which have not changed, the judge gave 183 accurate and 12 partly right this time, against 185 and 10 in the first run. The same judge, grading the same text, gave different verdicts on a few items, so even an AI judge’s scores carry run-to-run noise. Several of its notes are sensible (“gas fittings” for PTFE tape, the fridge bins “stack” claim). Its agreement with my 20 hand-checked definitions is unchanged at 11 of 20 (55%), with the same pattern: it never called a definition I rated accurate wrong, but it called 9 of my 10 “partly right” definitions accurate, missing invented Urdu names and context errors such as wall plugs “for drywall”. The judge is a useful first filter, but it is consistently more lenient than my own checking, and its 94% should be read as an upper bound.

## 8. My check of the judge (16 chat verdicts, 20%)
16 of the judge's chat verdicts, sampled at random with a fixed seed. For each, I read the request, the reply and the suggestions, and record whether I agree with the judge's grade.

In [9]:
CHECK = sorted(random.Random("judge-check").sample(sorted(r["qid"] for r in test), 16))
for q in CHECK:
    x, g = runs[q], chat_grades.get(q, {})
    print(f"{q} | {by_q[q]['query']}")
    print("   reply:", x["reply"])
    print("   suggested:", "; ".join(f'{by_id[p]["title"]} (Rs {by_id[p]["price_pkr"]:,})' for p in x["picks"]) or "(none)")
    print("   reasons:", " | ".join(w for w in x["whys"] if w) or "(none)")
    print(f"   JUDGE: first_pick={g.get('first_pick')}, reasons_supported={g.get('reasons_supported')}, "
          f"language_match={g.get('language_match')}  {g.get('note', '')}\n")

Q022 | bookcase
   reply: We don’t have any in‑stock bookcases right now. Try searching for “shelf unit” or “wall shelves”.
   suggested: (none)
   reasons: (none)
   JUDGE: first_pick=none, reasons_supported=n/a, language_match=yes  No bookcases in stock.

Q032 | flip rotis without burning my fingers
   reply: Try the Steel Chimta, Flat 14 inch—it lets you flip chapatis safely without touching the hot surface.
   suggested: Steel Chimta, Flat 14 inch (Rs 390)
   reasons: designed for flipping chapati and turning fried items, keeping your fingers away from heat
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q039 | stop oil splashing everywhere while frying
   reply: The Splatter Guard Screen stops oil from splashing while frying.
   suggested: Splatter Guard Screen, 33 cm (Rs 990)
   reasons: prevents oil splatter while frying
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q047 | hold two pieces of wood together while the glue dries
   reply: The Quick‑Grip Bar Clamps hold wood pieces securely while the glue sets.
   suggested: Quick-Grip Bar Clamps, Set of 2 (Rs 1,350)
   reasons: designed for holding wood pieces while gluing
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q049 | stop water leaking from a pipe thread
   reply: Use PTFE Thread Seal Tape to stop the leak; it seals pipe threads effectively. A pipe wrench can help tighten the joint if needed.
   suggested: PTFE Thread Seal Tape, Pack of 5 (Rs 250); Pipe Wrench, 14 inch (Rs 1,650)
   reasons: seals pipe threads to prevent leaks | tightens pipe fittings for a secure connection
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q056 | use my laptop comfortably in bed
   reply: A Laptop Bed Table with Foldable Legs lets you work comfortably in bed, and its size fits well for a laptop. The Adjustable Laptop Table with Tilting Top also offers height flexibility and a tilting surface for better viewing. Both are in stock and affordable.
   suggested: Laptop Bed Table with Foldable Legs (Rs 2,950); Adjustable Laptop Table with Tilting Top (Rs 4,950)
   reasons: Foldable legs make it easy to use on a bed | Adjustable height and tilting top improve comfort while in bed
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q066 | the kitchen sink drains really slowly
   reply: Try a Drain Auger to reach deep clogs, or a Rubber Cup Plunger for quick surface blockages.
   suggested: Drain Auger, 5 m Steel Cable (Rs 1,890); Rubber Cup Plunger with Wooden Handle (Rs 590)
   reasons: clears kitchen sink clogs with a 5 m steel cable | removes minor pipe blockages in sink drains
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q067 | guests are staying over and we have no spare bed
   reply: You could use the Sofa Cum Bed, which turns into a guest bed; the Metal Bunk Bed gives two sleeping spots while saving floor space; or the Woven Rope Charpai, which works as a simple guest sleeping area.
   suggested: Sofa Cum Bed, 3-Seater, Fabric (Rs 64,500); Metal Bunk Bed, Single over Single (Rs 46,500); Woven Rope Charpai, Sheesham Frame (Rs 18,500)
   reasons: turns into a guest bed | provides two sleeping spots and saves floor space | can be used as a guest sleeping area
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q069 | plastic shopping bags are piling up in the kitchen
   reply: A wall‑mounted plastic bag holder can keep your zip‑lock and freezer bags organized and free up drawer space.
   suggested: Wall-Mounted Plastic Bag Holder (Rs 590)
   reasons: stores zip‑lock bags and keeps them easily reachable
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q077 | knife sharpener under 1500
   reply: The 3‑Stage Manual Knife Sharpener fits your budget and sharpens kitchen knives.
   suggested: 3-Stage Manual Knife Sharpener (Rs 990)
   reasons: Sharpens kitchen knives with diamond, ceramic, and tungsten stages
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q083 | storage for winter blankets under 2000, in stock
   reply: Here are some options for storing winter blankets within your budget:
   suggested: Jumbo Vacuum Bags, Set of 3 (Rs 1,390); Under-Bed Storage Bag with Zip, Set of 2 (Rs 1,590); Hanging Closet Shelves, 6 Sections (Rs 1,350)
   reasons: Jumbo vacuum bags compress quilts and blankets to save space | Under‑bed storage bags keep extra bedding hidden and organized | Hanging closet shelves provide easy access for folded blankets
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q094 | jootay rakhne ki rack
   reply: Aap ke liye ye shoe rack munasib hain:
   suggested: Stackable Shoe Rack, 4 Tiers (Rs 2,450); Bamboo Shoe Rack, 2 Tiers (Rs 2,950); Over-the-Door Shoe Organizer, 24 Pockets (Rs 1,450)
   reasons: 4 tiers se 12 joote rakh sakte hain aur floor space bachata hai | Bamboo ka natural look aur 2 tiers se 6 joote organize karte hain | 24 pockets ke saath over-the-door lagta hai, floor space bilkul bachata
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

Q103 | mosquito net for a bed
   reply: Sorry, we don’t have a mosquito net in our current list. Try searching for "mosquito net" or "bed net".
   suggested: (none)
   reasons: (none)
   JUDGE: first_pick=none, reasons_supported=n/a, language_match=yes  No products available for this request.

Q108 | hair curling tongs
   reply: We don’t have hair curling tongs in our catalog. Try searching for “curling iron” or “hair styling tools”.
   suggested: (none)
   reasons: (none)
   JUDGE: first_pick=none, reasons_supported=n/a, language_match=yes  No products were suggested in the catalog.

Q109 | office chair under Rs 10000
   reply: Sorry, none of the listed items match an office chair under Rs 10,000. Try searching with terms like “office chair” or “desk chair”.
   suggested: (none)
   reasons: (none)
   JUDGE: first_pick=none, reasons_supported=n/a, language_match=yes  No products were suggested in the catalog.

Q114 | cover for a bean bag
   reply: The Bean Bag Cover Only, Large will replace your worn cover or let you add a new breathable cover.
   suggested: Bean Bag Cover Only, Large (Rs 3,950)
   reasons: fits a bean bag and is a replaceable cotton canvas cover
   JUDGE: first_pick=good, reasons_supported=yes, language_match=yes

In [10]:
# My verdict on each judge grade: "agree" or "disagree", with a note where I disagree
MY_CHECK = {
    "Q022": ("agree", "Correct to suggest nothing: the store's only bookcase is out of stock, and the reply says so and suggests other words. The automatic score counts this as 'wrongly says no close match', which is unfair here"),
    "Q032": ("agree", ""),
    "Q039": ("agree", ""),
    "Q047": ("agree", ""),
    "Q049": ("agree", ""),
    "Q056": ("agree", ""),
    "Q066": ("agree", ""),
    "Q067": ("agree", ""),
    "Q069": ("agree", "Right product, but the reason talks about zip-lock and freezer bags, not shopping bags. It comes from an error in this product's AI definition (the judge flagged that definition in section 7), so definition errors carry through into chat answers"),
    "Q077": ("agree", ""),
    "Q083": ("agree", ""),
    "Q094": ("agree", "Roman Urdu question, Roman Urdu reply; all three capacities match the specs"),
    "Q103": ("agree", "Correctly said the store has no mosquito net"),
    "Q108": ("agree", "Correctly said the store has no hair curling tongs"),
    "Q109": ("agree", "Correctly said no office chair within budget"),
    "Q114": ("agree", ""),
}
assert sorted(MY_CHECK) == CHECK, "The IDs must match the sample shown above"
marks = [v for v, _ in MY_CHECK.values()]
if "?" in marks:
    print(f"{marks.count('?')} still marked '?'.")
else:
    print(f"I agree with the judge on {marks.count('agree')} of 16 chat verdicts ({marks.count('agree') / 16:.0%})")
    json.dump({q: {"my_view": v, "note": n} for q, (v, n) in MY_CHECK.items()}, open("results/judge_handcheck.json", "w"), indent=1)

I agree with the judge on 16 of 16 chat verdicts (100%)

**Observations:** I agreed with the judge on all 16 sampled chat verdicts. Two need a note. In Q022 (“bookcase”), the chat suggested nothing because the store’s only bookcase is out of stock, and said so. That is the honest answer, but the automatic score in section 4 counts it as “wrongly says no close match”, so that measure slightly overstates the chat’s over-caution. In Q069, the right product came first, but its reason talks about zip-lock and freezer bags instead of shopping bags. That wording comes from an error in the product’s AI definition, which the judge flagged in section 7, so mistakes in the Part 1 definitions can carry through into chat answers.

Full agreement here does not show that the judge is reliable. It shows that the second run left it little to miss. The first run’s records show what it misses: it marked all 79 replies as in the shopper’s language and every reason as supported, yet 4 of these same 16 questions were answered in Roman Urdu (section 6), and 7 reasons used “perfect”. So the judge confirms good answers but does not catch language or wording problems. Those are now checked in code, not left to the judge.

## 9. Cost and latency
Token use for this whole run, and per chat turn. We run on free tiers, so the actual cost is \$0. The estimate uses published paid prices: Groq `gpt-oss-120b` at \$0.15 / \$0.60 per million input / output tokens, and Gemini embeddings at \$0.15 per million tokens. The judge model's price is not included in the per-turn figure, because it is an evaluation cost, not a running cost.

In [11]:
usage = pd.DataFrame(USAGE.summary()).T
display(usage)
turns = [x for x in runs.values() if not x.get("fallback")]
tin = sum(x["tokens_in"] for x in turns) / len(turns)
tout = sum(x["tokens_out"] for x in turns) / len(turns)
lat = sorted(x["latency_ms"] for x in turns)
p = PRICES["openai/gpt-oss-120b"]
per_turn = tin / 1e6 * p["in"] + tout / 1e6 * p["out"]
embed_per_query = 12 / 1e6 * PRICES["gemini-embedding-001"]["in"]   # about 12 tokens per search
print(f"Average chat turn: {tin:,.0f} input + {tout:,.0f} output tokens; median latency {lat[len(lat) // 2] / 1000:.1f} s "
      f"(slowest {lat[-1] / 1000:.1f} s)")
print(f"Estimated cost at paid prices: ${per_turn * 1000:.2f} per 1,000 chat turns; "
      f"${embed_per_query * 1000:.4f} per 1,000 searches (embedding only); hosting on Vercel Hobby: $0")
json.dump({"avg_tokens_in": tin, "avg_tokens_out": tout, "median_latency_s": lat[len(lat) // 2] / 1000,
           "usd_per_1000_chat_turns": per_turn * 1000, "usd_per_1000_searches": embed_per_query * 1000},
          open("results/part3_cost.json", "w"), indent=1)

,model,calls,items,tokens_in,tokens_out,seconds,est_cost_usd
chat_turn,openai/gpt-oss-120b,85,85,68894,10022,45.9,0.01635
embed_chat_queries,gemini-embedding-001,6,6,76,0,1.4,0.00001
judge_chat,models/gemini-flash-lite-latest,10,79,18469,4493,14.1,0.0
judge_definitions,models/gemini-flash-lite-latest,13,195,31402,6779,20.1,0.0

Average chat turn: 806 input + 115 output tokens; median latency 0.6 s (slowest 58.7 s)
Estimated cost at paid prices: $0.19 per 1,000 chat turns; $0.0018 per 1,000 searches (embedding only); hosting on Vercel Hobby: $0

**Observations:** This run made 85 chat calls (79 test questions and 6 conversation turns), using about 79,000 tokens in total, and 6 Gemini embedding calls for conversation messages not seen before. An average chat turn uses 806 input and 115 output tokens. Most of the input is the candidate list with each product’s facts and uses. At paid prices that is about \$0.19 per 1,000 chat turns, and \$0.0018 per 1,000 searches for the embedding. Hosting on Vercel’s free plan costs \$0, and on free tiers the whole project costs \$0. The judge’s calls (about 61,000 tokens) are an evaluation cost, not a running cost, so they are not in the per-turn figure.

The median chat turn took 0.6 seconds. The slowest (58.7 s) was the notebook pausing to stay within Groq’s free limit of 8,000 tokens per minute, not the model itself. On the live site there is no such pause: if the limit is reached, the chat shows the search results instead. The site also adds one embedding call per new message, so a shopper waits a little longer than the median here. The binding constraint is the free tier, not cost. At about 920 tokens per turn, 8,000 tokens a minute allows roughly 8 chat turns a minute, and Groq’s free daily limit of 1,000 requests caps the chat at about 1,000 turns a day. That is fine for a demo, but a real store would need a paid tier, which at these prices is still very cheap.

## 10. Saving results

In [12]:
summary.to_json("results/part3_chat_vs_search.json", indent=1)
subprocess.run(["git", "add", "results"], check=True)
subprocess.run(["git", "commit", "-q", "-m", "Part 3 run: chat evaluation, judge, judge hand-check, cost"])
subprocess.run(["git", "pull", "-q", "--rebase"])
r = subprocess.run(["git", "push", "-q"], capture_output=True, text=True)
print("Pushed to GitHub" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])

Pushed to GitHub

---

# Sahulat Home generative search, Part 4: the catalogue as an MCP server

**What MCP is.** The Model Context Protocol is an open standard that lets AI assistants (Claude, ChatGPT, coding tools) call outside tools and data through one common interface. A store that publishes an MCP server can be used by any compatible assistant, without a custom integration for each one.

**What I built.** `mcp_server.py` exposes Sahulat's search as two tools:
- `search_products(query, max_price, in_stock, page_category, limit)`
- `get_product(product_id)`

They run the same meaning search on the AI definitions (keyword search if Gemini is unavailable), the same hard budget and stock filters, and the same "no close match" decision as the website.

**Why, and where it is not used.** An assistant connected to this server answers shopping questions from the store's real catalogue instead of guessing from its training data. The live website does not use MCP: its chat calls the search directly as a fixed pipeline, which is cheaper and easier to evaluate (decision 3 in `docs/DECISIONS.md`). MCP is the integration layer for other assistants.

**AI use.** Code written with Claude (Anthropic) as a coding assistant. Design decisions, runs and observations are mine.

## 1. Setup
Installs the MCP library (pinned to the version the server was written for), loads the Gemini key for meaning-based search, and pulls the project.

In [3]:
!pip install -q "mcp==2.3.0" google-genai

import os, sys, json, subprocess
from google.colab import userdata
os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")
token = userdata.get("GITHUB_TOKEN")
REPO = "/content/data722-generative-search"
url = f"https://x-access-token:{token}@github.com/mahamnalavi/data722-generative-search.git"
if not os.path.exists(REPO):
    r = subprocess.run(["git", "clone", "-q", url, REPO], capture_output=True, text=True)
else:
    r = subprocess.run(["git", "-C", REPO, "pull", "-q"], capture_output=True, text=True)
print("GitHub:", "OK" if r.returncode == 0 else "PROBLEM -> " + r.stderr.replace(token, "***")[:300])
from mcp import Client, StdioServerParameters
SERVER = StdioServerParameters(command=sys.executable, args=[f"{REPO}/mcp_server.py"], cwd=REPO,
                               env={**os.environ})
from mcp.client.stdio import stdio_client
# Colab's output area can't be handed to another process, so the server's own log goes to a file.
SERVER_LOG = open("/content/mcp_server.log", "w")
def connect():
    """Start the server as a separate process and connect to it over standard input and output."""
    return Client(stdio_client(SERVER, errlog=SERVER_LOG))
def show(result):
    """MCP returns tool results as JSON text; turn it back into data."""
    return json.loads(result.content[0].text)

GitHub: OK

## 2. Connect and list the tools
The server runs as a separate process and talks MCP over standard input and output, exactly as an assistant such as Claude Desktop would start it.

In [5]:
async with connect() as client:
    tools = await client.list_tools()
    for t in tools.tools:
        schema = getattr(t, "input_schema", None) or getattr(t, "inputSchema", None) or {}
        print(f"{t.name}: {t.description}\n   inputs: {list(schema.get('properties', {}))}\n")

search_products: Find products by name or by what the shopper needs them for.
max_price (PKR) and in_stock are applied strictly. page_category (Kitchenware, Tools, Organizers,
Furniture) is an optional soft hint. Returns results, plus no_close_match=true when nothing fits well.
   inputs: ['query', 'max_price', 'in_stock', 'page_category', 'limit']

get_product: Full details for one product id returned by search_products.
   inputs: ['product_id']

**Observations:** The server describes its two tools in a form any MCP assistant can read: what each does, and which inputs it takes (query, max_price, in_stock, page_category and limit for search; a product id for details). The assistant decides when to call them; the server decides how the search runs. Running the server from Colab first failed because Colab’s output area can’t be handed to another process. Sending the server’s log to a file fixed it.

## 3. Call the tools
Four calls an assistant might make: a described need, a budget nobody can meet, Roman Urdu, and full details for one product.

In [6]:
async with connect() as client:
    for args in [{"query": "something to stop milk boiling over"},
                 {"query": "office chair", "max_price": 10000},
                 {"query": "roti garam rakhne ka dabba", "in_stock": True},]:
        out = show(await client.call_tool("search_products", args))
        print(f"search_products{args}\n   mode: {out['search_mode']}, no_close_match: {out['no_close_match']}, limits: {out['limits_applied']}")
        for p in out["results"][:3]:
            print(f"   - {p['id']} {p['title']} (Rs {p['price_pkr']:,}, {'in stock' if p['in_stock'] else 'out of stock'})")
        print()
    print(json.dumps(show(await client.call_tool("get_product", {"product_id": "KIT-053"})), indent=1, ensure_ascii=False))

search_products{'query': 'something to stop milk boiling over'}
   mode: semantic_definitions, no_close_match: False, limits: {'max_price': None, 'in_stock': False}
   - KIT-053 Glass Boil-Over Preventer Disc (Rs 450, in stock)
   - KIT-049 Splatter Guard Screen, 33 cm (Rs 990, in stock)
   - KIT-002 Silicone Egg Yolk Separator, Food-Grade (Rs 380, in stock)

search_products{'query': 'office chair', 'max_price': 10000}
   mode: semantic_definitions, no_close_match: False, limits: {'max_price': 10000, 'in_stock': False}
   - FUR-018 Folding Steel Chair, Padded Seat (Rs 3,950, out of stock)
   - FUR-007 Bean Bag Chair, XL, with Filling (Rs 9,500, in stock)
   - FUR-037 Under-Desk Footrest, Adjustable Angle (Rs 2,450, in stock)

search_products{'query': 'roti garam rakhne ka dabba', 'in_stock': True}
   mode: semantic_definitions, no_close_match: False, limits: {'max_price': None, 'in_stock': True}
   - KIT-043 Insulated Hot Pot Casserole, 2.5 Litre (Rs 1,890, in stock)
   - KIT-023 Masala Dabba, 7 Bowls with Spoon, Stainless Steel (Rs 2,450, in stock)
   - ORG-031 Airtight Food Storage Containers, Set of 6 (Rs 2,950, in stock)

{
 "id": "KIT-053",
 "title": "Glass Boil-Over Preventer Disc",
 "price_pkr": 450,
 "in_stock": true,
 "category": "Kitchenware",
 "uses": [
  "prevent boil‑over while cooking rice",
  "keep stovetop clean",
  "reduce mess from sauces"
 ],
 "brand": "Handi House",
 "subcategory": "Cookware Tools",
 "stock_qty": 27,
 "specs": {
  "material": "Heat-resistant glass",
  "diameter": "7 cm"
 }
}

**Observations:** Through MCP, the tools give the same results as the website’s search. “Something to stop milk boiling over” returns the boil-over disc first, found by meaning. For “roti garam rakhne ka dabba” with in_stock, the hot pot casserole comes first, and the insulated roti box is left out because it is out of stock, so the stock limit is applied by the server, not left to the assistant. get_product returns the full record, including the uses from my Part 1 definitions, so a connected assistant can explain a product from the store’s own facts.

“Office chair” under Rs 10,000 shows the weakness found in Part 2: the store’s only office chair costs Rs 32,500, yet the server returns other chairs without flagging “no close match”. MCP exposes the search layer, not the chat, so an assistant using these tools gets the same unreliable no-match signal. It would need to check whether the results do the job, as the Ask Sahulat chat does.

## 4. Connecting an assistant
To use the server from Claude Desktop, a user adds it to the app's MCP configuration (paths shown for a local copy of the repository):

```json
{"mcpServers": {"sahulat-home": {
   "command": "python",
   "args": ["/path/to/data722-generative-search/mcp_server.py"],
   "env": {"GEMINI_API_KEY": "<your key>"}}}}
```

The assistant can then call search_products and get_product while chatting, so it can base its recommendations on the store’s real catalogue instead of guessing. Unlike the Ask Sahulat chat, nothing in the server checks what the assistant then says: grounding depends on the assistant using the tool results. Without a Gemini key the server still works, using keyword search, and says so in search_mode. I tested the server from Python (sections 2 and 3), not from Claude Desktop itself.